/*
 *  dev_rm_layoff.c
 *  l4_mgr
 *
 *  Created by yehjunying on 2011/6/3.
 *  Copyright 2011 __MyCompanyName__. All rights reserved.
 *
 */

#ifdef MIRROR_TO_ANALYZER_PORT_WAR_CPU_CODE
#undef MIRROR_TO_ANALYZER_PORT_WAR_CPU_CODE
#endif

#ifdef MIRROR_TO_ANALYZER_PORT_WAR_DESIGNATED_DEV_NUM_INDEX
#undef MIRROR_TO_ANALYZER_PORT_WAR_DESIGNATED_DEV_NUM_INDEX
#endif

#ifdef MIRROR_TO_ANALYZER_PORT_WAR_DEV_NUM
#undef MIRROR_TO_ANALYZER_PORT_WAR_DEV_NUM
#endif

#ifdef DEV_SWDRV_IS_CRAFT_PORT
#undef DEV_SWDRV_IS_CRAFT_PORT
#endif

#ifdef DEVRM_MAX_NBR_OF_TCAM_ENTRIES
#undef DEVRM_MAX_NBR_OF_TCAM_ENTRIES
#endif

#ifdef DEVRM_MAX_NBR_OF_TCAM_ROWS
#undef DEVRM_MAX_NBR_OF_TCAM_ROWS
#endif

#ifdef DEVRM_MAX_NBR_OF_PCL
#undef DEVRM_MAX_NBR_OF_PCL
#endif


#ifdef DEVRM_METER_POLICER_STAGE
#undef DEVRM_METER_POLICER_STAGE
#endif

#ifdef DEVRM_METER_MAX_NUM
#undef DEVRM_METER_MAX_NUM
#endif

#ifdef DEVRM_METER_MAX_NUM_BY_STAGE
#undef DEVRM_METER_MAX_NUM_BY_STAGE
#endif

#ifdef DEVRM_METER_INDEX_BASE
#undef DEVRM_METER_INDEX_BASE
#endif

#ifdef DEVRM_QOS_REMARKING_ENTRY_FIRST_IDX
#undef DEVRM_QOS_REMARKING_ENTRY_FIRST_IDX
#endif

#ifdef DEVRM_QOS_REMARKING_ENTRY_LAST_IDX
#undef DEVRM_QOS_REMARKING_ENTRY_LAST_IDX
#endif

#ifdef DEVRM_QOS_REMARKING_ENTRY_NUM
#undef DEVRM_QOS_REMARKING_ENTRY_NUM
#endif

#ifdef DEVRM_LOG
#undef DEVRM_LOG
#endif

#ifdef DEBUG_ERROR_MSG
#undef DEBUG_ERROR_MSG
#endif

#ifdef DEBUG_PRINT_STR
#undef DEBUG_PRINT_STR
#endif

#ifdef DEVRM_IS_DEBUG_ERROR_ON
#undef DEVRM_IS_DEBUG_ERROR_ON
#endif

#ifdef DEVRM_POLICER_STAGE
#undef DEVRM_POLICER_STAGE
#endif

#ifdef DEVRM_POLICER_STAGE_STR
#undef DEVRM_POLICER_STAGE_STR
#endif


