/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
* prvCpssDxChPortCtrl.h
*
* DESCRIPTION:
*       Includes types and values definition and initialization for the use of 
*       CPSS DxCh Port Control feature.
*
*
* FILE REVISION NUMBER:
*       $Revision: 4 $
*
*******************************************************************************/
#ifndef __prvCpssDxChPortCtrlh
#define __prvCpssDxChPortCtrlh

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <cpss/generic/cpssTypes.h>

/* serdesSpeed1 register value for 2.5 gig mode */
#define PRV_SERDES_SPEED_2500_REG_VAL_CNS 0x0000264A

/* serdesSpeed1 register value for 1 gig mode*/
#define PRV_SERDES_SPEED_1000_REG_VAL_CNS 0x0000213A

/* get flex port type */
#define PRV_CPSS_DXCH_FLEX_PORT_TYPE_MAC(devNum,portNum) \
        PRV_CPSS_PP_MAC(devNum)->phyPortInfoArray[portNum].portTypeOptions

/* at this moment max number of serdeses that could be occupied by port
   is 8 for XLG mode */
#define PRV_CPSS_DXCH_MAX_SERDES_NUM_PER_PORT_CNS 8

#define PRV_PER_PORT_LOOP_MAC for(localPort = startSerdes/2; localPort*2 < startSerdes+serdesesNum; localPort++)
#define PRV_PER_SERDES_LOOP_MAC for (i = startSerdes; i < startSerdes+serdesesNum; i++)

/* array defining possible interfaces/ports modes configuration options */
/* APPLICABLE DEVICES:  DxCh */
static GT_BOOL supportedPortsModes[PRV_CPSS_XG_PORT_OPTIONS_MAX_E][CPSS_PORT_INTERFACE_MODE_NA_E] =
{                                  /* R_10BIT  R_GMII    MII       SGMII     XGMII     MGMII   1000BASE_X    GMII    MII_PHY    QX          HX      RXAUI   100BASE_FX  QSGMII       XLG   LOCAL_XGMII */
/* PRV_CPSS_XG_PORT_XG_ONLY_E */    {GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE},
/* PRV_CPSS_XG_PORT_QX_ONLY_E */    {GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE},
/* PRV_CPSS_XG_PORT_HX_QX_ONLY_E */ {GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE},
/* PRV_CPSS_XG_PORT_XG_HX_QX_E */   {GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_TRUE , GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_TRUE , GT_TRUE , GT_TRUE , GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE},
/* PRV_CPSS_GE_PORT_GE_ONLY_E */    {GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE},
/* PRV_CPSS_XG_PORT_XLG_SGMII_E */  {GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_TRUE , GT_FALSE, GT_TRUE , GT_FALSE, GT_FALSE, GT_FALSE, GT_TRUE , GT_TRUE , GT_FALSE, GT_FALSE, GT_TRUE , GT_TRUE }
};

/* array defining serdes speed used in given interface mode for given port data speed */
/* APPLICABLE DEVICES:  DxChXcat and above. */
static PRV_CPSS_DXCH_PORT_SERDES_SPEED_ENT serdesFrequency[CPSS_PORT_INTERFACE_MODE_NA_E][CPSS_PORT_SPEED_NA_E] =
{                                               /* 10M                                      100M                                  1G                                        10G                                   12G                                       2.5G                                  5G                                        13.6G                                 20G                                   40G                                   16G */
/* CPSS_PORT_INTERFACE_MODE_REDUCED_10BIT_E */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_REDUCED_GMII_E  */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_MII_E           */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_SGMII_E         */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_1_25_E , PRV_CPSS_DXCH_PORT_SERDES_SPEED_1_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_1_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_3_125_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_XGMII_E         */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_3_125_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_3_75_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_4_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_6_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_5_E},
/* CPSS_PORT_INTERFACE_MODE_MGMII_E         */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_1000BASE_X_E,   */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_1_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_GMII_E,         */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_MII_PHY_E,      */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_QX_E,           */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_3_125_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_6_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_HX_E,           */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_6_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_3_125_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_RXAUI_E,        */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_6_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_100BASE_FX_E,   */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_1_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_QSGMII_E,       */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_XLG_E,          */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_5_156_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E},
/* CPSS_PORT_INTERFACE_MODE_LOCAL_XGMII_E   */  {PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E   , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_3_125_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_3_75_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E , PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E  , PRV_CPSS_DXCH_PORT_SERDES_SPEED_4_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_6_25_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E, PRV_CPSS_DXCH_PORT_SERDES_SPEED_NA_E}
};

/*******************************************************************************
* PRV_CPSS_PORT_MODE_SPEED_TEST_FUN
*
* DESCRIPTION:
*      The function checks if specific interface mode and speed compatible with 
*       given port interface
*
* INPUTS:
*       devNum  - device number
*       portNum - port number
*
* OUTPUTS:
*       status - pointer to test result: 
*         GT_TRUE - suggested mode/speed pair compatible with given port interface,
*         GT_FALSE - otherwise
*                                       
*
* RETURNS:
*       GT_OK           - on success,
*       GT_BAD_PARAM    - bad devNum, smiInterface
*       GT_BAD_PTR      - pointer to place data is NULL
*       GT_HW_ERROR     - hw error
*
* COMMENTS:
*       None.
*
*******************************************************************************/
typedef GT_STATUS (*PRV_CPSS_PORT_MODE_SPEED_TEST_FUN)
(
    IN  GT_U8   devNum,
    IN  GT_U8   portNum,
    OUT GT_BOOL *status
);

/* default array of supported by Lion port mode/speed auto detect and 
    configure options */
static CPSS_PORT_MODE_SPEED_STC lionDefaultPortModeSpeedOptionsArray[] = 
{
    {CPSS_PORT_INTERFACE_MODE_XLG_E,        CPSS_PORT_SPEED_40000_E},
    {CPSS_PORT_INTERFACE_MODE_XGMII_E,      CPSS_PORT_SPEED_20000_E},
    {CPSS_PORT_INTERFACE_MODE_XGMII_E,      CPSS_PORT_SPEED_10000_E},
    {CPSS_PORT_INTERFACE_MODE_RXAUI_E,      CPSS_PORT_SPEED_10000_E},
    {CPSS_PORT_INTERFACE_MODE_1000BASE_X_E, CPSS_PORT_SPEED_1000_E},
    {CPSS_PORT_INTERFACE_MODE_SGMII_E,      CPSS_PORT_SPEED_1000_E}
};

/* default array of supported by XCAT stacking ports mode/speed auto detect 
    and configure options */
static CPSS_PORT_MODE_SPEED_STC xcatDefaultStackPortModeSpeedOptionsArray[] = 
{
    {CPSS_PORT_INTERFACE_MODE_XGMII_E,      CPSS_PORT_SPEED_10000_E},
    {CPSS_PORT_INTERFACE_MODE_RXAUI_E,      CPSS_PORT_SPEED_10000_E},
    {CPSS_PORT_INTERFACE_MODE_1000BASE_X_E, CPSS_PORT_SPEED_1000_E},
    {CPSS_PORT_INTERFACE_MODE_SGMII_E,      CPSS_PORT_SPEED_2500_E},
    {CPSS_PORT_INTERFACE_MODE_SGMII_E,      CPSS_PORT_SPEED_1000_E}
};

/* default array of supported by XCAT network ports mode/speed auto detect 
    and configure options */
static CPSS_PORT_MODE_SPEED_STC xcatDefaultNetworkPortModeSpeedOptionsArray[] = 
{
    {CPSS_PORT_INTERFACE_MODE_QSGMII_E,     CPSS_PORT_SPEED_1000_E},
    {CPSS_PORT_INTERFACE_MODE_1000BASE_X_E, CPSS_PORT_SPEED_1000_E},
    {CPSS_PORT_INTERFACE_MODE_SGMII_E,      CPSS_PORT_SPEED_2500_E},
    {CPSS_PORT_INTERFACE_MODE_SGMII_E,      CPSS_PORT_SPEED_1000_E}
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __prvCpssDxChPortCtrlh */

