#ifndef SYS_VER_H
#define SYS_VER_H

#define SYS_VER_POST_VER "0.0.0.1"
#define SYS_VER_ROOTFS_VER "0.0.0.1"
#define SYS_VER_POST_CUSTOMIZED_VER ""
#define SYS_VER_ROOTFS_CUSTOMIZED_VER ""
#define SYS_VER_LOADER_COMPAT_VER_ORG_PART_START "*"
#define SYS_VER_LOADER_COMPAT_VER_ORG_PART_END "*"
#define SYS_VER_LOADER_COMPAT_VER_ACCTON_PART_START "*"
#define SYS_VER_LOADER_COMPAT_VER_ACCTON_PART_END "*"
#define SYS_VER_KERNEL_COMPAT_VER_ORG_PART_START "*"
#define SYS_VER_KERNEL_COMPAT_VER_ORG_PART_END "*"
#define SYS_VER_KERNEL_COMPAT_VER_ACCTON_PART_START "*"
#define SYS_VER_KERNEL_COMPAT_VER_ACCTON_PART_END "*"
#endif
