/*
 * Bsafe uHSM chip returncodes.
 *
 * $Copyright: Copyright 2008 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * $Id: bsafe_returncode.h,v 1.3 Broadcom SDK $
 */

#ifndef __BSAFE_RETURNCODE_H_
#define __BSAFE_RETURNCODE_H_

#ifndef BSAFE_RETURNCODE_BEGIN
#define BSAFE_RETURNCODE_BEGIN typedef enum bsafe_returncode {
#define BSAFE_RETURNCODE_END } bsafe_returncode_t;
#define BSAFE_RETURNCODE( name,value) name=value
#endif


BSAFE_RETURNCODE_BEGIN


/*
 * Define Declarations
 */

BSAFE_RETURNCODE( UHSM_SUCCESS			,0x0000),
BSAFE_RETURNCODE( UHSM_FAIL			,0x0001),
BSAFE_RETURNCODE( TPM_SUCCESS			,0x0000),
BSAFE_RETURNCODE( TPM_FAIL			,0x0001),

/*
 * these are related to command parsing
 */
BSAFE_RETURNCODE( CMD_MAX_LENGTH_ERR		,0x8002),
BSAFE_RETURNCODE( CMD_LENGTH_ERR		,0x8003),
BSAFE_RETURNCODE( CMD_UNKNOWN_ERR		,0x8004),
BSAFE_RETURNCODE( CMD_BAD_PARAM_ERR		,0x8005),
BSAFE_RETURNCODE( UNINIT_GLB_TIMER_ERR          ,0x8006),
BSAFE_RETURNCODE( BAD_CMD_ERR                   ,0x8007),

/*
 * these are related to OTP
 */
BSAFE_RETURNCODE( OTP_NOT_CLR_ERR		,0x8080),
BSAFE_RETURNCODE( OTP_PREV_PROG_ERR		,0x8081),
BSAFE_RETURNCODE( OTP_PROG_FAIL_ERR		,0x8082),
BSAFE_RETURNCODE( OTP_NOT_PROG_ERR		,0x8083),

/*
 * these are related to KEK or AKEY
 */
BSAFE_RETURNCODE( KEY_CACHE_ERR			,0x0100),

BSAFE_RETURNCODE( KEK_BAD_TYPE_ERR		,0x0101),
BSAFE_RETURNCODE( KEK_BAD_SIZE_ERR		,0x0102),
BSAFE_RETURNCODE( KEK_BAD_STAT_ERR		,0x0103),
BSAFE_RETURNCODE( KEK_BAD_LOC_ERR		,0x0104),
BSAFE_RETURNCODE( KEK_BKT_FULL_ERR		,0x8105),
BSAFE_RETURNCODE( KEK_POLICY_ERR		,0x8106),
BSAFE_RETURNCODE( KEK_TIME_EXP_ERR		,0x8107),

BSAFE_RETURNCODE( AKEY_BAD_TYPE_ERR		,0x0201),
BSAFE_RETURNCODE( AKEY_BAD_SIZE_ERR		,0x0202),
BSAFE_RETURNCODE( AKEY_BAD_STAT_ERR		,0x0203),
BSAFE_RETURNCODE( AKEY_BAD_LOC_ERR		,0x0204),
BSAFE_RETURNCODE( AKEY_BKT_FULL_ERR		,0x8205),
BSAFE_RETURNCODE( AKEY_POLICY_ERR		,0x8206),
BSAFE_RETURNCODE( AKEY_TIME_EXP_ERR		,0x8207),

/*
 * these are related to OTP configuration
 */
BSAFE_RETURNCODE( AUTHORIZATION_VLD_ERR		,0x0300),
BSAFE_RETURNCODE( DIS_USER_AUTH_ERR		,0x0301),
BSAFE_RETURNCODE( ENABLE_USERKEY_ERR		,0x0302),
BSAFE_RETURNCODE( DIS_RAWRNG_ERR		,0x0303),
BSAFE_RETURNCODE( DIS_USERSTATUS_ERR		,0x0304),

/*
 * these are more specific to individual commands
 */
BSAFE_RETURNCODE( SELFTEST_HW_FAIL_ERR		,0x0400),
BSAFE_RETURNCODE( SELFTEST_DONE_ERR		,0x0401),

BSAFE_RETURNCODE( LDCFG_INVLD_KMP_ERR		,0x0420),
BSAFE_RETURNCODE( LDCFG_SIG_ERR			,0x0421),
BSAFE_RETURNCODE( LDCFG_MSGID_ERR		,0x0422),

BSAFE_RETURNCODE( USERAUTH_TIMEOUT_ERR          ,0x0440),

BSAFE_RETURNCODE( DLIES_NO_KS_ERR		,0x0500),
BSAFE_RETURNCODE( DLIES_CACHE_ERR		,0x0501),
BSAFE_RETURNCODE( DLIES_NEST_LVL_ERR		,0x0502),
BSAFE_RETURNCODE( DLIES_LOC_ERR			,0x0503),
BSAFE_RETURNCODE( DLIES_MSGID_ERR		,0x0504),
BSAFE_RETURNCODE( DLIES_DECRYPT_ERR		,0x0505),
BSAFE_RETURNCODE( DLIES_MAC_ERR			,0x0506),

/*
 * these are more related to hardware modules
 */
BSAFE_RETURNCODE( DES_BLK_SIZE_ERR		,0x0800),
BSAFE_RETURNCODE( PKE_UNKNOWN_OP_ERR		,0x0820),
BSAFE_RETURNCODE( HSH_MODE_ERR			,0x0840),
BSAFE_RETURNCODE( HSH_BLK_SIZE_ERR		,0x0841),
BSAFE_RETURNCODE( RNG_TYPE_ERR			,0x0860),
BSAFE_RETURNCODE( RNG_TEST_FAIL_ERR		,0x0861)


BSAFE_RETURNCODE_END

#endif /* __BSAFE_RETURN_H_ */

