/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Thu Sep 18 11:48:45 2003
 **** from files:
 ****  ..\MibFiles\SnmpFramework_Rfc2271.mib, ctl\SnmpFramework_Rfc2271.ctl,
 ****  ..\MibFiles\SnmpTarget_Rfc3413.mib, ctl\SnmpTarget_Rfc3413.ctl,
 ****  ..\MibFiles\SnmpCommunity_Rfc2576.mib
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_2576_H
#define  LEAF_2576_H

#define LEAF_snmpCommunityIndex	1
#define MINSIZE_snmpCommunityIndex	1L
#define MAXSIZE_snmpCommunityIndex	32L
#define LEAF_snmpCommunityName	2
#define LEAF_snmpCommunitySecurityName	3
#define MINSIZE_snmpCommunitySecurityName	1L
#define MAXSIZE_snmpCommunitySecurityName	32L
#define LEAF_snmpCommunityContextEngineID	4
#define MINSIZE_snmpCommunityContextEngineID	1L
#define MAXSIZE_snmpCommunityContextEngineID	32L
#define LEAF_snmpCommunityContextName	5
#define MINSIZE_snmpCommunityContextName	0L
#define MAXSIZE_snmpCommunityContextName	32L
#define LEAF_snmpCommunityTransportTag	6
#define MINSIZE_snmpCommunityTransportTag	0L
#define MAXSIZE_snmpCommunityTransportTag	255L
#define LEAF_snmpCommunityStorageType	7
#define VAL_snmpCommunityStorageType_other	1L
#define VAL_snmpCommunityStorageType_volatile	2L
#define VAL_snmpCommunityStorageType_nonVolatile	3L
#define VAL_snmpCommunityStorageType_permanent	4L
#define VAL_snmpCommunityStorageType_readOnly	5L
#define LEAF_snmpCommunityStatus	8
#define VAL_snmpCommunityStatus_active	1L
#define VAL_snmpCommunityStatus_notInService	2L
#define VAL_snmpCommunityStatus_notReady	3L
#define VAL_snmpCommunityStatus_createAndGo	4L
#define VAL_snmpCommunityStatus_createAndWait	5L
#define VAL_snmpCommunityStatus_destroy	6L
#define LEAF_snmpTargetAddrTMask	1
#define MINSIZE_snmpTargetAddrTMask	0L
#define MAXSIZE_snmpTargetAddrTMask	255L
#define LEAF_snmpTargetAddrMMS	2
#define MIN_snmpTargetAddrMMS_1	0L
#define MAX_snmpTargetAddrMMS_1	0L
#define MIN_snmpTargetAddrMMS_2	484L
#define MAX_snmpTargetAddrMMS_2	2147483647L
#define LEAF_snmpTrapAddress	3
#define LEAF_snmpTrapCommunity	4

#endif /* end of #ifndef  LEAF_2576_H */
