/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Wed Apr 02 21:35:48 2003
 **** from files:
 ****  ..\StdMib\Rfc1213.mib, ctl\Rfc1213.ctl, ..\StdMib\Rmon_Rfc2819.mib,
 ****  ctl\Rmon_Rfc2819.ctl, ..\StdMib\TokenRingRmon_Rfc1513.mib,
 ****  ctl\TokenRingRmon_Rfc1513.ctl, ..\StdMib\Rmon2_Rfc2021.mib,
 ****  ctl\Rmon2_Rfc2021.ctl, ..\StdMib\Bridge_Rfc1493.mib,
 ****  ctl\Bridge_Rfc1493.ctl, ..\StdMib\SnmpFramework_Rfc2271.mib,
 ****  ctl\SnmpFramework_Rfc2271.ctl, ..\StdMib\PBridge_Rfc2674.mib,
 ****  ctl\PBridge_Rfc2674.ctl, ..\StdMib\QBridge_Rfc2674.mib,
 ****  ctl\QBridge_Rfc2674.ctl, ..\StdMib\IanaIfType_Rfc1573.mib,
 ****  ..\StdMib\SnmpV2_Rfc1907.mib, ctl\SnmpV2_Rfc1907.ctl,
 ****  ..\StdMib\If_Rfc2863.mib, ctl\If_Rfc2863.ctl,
 ****  ..\StdMib\Ieee8023Lag_lacp.mib
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_IEEE8023LAG_H
#define  LEAF_IEEE8023LAG_H

#define LEAF_dot3adAggIndex	1
#define MIN_dot3adAggIndex	1L
#define MAX_dot3adAggIndex	2147483647L
#define LEAF_dot3adAggMACAddress	2
#define SIZE_dot3adAggMACAddress	6L
#define LEAF_dot3adAggActorSystemPriority	3
#define MIN_dot3adAggActorSystemPriority	0L
#define MAX_dot3adAggActorSystemPriority	65535L
#define LEAF_dot3adAggActorSystemID	4
#define SIZE_dot3adAggActorSystemID	6L
#define LEAF_dot3adAggAggregateOrIndividual	5
#define VAL_dot3adAggAggregateOrIndividual_true	1L
#define VAL_dot3adAggAggregateOrIndividual_false	2L
#define LEAF_dot3adAggActorAdminKey	6
#define MIN_dot3adAggActorAdminKey	0L
#define MAX_dot3adAggActorAdminKey	65535L
#define LEAF_dot3adAggActorOperKey	7
#define MIN_dot3adAggActorOperKey	0L
#define MAX_dot3adAggActorOperKey	65535L
#define LEAF_dot3adAggPartnerSystemID	8
#define SIZE_dot3adAggPartnerSystemID	6L
#define LEAF_dot3adAggPartnerSystemPriority	9
#define MIN_dot3adAggPartnerSystemPriority	0L
#define MAX_dot3adAggPartnerSystemPriority	65535L
#define LEAF_dot3adAggPartnerOperKey	10
#define MIN_dot3adAggPartnerOperKey	0L
#define MAX_dot3adAggPartnerOperKey	65535L
#define LEAF_dot3adAggCollectorMaxDelay	11
#define MIN_dot3adAggCollectorMaxDelay	0L
#define MAX_dot3adAggCollectorMaxDelay	65535L
#define LEAF_dot3adAggPortListPorts	1
#define LEAF_dot3adAggPortIndex	1
#define MIN_dot3adAggPortIndex	1L
#define MAX_dot3adAggPortIndex	2147483647L
#define LEAF_dot3adAggPortActorSystemPriority	2
#define MIN_dot3adAggPortActorSystemPriority	0L
#define MAX_dot3adAggPortActorSystemPriority	65535L
#define LEAF_dot3adAggPortActorSystemID	3
#define SIZE_dot3adAggPortActorSystemID	6L
#define LEAF_dot3adAggPortActorAdminKey	4
#define MIN_dot3adAggPortActorAdminKey	0L
#define MAX_dot3adAggPortActorAdminKey	65535L
#define LEAF_dot3adAggPortActorOperKey	5
#define MIN_dot3adAggPortActorOperKey	0L
#define MAX_dot3adAggPortActorOperKey	65535L
#define LEAF_dot3adAggPortPartnerAdminSystemPriority	6
#define MIN_dot3adAggPortPartnerAdminSystemPriority	0L
#define MAX_dot3adAggPortPartnerAdminSystemPriority	65535L
#define LEAF_dot3adAggPortPartnerOperSystemPriority	7
#define MIN_dot3adAggPortPartnerOperSystemPriority	0L
#define MAX_dot3adAggPortPartnerOperSystemPriority	65535L
#define LEAF_dot3adAggPortPartnerAdminSystemID	8
#define SIZE_dot3adAggPortPartnerAdminSystemID	6L
#define LEAF_dot3adAggPortPartnerOperSystemID	9
#define SIZE_dot3adAggPortPartnerOperSystemID	6L
#define LEAF_dot3adAggPortPartnerAdminKey	10
#define MIN_dot3adAggPortPartnerAdminKey	0L
#define MAX_dot3adAggPortPartnerAdminKey	65535L
#define LEAF_dot3adAggPortPartnerOperKey	11
#define MIN_dot3adAggPortPartnerOperKey	0L
#define MAX_dot3adAggPortPartnerOperKey	65535L
#define LEAF_dot3adAggPortSelectedAggID	12
#define MIN_dot3adAggPortSelectedAggID	1L
#define MAX_dot3adAggPortSelectedAggID	2147483647L
#define LEAF_dot3adAggPortAttachedAggID	13
#define MIN_dot3adAggPortAttachedAggID	1L
#define MAX_dot3adAggPortAttachedAggID	2147483647L
#define LEAF_dot3adAggPortActorPort	14
#define MIN_dot3adAggPortActorPort	0L
#define MAX_dot3adAggPortActorPort	65535L
#define LEAF_dot3adAggPortActorPortPriority	15
#define MIN_dot3adAggPortActorPortPriority	0L
#define MAX_dot3adAggPortActorPortPriority	65535L
#define LEAF_dot3adAggPortPartnerAdminPort	16
#define MIN_dot3adAggPortPartnerAdminPort	0L
#define MAX_dot3adAggPortPartnerAdminPort	65535L
#define LEAF_dot3adAggPortPartnerOperPort	17
#define MIN_dot3adAggPortPartnerOperPort	0L
#define MAX_dot3adAggPortPartnerOperPort	65535L
#define LEAF_dot3adAggPortPartnerAdminPortPriority	18
#define MIN_dot3adAggPortPartnerAdminPortPriority	0L
#define MAX_dot3adAggPortPartnerAdminPortPriority	65535L
#define LEAF_dot3adAggPortPartnerOperPortPriority	19
#define MIN_dot3adAggPortPartnerOperPortPriority	0L
#define MAX_dot3adAggPortPartnerOperPortPriority	65535L
#define LEAF_dot3adAggPortActorAdminState	20
#define VAL_dot3adAggPortActorAdminState_lacpActivity	0L
#define VAL_dot3adAggPortActorAdminState_lacpTimeout	1L
#define VAL_dot3adAggPortActorAdminState_aggregation	2L
#define VAL_dot3adAggPortActorAdminState_synchronization	3L
#define VAL_dot3adAggPortActorAdminState_collecting	4L
#define VAL_dot3adAggPortActorAdminState_distributing	5L
#define VAL_dot3adAggPortActorAdminState_defaulted	6L
#define VAL_dot3adAggPortActorAdminState_expired	7L
#define LEAF_dot3adAggPortActorOperState	21
#define VAL_dot3adAggPortActorOperState_lacpActivity	0L
#define VAL_dot3adAggPortActorOperState_lacpTimeout	1L
#define VAL_dot3adAggPortActorOperState_aggregation	2L
#define VAL_dot3adAggPortActorOperState_synchronization	3L
#define VAL_dot3adAggPortActorOperState_collecting	4L
#define VAL_dot3adAggPortActorOperState_distributing	5L
#define VAL_dot3adAggPortActorOperState_defaulted	6L
#define VAL_dot3adAggPortActorOperState_expired	7L
#define LEAF_dot3adAggPortPartnerAdminState	22
#define VAL_dot3adAggPortPartnerAdminState_lacpActivity	0L
#define VAL_dot3adAggPortPartnerAdminState_lacpTimeout	1L
#define VAL_dot3adAggPortPartnerAdminState_aggregation	2L
#define VAL_dot3adAggPortPartnerAdminState_synchronization	3L
#define VAL_dot3adAggPortPartnerAdminState_collecting	4L
#define VAL_dot3adAggPortPartnerAdminState_distributing	5L
#define VAL_dot3adAggPortPartnerAdminState_defaulted	6L
#define VAL_dot3adAggPortPartnerAdminState_expired	7L
#define LEAF_dot3adAggPortPartnerOperState	23
#define VAL_dot3adAggPortPartnerOperState_lacpActivity	0L
#define VAL_dot3adAggPortPartnerOperState_lacpTimeout	1L
#define VAL_dot3adAggPortPartnerOperState_aggregation	2L
#define VAL_dot3adAggPortPartnerOperState_synchronization	3L
#define VAL_dot3adAggPortPartnerOperState_collecting	4L
#define VAL_dot3adAggPortPartnerOperState_distributing	5L
#define VAL_dot3adAggPortPartnerOperState_defaulted	6L
#define VAL_dot3adAggPortPartnerOperState_expired	7L
#define LEAF_dot3adAggPortAggregateOrIndividual	24
#define VAL_dot3adAggPortAggregateOrIndividual_true	1L
#define VAL_dot3adAggPortAggregateOrIndividual_false	2L
#define LEAF_dot3adAggPortStatsLACPDUsRx	1
#define LEAF_dot3adAggPortStatsMarkerPDUsRx	2
#define LEAF_dot3adAggPortStatsMarkerResponsePDUsRx	3
#define LEAF_dot3adAggPortStatsUnknownRx	4
#define LEAF_dot3adAggPortStatsIllegalRx	5
#define LEAF_dot3adAggPortStatsLACPDUsTx	6
#define LEAF_dot3adAggPortStatsMarkerPDUsTx	7
#define LEAF_dot3adAggPortStatsMarkerResponsePDUsTx	8
#define LEAF_dot3adAggPortDebugRxState	1
#define VAL_dot3adAggPortDebugRxState_currentRx	1L
#define VAL_dot3adAggPortDebugRxState_expired	2L
#define VAL_dot3adAggPortDebugRxState_defaulted	3L
#define VAL_dot3adAggPortDebugRxState_initialize	4L
#define VAL_dot3adAggPortDebugRxState_lacpDisabled	5L
#define VAL_dot3adAggPortDebugRxState_portDisabled	6L
#define LEAF_dot3adAggPortDebugLastRxTime	2
#define LEAF_dot3adAggPortDebugMuxState	3
#define VAL_dot3adAggPortDebugMuxState_detached	1L
#define VAL_dot3adAggPortDebugMuxState_waiting	2L
#define VAL_dot3adAggPortDebugMuxState_attached	3L
#define VAL_dot3adAggPortDebugMuxState_collecting	4L
#define VAL_dot3adAggPortDebugMuxState_distributing	5L
#define VAL_dot3adAggPortDebugMuxState_collectingDistributing	6L
#define LEAF_dot3adAggPortDebugMuxReason	4
#define MINSIZE_dot3adAggPortDebugMuxReason	0L
#define MAXSIZE_dot3adAggPortDebugMuxReason	255L
#define LEAF_dot3adAggPortDebugActorChurnState	5
#define VAL_dot3adAggPortDebugActorChurnState_noChurn	1L
#define VAL_dot3adAggPortDebugActorChurnState_churn	2L
#define VAL_dot3adAggPortDebugActorChurnState_churnMonitor	3L
#define LEAF_dot3adAggPortDebugPartnerChurnState	6
#define VAL_dot3adAggPortDebugPartnerChurnState_noChurn	1L
#define VAL_dot3adAggPortDebugPartnerChurnState_churn	2L
#define VAL_dot3adAggPortDebugPartnerChurnState_churnMonitor	3L
#define LEAF_dot3adAggPortDebugActorChurnCount	7
#define LEAF_dot3adAggPortDebugPartnerChurnCount	8
#define LEAF_dot3adAggPortDebugActorSyncTransitionCount	9
#define LEAF_dot3adAggPortDebugPartnerSyncTransitionCount	10
#define LEAF_dot3adAggPortDebugActorChangeCount	11
#define LEAF_dot3adAggPortDebugPartnerChangeCount	12
#define LEAF_dot3adTablesLastChanged	3
#define LEAF_snmpTrapOID	1
#define LEAF_snmpTrapEnterprise	3

#endif /* end of #ifndef  LEAF_IEEE8023LAG_H */
