/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 ****
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 ****
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 ****
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 ****
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 ****
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 ****
 **** DO NOT MODIFY THIS FILE BY HAND.
 ****
 **** Last build date: Fri Nov  9 22:47:38 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1447-SNMPv2-PARTY.mib, Rfc1450-SNMPv2.mib,
 ****  E-Rfc1573-IANAifType.mib, Rfc2863-IF.mib, Rfc2933-IGMP-STD.mib,
 ****  rfc2933.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_mld_H
#define  LEAF_mld_H

#define LEAF_mldInterfaceIfIndex	1
#define MIN_mldInterfaceIfIndex	1L
#define MAX_mldInterfaceIfIndex	2147483647L
#define LEAF_mldInterfaceQueryInterval	2
#define LEAF_mldInterfaceStatus	3
#define VAL_mldInterfaceStatus_active	1L
#define VAL_mldInterfaceStatus_notInService	2L
#define VAL_mldInterfaceStatus_notReady	3L
#define VAL_mldInterfaceStatus_createAndGo	4L
#define VAL_mldInterfaceStatus_createAndWait	5L
#define VAL_mldInterfaceStatus_destroy	6L
#define LEAF_mldInterfaceVersion	4
#define LEAF_mldInterfaceQuerier	5
#define LEAF_mldInterfaceQueryMaxResponseTime	6
#define MIN_mldInterfaceQueryMaxResponseTime	0L
#define MAX_mldInterfaceQueryMaxResponseTime	255L
#define LEAF_mldInterfaceQuerierUpTime	7
#define LEAF_mldInterfaceQuerierExpiryTime	8
#define LEAF_mldInterfaceVersion1QuerierTimer	9
#define LEAF_mldInterfaceWrongVersionQueries	10
#define LEAF_mldInterfaceJoins	11
#define LEAF_mldInterfaceProxyIfIndex	12
#define MIN_mldInterfaceProxyIfIndex	0L
#define MAX_mldInterfaceProxyIfIndex	2147483647L
#define LEAF_mldInterfaceGroups	13
#define LEAF_mldInterfaceRobustness	14
#define MIN_mldInterfaceRobustness	1L
#define MAX_mldInterfaceRobustness	255L
#define LEAF_mldInterfaceLastMembQueryIntvl	15
#define MIN_mldInterfaceLastMembQueryIntvl	0L
#define MAX_mldInterfaceLastMembQueryIntvl	255L
#define LEAF_mldCacheAddress	1
#define LEAF_mldCacheIfIndex	2
#define MIN_mldCacheIfIndex	1L
#define MAX_mldCacheIfIndex	2147483647L
#define LEAF_mldCacheSelf	3
#define VAL_mldCacheSelf_true	1L
#define VAL_mldCacheSelf_false	2L
#define LEAF_mldCacheLastReporter	4
#define LEAF_mldCacheUpTime	5
#define LEAF_mldCacheExpiryTime	6
#define LEAF_mldCacheStatus	7
#define VAL_mldCacheStatus_active	1L
#define VAL_mldCacheStatus_notInService	2L
#define VAL_mldCacheStatus_notReady	3L
#define VAL_mldCacheStatus_createAndGo	4L
#define VAL_mldCacheStatus_createAndWait	5L
#define VAL_mldCacheStatus_destroy	6L
#define LEAF_mldCacheVersion1HostTimer	8

#endif /* end of #ifndef  LEAF_2933_H */

