/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Thu May 30 21:59:14 2002
 **** from files:
 ****  Rfc1907.mib, rfc1907.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_1907_H
#define  LEAF_1907_H

#define LEAF_sysDescr	1
#define MINSIZE_sysDescr	0L
#define MAXSIZE_sysDescr	255L
#define LEAF_sysObjectID	2
#define LEAF_sysUpTime	3
#define LEAF_sysContact	4
#define MINSIZE_sysContact	0L
#define MAXSIZE_sysContact	255L
#define LEAF_sysName	5
#define MINSIZE_sysName	0L
#define MAXSIZE_sysName	255L
#define LEAF_sysLocation	6
#define MINSIZE_sysLocation	0L
#define MAXSIZE_sysLocation	255L
#define LEAF_sysServices	7
#define MIN_sysServices	0L
#define MAX_sysServices	127L
#define LEAF_sysORLastChange	8
#define LEAF_sysORIndex	1
#define MIN_sysORIndex	1L
#define MAX_sysORIndex	2147483647L
#define LEAF_sysORID	2
#define LEAF_sysORDescr	3
#define MINSIZE_sysORDescr	0L
#define MAXSIZE_sysORDescr	255L
#define LEAF_sysORUpTime	4
#define LEAF_snmpInPkts	1
#define LEAF_snmpOutPkts	2
#define LEAF_snmpInBadVersions	3
#define LEAF_snmpInBadCommunityNames	4
#define LEAF_snmpInBadCommunityUses	5
#define LEAF_snmpInASNParseErrs	6
#define LEAF_snmpInTooBigs	8
#define LEAF_snmpInNoSuchNames	9
#define LEAF_snmpInBadValues	10
#define LEAF_snmpInReadOnlys	11
#define LEAF_snmpInGenErrs	12
#define LEAF_snmpInTotalReqVars	13
#define LEAF_snmpInTotalSetVars	14
#define LEAF_snmpInGetRequests	15
#define LEAF_snmpInGetNexts	16
#define LEAF_snmpInSetRequests	17
#define LEAF_snmpInGetResponses	18
#define LEAF_snmpInTraps	19
#define LEAF_snmpOutTooBigs	20
#define LEAF_snmpOutNoSuchNames	21
#define LEAF_snmpOutBadValues	22
#define LEAF_snmpOutGenErrs	24
#define LEAF_snmpOutGetRequests	25
#define LEAF_snmpOutGetNexts	26
#define LEAF_snmpOutSetRequests	27
#define LEAF_snmpOutGetResponses	28
#define LEAF_snmpOutTraps	29
#define LEAF_snmpEnableAuthenTraps	30
#define VAL_snmpEnableAuthenTraps_enabled	1L
#define VAL_snmpEnableAuthenTraps_disabled	2L
#define LEAF_snmpSilentDrops	31
#define LEAF_snmpProxyDrops	32
#define LEAF_snmpTrapOID	1
#define LEAF_snmpTrapEnterprise	3
#define LEAF_snmpSetSerialNo	1
#define MIN_snmpSetSerialNo	0L
#define MAX_snmpSetSerialNo	2147483647L

#endif /* end of #ifndef  LEAF_1907_H */
