#define LEAF_secureSlotIndex	1
#define MIN_secureSlotIndex	1L
#define MAX_secureSlotIndex	1024L
#define LEAF_securePortIndex	2
#define MIN_securePortIndex	1L
#define MAX_securePortIndex	1024L
#define LEAF_securePortMode	3
#define VAL_securePortMode_noRestrictions	1L
#define VAL_securePortMode_continuousLearning	2L
#define VAL_securePortMode_autoLearn	3L
#define VAL_securePortMode_secure	4L
#define VAL_securePortMode_userLogin	5L
#define VAL_securePortMode_userLoginSecure	6L
#define VAL_securePortMode_userLoginWithOUI	7L
#define VAL_securePortMode_macAddressWithRadius	8L
#define VAL_securePortMode_macAddressOrUserLoginSecure	9L
#define VAL_securePortMode_macAddressElseUserLoginSecure	10L
#define LEAF_secureNeedToKnowMode	4
#define VAL_secureNeedToKnowMode_notAvailable	1L
#define VAL_secureNeedToKnowMode_disabled	2L
#define VAL_secureNeedToKnowMode_needToKnowOnly	3L
#define VAL_secureNeedToKnowMode_needToKnowWithBroadcastsAllowed	4L
#define VAL_secureNeedToKnowMode_needToKnowWithMulticastsAllowed	5L
#define VAL_secureNeedToKnowMode_permanentNeedToKnowOnly	6L
#define VAL_secureNeedToKnowMode_permanentNeedToKnowWithBroadcastsAllowed	7L
#define VAL_secureNeedToKnowMode_permanentNeedToKnowWithMulticastsAllowed	8L
#define LEAF_secureIntrusionAction	5
#define VAL_secureIntrusionAction_notAvailable	1L
#define VAL_secureIntrusionAction_noAction	2L
#define VAL_secureIntrusionAction_disablePort	3L
#define VAL_secureIntrusionAction_disablePortTemporarily	4L
#define VAL_secureIntrusionAction_allowDefaultAccess	5L
#define VAL_secureIntrusionAction_blockMacAddress	6L
#define LEAF_secureNumberAddresses	6
#define LEAF_secureNumberAddressesStored	7
#define LEAF_secureMaximumAddresses	8
#define LEAF_secureAddrSlotIndex	1
#define MIN_secureAddrSlotIndex	1L
#define MAX_secureAddrSlotIndex	1024L
#define LEAF_secureAddrPortIndex	2
#define MIN_secureAddrPortIndex	1L
#define MAX_secureAddrPortIndex	1024L
#define LEAF_secureAddrMAC	3
#define SIZE_secureAddrMAC	6L
#define LEAF_secureAddrRowStatus	4
#define VAL_secureAddrRowStatus_active	1L
#define VAL_secureAddrRowStatus_notInService	2L
#define VAL_secureAddrRowStatus_notReady	3L
#define VAL_secureAddrRowStatus_createAndGo	4L
#define VAL_secureAddrRowStatus_createAndWait	5L
#define VAL_secureAddrRowStatus_destroy	6L
#define LEAF_secureStop	3
#define LEAF_securePortSecurityControl	4
#define VAL_securePortSecurityControl_enabled	1L
#define VAL_securePortSecurityControl_disabled	2L
#define LEAF_secureOUISlotIndex	1
#define MIN_secureOUISlotIndex	1L
#define MAX_secureOUISlotIndex	1024L
#define LEAF_secureOUI	2
#define SIZE_secureOUI	3L
#define LEAF_secureOUIRowStatus	3
#define VAL_secureOUIRowStatus_active	1L
#define VAL_secureOUIRowStatus_notInService	2L
#define VAL_secureOUIRowStatus_notReady	3L
#define VAL_secureOUIRowStatus_createAndGo	4L
#define VAL_secureOUIRowStatus_createAndWait	5L
#define VAL_secureOUIRowStatus_destroy	6L
#define LEAF_securePortVlanMembershipList	6
#define MINSIZE_securePortVlanMembershipList	0L
#define MAXSIZE_securePortVlanMembershipList	255L
#define LEAF_secureRadaDefaultSessionTime	1
#define MIN_secureRadaDefaultSessionTime	1L
#define MAX_secureRadaDefaultSessionTime	1000000L
#define LEAF_secureRadaHoldoffTime	2
#define MIN_secureRadaHoldoffTime	1L
#define MAX_secureRadaHoldoffTime	1000000L
#define LEAF_secureRadaReauthenticate	3
#define SIZE_secureRadaReauthenticate	6L
#define LEAF_secureRadaAuthMode	4
#define VAL_secureRadaAuthMode_papUsernameAsMacAddress	1L
#define VAL_secureRadaAuthMode_papUsernameFixed	2L
#define LEAF_secureRadaAuthUsername	5
#define MINSIZE_secureRadaAuthUsername	1L
#define MAXSIZE_secureRadaAuthUsername	10L
#define LEAF_secureRadaAuthPassword	6
#define MINSIZE_secureRadaAuthPassword	0L
#define MAXSIZE_secureRadaAuthPassword	10L


