/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Thu Dec 15 14:34:33 2005
 **** from files:
 ****  ..\MibFiles\Rfc1213.mib, ctl\Rfc1213.ctl,
 ****  ..\MibFiles\IanaIfType_Rfc1573.mib, ..\MibFiles\SnmpV2_Rfc1907.mib,
 ****  ctl\SnmpV2_Rfc1907.ctl, ..\MibFiles\If_Rfc2863.mib, ctl\If_Rfc2863.ctl,
 ****  ..\MibFiles\Rmon_Rfc2819.mib, ctl\Rmon_Rfc2819.ctl,
 ****  ..\MibFiles\TokenRingRmon_Rfc1513.mib, ctl\TokenRingRmon_Rfc1513.ctl,
 ****  ..\MibFiles\Rmon2_Rfc2021.mib, ctl\Rmon2_Rfc2021.ctl,
 ****  ..\MibFiles\Bridge_Rfc1493.mib, ctl\Bridge_Rfc1493.ctl,
 ****  ..\MibFiles\PBridge_Rfc2674.mib, ctl\PBridge_Rfc2674.ctl,
 ****  ..\MibFiles\SnmpFramework_Rfc2271.mib, ctl\SnmpFramework_Rfc2271.ctl,
 ****  ..\MibFiles\QBridge_Rfc2674.mib, ctl\QBridge_Rfc2674.ctl,
 ****  ..\MibFiles\Vrrp_Rfc2787.mib, ctl\Vrrp_Rfc2787.ctl,
 ****  ..\MibFiles\HcnumTc.mib, ..\MibFiles\Ip_Rfc2011.mib,
 ****  ..\MibFiles\InetAddress_Rfc3291.mib,
 ****  ..\MibFiles\IntegratedServices_Rfc2213.mib,
 ****  ..\MibFiles\DiffServDscpTc_Rfc3289.mib,
 ****  ..\MibFiles\DiffServ_Rfc3289.mib, ..\MibFiles\Ieee8021Pae.mib,
 ****  ctl\Ieee8021Pae.ctl, ..\MibFiles\IANA-ADDRESS-FAMILY-NUMBERS.mib,
 ****  ..\MibFiles\LLDP.MIB
 ******************************************************************************
 ******************************************************************************
 */

#define LEAF_lldpMessageTxInterval	1
#define MIN_lldpMessageTxInterval	5L
#define MAX_lldpMessageTxInterval	32768L
#define LEAF_lldpMessageTxHoldMultiplier	2
#define MIN_lldpMessageTxHoldMultiplier	2L
#define MAX_lldpMessageTxHoldMultiplier	10L
#define LEAF_lldpReinitDelay	3
#define MIN_lldpReinitDelay	1L
#define MAX_lldpReinitDelay	10L
#define LEAF_lldpTxDelay	4
#define MIN_lldpTxDelay	1L
#define MAX_lldpTxDelay	8192L
#define LEAF_lldpNotificationInterval	5
#define MIN_lldpNotificationInterval	5L
#define MAX_lldpNotificationInterval	3600L
#define LEAF_lldpPortConfigPortNum	1
#define MIN_lldpPortConfigPortNum	1L
#define MAX_lldpPortConfigPortNum	4096L
#define LEAF_lldpPortConfigAdminStatus	2
#define VAL_lldpPortConfigAdminStatus_txOnly	1L
#define VAL_lldpPortConfigAdminStatus_rxOnly	2L
#define VAL_lldpPortConfigAdminStatus_txAndRx	3L
#define VAL_lldpPortConfigAdminStatus_disabled	4L
#define LEAF_lldpPortConfigNotificationEnable	3
#define VAL_lldpPortConfigNotificationEnable_true	1L
#define VAL_lldpPortConfigNotificationEnable_false	2L
#define LEAF_lldpPortConfigTLVsTxEnable	4
#define VAL_lldpPortConfigTLVsTxEnable_portDesc	0L
#define VAL_lldpPortConfigTLVsTxEnable_sysName	1L
#define VAL_lldpPortConfigTLVsTxEnable_sysDesc	2L
#define VAL_lldpPortConfigTLVsTxEnable_sysCap	3L
#define SIZE_lldpPortConfigTLVsTxEnable    1L    
#define LEAF_lldpConfigManAddrPortsTxEnable	1
#define MINSIZE_lldpConfigManAddrPortsTxEnable	0L
#define MAXSIZE_lldpConfigManAddrPortsTxEnable	512L
#define LEAF_lldpStatsRemTablesLastChangeTime	1
#define LEAF_lldpStatsRemTablesInserts	2
#define LEAF_lldpStatsRemTablesDeletes	3
#define LEAF_lldpStatsRemTablesDrops	4
#define LEAF_lldpStatsRemTablesAgeouts	5
#define LEAF_lldpStatsTxPortNum	1
#define MIN_lldpStatsTxPortNum	1L
#define MAX_lldpStatsTxPortNum	4096L
#define LEAF_lldpStatsTxPortFramesTotal	2
#define LEAF_lldpStatsRxPortNum	1
#define MIN_lldpStatsRxPortNum	1L
#define MAX_lldpStatsRxPortNum	4096L
#define LEAF_lldpStatsRxPortFramesDiscardedTotal	2
#define LEAF_lldpStatsRxPortFramesErrors	3
#define LEAF_lldpStatsRxPortFramesTotal	4
#define LEAF_lldpStatsRxPortTLVsDiscardedTotal	5
#define LEAF_lldpStatsRxPortTLVsUnrecognizedTotal	6
#define LEAF_lldpStatsRxPortAgeoutsTotal	7
#define LEAF_lldpLocChassisIdSubtype	1
#define VAL_lldpLocChassisIdSubtype_chassisComponent	1L
#define VAL_lldpLocChassisIdSubtype_interfaceAlias	2L
#define VAL_lldpLocChassisIdSubtype_portComponent	3L
#define VAL_lldpLocChassisIdSubtype_macAddress	4L
#define VAL_lldpLocChassisIdSubtype_networkAddress	5L
#define VAL_lldpLocChassisIdSubtype_interfaceName	6L
#define VAL_lldpLocChassisIdSubtype_local	7L
#define LEAF_lldpLocChassisId	2
#define MINSIZE_lldpLocChassisId	1L
#define MAXSIZE_lldpLocChassisId	255L
#define LEAF_lldpLocSysName	3
#define MINSIZE_lldpLocSysName	0L
#define MAXSIZE_lldpLocSysName	255L
#define LEAF_lldpLocSysDesc	4
#define MINSIZE_lldpLocSysDesc	0L
#define MAXSIZE_lldpLocSysDesc	255L
#define LEAF_lldpLocSysCapSupported	5
#define SIZE_lldpLocSysCapSupported 1L                    
#define VAL_lldpLocSysCapSupported_other 0L
#define VAL_lldpLocSysCapSupported_repeater 1L
#define VAL_lldpLocSysCapSupported_bridge 2L
#define VAL_lldpLocSysCapSupported_wlanAccessPoint 3L
#define VAL_lldpLocSysCapSupported_router 4L
#define VAL_lldpLocSysCapSupported_telephone 5L
#define VAL_lldpLocSysCapSupported_docsisCableDevice 6L
#define VAL_lldpLocSysCapSupported_stationOnly 7L
#define LEAF_lldpLocSysCapEnabled	6
#define SIZE_lldpLocSysCapEnabled 1L       
#define VAL_lldpLocSysCapEnabled_other	0L
#define VAL_lldpLocSysCapEnabled_repeater	1L
#define VAL_lldpLocSysCapEnabled_bridge	2L
#define VAL_lldpLocSysCapEnabled_wlanAccessPoint	3L
#define VAL_lldpLocSysCapEnabled_router	4L
#define VAL_lldpLocSysCapEnabled_telephone	5L
#define VAL_lldpLocSysCapEnabled_docsisCableDevice	6L
#define VAL_lldpLocSysCapEnabled_stationOnly	7L
#define LEAF_lldpLocPortNum	1
#define MIN_lldpLocPortNum	1L
#define MAX_lldpLocPortNum	4096L
#define LEAF_lldpLocPortIdSubtype	2
#define VAL_lldpLocPortIdSubtype_interfaceAlias	1L
#define VAL_lldpLocPortIdSubtype_portComponent	2L
#define VAL_lldpLocPortIdSubtype_macAddress	3L
#define VAL_lldpLocPortIdSubtype_networkAddress	4L
#define VAL_lldpLocPortIdSubtype_interfaceName	5L
#define VAL_lldpLocPortIdSubtype_agentCircuitId	6L
#define VAL_lldpLocPortIdSubtype_local	7L
#define LEAF_lldpLocPortId	3
#define MINSIZE_lldpLocPortId	1L
#define MAXSIZE_lldpLocPortId	255L
#define LEAF_lldpLocPortDesc	4
#define MINSIZE_lldpLocPortDesc	0L
#define MAXSIZE_lldpLocPortDesc	255L
#define LEAF_lldpLocManAddrSubtype	1
#define VAL_lldpLocManAddrSubtype_other	0L
#define VAL_lldpLocManAddrSubtype_ipV4	1L
#define VAL_lldpLocManAddrSubtype_ipV6	2L
#define VAL_lldpLocManAddrSubtype_nsap	3L
#define VAL_lldpLocManAddrSubtype_hdlc	4L
#define VAL_lldpLocManAddrSubtype_bbn1822	5L
#define VAL_lldpLocManAddrSubtype_all802	6L
#define VAL_lldpLocManAddrSubtype_e163	7L
#define VAL_lldpLocManAddrSubtype_e164	8L
#define VAL_lldpLocManAddrSubtype_f69	9L
#define VAL_lldpLocManAddrSubtype_x121	10L
#define VAL_lldpLocManAddrSubtype_ipx	11L
#define VAL_lldpLocManAddrSubtype_appleTalk	12L
#define VAL_lldpLocManAddrSubtype_decnetIV	13L
#define VAL_lldpLocManAddrSubtype_banyanVines	14L
#define VAL_lldpLocManAddrSubtype_e164withNsap	15L
#define VAL_lldpLocManAddrSubtype_dns	16L
#define VAL_lldpLocManAddrSubtype_distinguishedName	17L
#define VAL_lldpLocManAddrSubtype_asNumber	18L
#define VAL_lldpLocManAddrSubtype_xtpOverIpv4	19L
#define VAL_lldpLocManAddrSubtype_xtpOverIpv6	20L
#define VAL_lldpLocManAddrSubtype_xtpNativeModeXTP	21L
#define VAL_lldpLocManAddrSubtype_fibreChannelWWPN	22L
#define VAL_lldpLocManAddrSubtype_fibreChannelWWNN	23L
#define VAL_lldpLocManAddrSubtype_gwid	24L
#define VAL_lldpLocManAddrSubtype_reserved	65535L
#define LEAF_lldpLocManAddr	2
#define MINSIZE_lldpLocManAddr	1L
#define MAXSIZE_lldpLocManAddr	31L
#define LEAF_lldpLocManAddrLen	3
#define LEAF_lldpLocManAddrIfSubtype	4
#define VAL_lldpLocManAddrIfSubtype_unknown	1L
#define VAL_lldpLocManAddrIfSubtype_ifIndex	2L
#define VAL_lldpLocManAddrIfSubtype_systemPortNumber	3L
#define LEAF_lldpLocManAddrIfId	5
#define LEAF_lldpLocManAddrOID	6
#define MINSIZE_lldpLocManAddrOID  0                             
#define MAXSIZE_lldpLocManAddrOID  32      
#define LEAF_lldpRemTimeMark	1
#define LEAF_lldpRemLocalPortNum	2
#define MIN_lldpRemLocalPortNum	1L
#define MAX_lldpRemLocalPortNum	4096L
#define LEAF_lldpRemIndex	3
#define MIN_lldpRemIndex	1L
#define MAX_lldpRemIndex	2147483647L
#define LEAF_lldpRemChassisIdSubtype	4
#define VAL_lldpRemChassisIdSubtype_chassisComponent	1L
#define VAL_lldpRemChassisIdSubtype_interfaceAlias	2L
#define VAL_lldpRemChassisIdSubtype_portComponent	3L
#define VAL_lldpRemChassisIdSubtype_macAddress	4L
#define VAL_lldpRemChassisIdSubtype_networkAddress	5L
#define VAL_lldpRemChassisIdSubtype_interfaceName	6L
#define VAL_lldpRemChassisIdSubtype_local	7L
#define LEAF_lldpRemChassisId	5
#define MINSIZE_lldpRemChassisId	1L
#define MAXSIZE_lldpRemChassisId	255L
#define LEAF_lldpRemPortIdSubtype	6
#define VAL_lldpRemPortIdSubtype_interfaceAlias	1L
#define VAL_lldpRemPortIdSubtype_portComponent	2L
#define VAL_lldpRemPortIdSubtype_macAddress	3L
#define VAL_lldpRemPortIdSubtype_networkAddress	4L
#define VAL_lldpRemPortIdSubtype_interfaceName	5L
#define VAL_lldpRemPortIdSubtype_agentCircuitId	6L
#define VAL_lldpRemPortIdSubtype_local	7L
#define LEAF_lldpRemPortId	7
#define MINSIZE_lldpRemPortId	1L
#define MAXSIZE_lldpRemPortId	255L
#define LEAF_lldpRemPortDesc	8
#define MINSIZE_lldpRemPortDesc	0L
#define MAXSIZE_lldpRemPortDesc	255L
#define LEAF_lldpRemSysName	9
#define MINSIZE_lldpRemSysName	0L
#define MAXSIZE_lldpRemSysName	255L
#define LEAF_lldpRemSysDesc	10
#define MINSIZE_lldpRemSysDesc	0L
#define MAXSIZE_lldpRemSysDesc	255L
#define LEAF_lldpRemSysCapSupported	11
#define SIZE_lldpRemSysCapSupported 2L       
#define VAL_lldpRemSysCapSupported_other	0L
#define VAL_lldpRemSysCapSupported_repeater	1L
#define VAL_lldpRemSysCapSupported_bridge	2L
#define VAL_lldpRemSysCapSupported_wlanAccessPoint	3L
#define VAL_lldpRemSysCapSupported_router	4L
#define VAL_lldpRemSysCapSupported_telephone	5L
#define VAL_lldpRemSysCapSupported_docsisCableDevice	6L
#define VAL_lldpRemSysCapSupported_stationOnly	7L
#define LEAF_lldpRemSysCapEnabled	12
#define SIZE_lldpRemSysCapEnabled 2L    
#define VAL_lldpRemSysCapEnabled_other	0L
#define VAL_lldpRemSysCapEnabled_repeater	1L
#define VAL_lldpRemSysCapEnabled_bridge	2L
#define VAL_lldpRemSysCapEnabled_wlanAccessPoint	3L
#define VAL_lldpRemSysCapEnabled_router	4L
#define VAL_lldpRemSysCapEnabled_telephone	5L
#define VAL_lldpRemSysCapEnabled_docsisCableDevice	6L
#define VAL_lldpRemSysCapEnabled_stationOnly	7L
#define LEAF_lldpRemManAddrSubtype	1
#define VAL_lldpRemManAddrSubtype_other	0L
#define VAL_lldpRemManAddrSubtype_ipV4	1L
#define VAL_lldpRemManAddrSubtype_ipV6	2L
#define VAL_lldpRemManAddrSubtype_nsap	3L
#define VAL_lldpRemManAddrSubtype_hdlc	4L
#define VAL_lldpRemManAddrSubtype_bbn1822	5L
#define VAL_lldpRemManAddrSubtype_all802	6L
#define VAL_lldpRemManAddrSubtype_e163	7L
#define VAL_lldpRemManAddrSubtype_e164	8L
#define VAL_lldpRemManAddrSubtype_f69	9L
#define VAL_lldpRemManAddrSubtype_x121	10L
#define VAL_lldpRemManAddrSubtype_ipx	11L
#define VAL_lldpRemManAddrSubtype_appleTalk	12L
#define VAL_lldpRemManAddrSubtype_decnetIV	13L
#define VAL_lldpRemManAddrSubtype_banyanVines	14L
#define VAL_lldpRemManAddrSubtype_e164withNsap	15L
#define VAL_lldpRemManAddrSubtype_dns	16L
#define VAL_lldpRemManAddrSubtype_distinguishedName	17L
#define VAL_lldpRemManAddrSubtype_asNumber	18L
#define VAL_lldpRemManAddrSubtype_xtpOverIpv4	19L
#define VAL_lldpRemManAddrSubtype_xtpOverIpv6	20L
#define VAL_lldpRemManAddrSubtype_xtpNativeModeXTP	21L
#define VAL_lldpRemManAddrSubtype_fibreChannelWWPN	22L
#define VAL_lldpRemManAddrSubtype_fibreChannelWWNN	23L
#define VAL_lldpRemManAddrSubtype_gwid	24L
#define VAL_lldpRemManAddrSubtype_reserved	65535L
#define LEAF_lldpRemManAddr	2
#define MINSIZE_lldpRemManAddr	1L
#define MAXSIZE_lldpRemManAddr	31L
#define LEAF_lldpRemManAddrIfSubtype	3
#define VAL_lldpRemManAddrIfSubtype_unknown	1L
#define VAL_lldpRemManAddrIfSubtype_ifIndex	2L
#define VAL_lldpRemManAddrIfSubtype_systemPortNumber	3L
#define LEAF_lldpRemManAddrIfId	4
#define LEAF_lldpRemManAddrOID	5
#define MINSIZE_lldpRemManAddrOID  0                             
#define MAXSIZE_lldpRemManAddrOID  32        
#define LEAF_lldpRemUnknownTLVType	1
#define MIN_lldpRemUnknownTLVType	9L
#define MAX_lldpRemUnknownTLVType	126L
#define LEAF_lldpRemUnknownTLVInfo	2
#define MINSIZE_lldpRemUnknownTLVInfo	0L
#define MAXSIZE_lldpRemUnknownTLVInfo	511L
#define LEAF_lldpRemOrgDefInfoOUI	1
#define SIZE_lldpRemOrgDefInfoOUI	3L
#define LEAF_lldpRemOrgDefInfoSubtype	2
#define MIN_lldpRemOrgDefInfoSubtype	1L
#define MAX_lldpRemOrgDefInfoSubtype	255L
#define LEAF_lldpRemOrgDefInfoIndex	3
#define MIN_lldpRemOrgDefInfoIndex	1L
#define MAX_lldpRemOrgDefInfoIndex	2147483647L
#define LEAF_lldpRemOrgDefInfo	4
#define MINSIZE_lldpRemOrgDefInfo	0L
#define MAXSIZE_lldpRemOrgDefInfo	507L
