/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 18:26:14 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1447-SNMPv2-PARTY.mib, Rfc1450-SNMPv2.mib, rfc1450.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_1450_H
#define  LEAF_1450_H

#define LEAF_snmpStatsPackets	1
#define LEAF_snmpStats30Something	2
#define LEAF_snmpStatsEncodingErrors	3
#define LEAF_snmpStatsUnknownDstParties	4
#define LEAF_snmpStatsDstPartyMismatches	5
#define LEAF_snmpStatsUnknownSrcParties	6
#define LEAF_snmpStatsBadAuths	7
#define LEAF_snmpStatsNotInLifetimes	8
#define LEAF_snmpStatsWrongDigestValues	9
#define LEAF_snmpStatsUnknownContexts	10
#define LEAF_snmpStatsBadOperations	11
#define LEAF_snmpStatsSilentDrops	12
#define LEAF_snmpV1BadCommunityNames	1
#define LEAF_snmpV1BadCommunityUses	2
#define LEAF_snmpORLastChange	1
#define LEAF_snmpORIndex	1
#define LEAF_snmpORID	2
#define LEAF_snmpORDescr	3
#define MINSIZE_snmpORDescr	0L
#define MAXSIZE_snmpORDescr	255L
#define LEAF_snmpTrapOID	1
#define LEAF_snmpTrapNumbers	1
#define LEAF_snmpTrapEnterprise	3
#define LEAF_snmpV2EnableAuthenTraps	4
#define VAL_snmpV2EnableAuthenTraps_true	1L
#define VAL_snmpV2EnableAuthenTraps_false	2L
#define LEAF_snmpSetSerialNo	1
#define MIN_snmpSetSerialNo	0L
#define MAX_snmpSetSerialNo	2147483647L

#endif /* end of #ifndef  LEAF_1450_H */
