
#ifndef  LEAF_5060_H
#define  LEAF_5060_H

#define LEAF_pimInterfaceIfIndex   1
#define MIN_pimInterfaceIfIndex  1L
#define MAX_pimInterfaceIfIndex  2147483647L
#define LEAF_pimInterfaceIPVersion   2
#define VAL_pimInterfaceIPVersion_unknown 0L
#define VAL_pimInterfaceIPVersion_ipv4 1L
#define VAL_pimInterfaceIPVersion_ipv6 2L
#define LEAF_5060pimInterfaceAddressType   3
#define VAL_pimInterfaceAddressType_unknown 0L
#define VAL_pimInterfaceAddressType_ipv4 1L
#define VAL_pimInterfaceAddressType_ipv6 2L
#define VAL_pimInterfaceAddressType_ipv4z 3L
#define VAL_pimInterfaceAddressType_ipv6z 4L
#define VAL_pimInterfaceAddressType_dns 16L
#define LEAF_5060pimInterfaceAddress   4
#define SIZE_pimInterfaceAddress 20L
#define LEAF_pimInterfaceGenerationIDValue   5
#define LEAF_5060pimInterfaceDR   6
#define SIZE_pimInterfaceDR 20L
#define LEAF_5060pimInterfaceDRPriority   7
#define LEAF_5060pimInterfaceDRPriorityEnabled   8
#define VAL_pimInterfaceDRPriorityEnabled_true 1L
#define VAL_pimInterfaceDRPriorityEnabled_false 2L
#define LEAF_5060pimInterfaceHelloInterval   9
#define MIN_pimInterfaceHelloInterval  0L
#define MAX_pimInterfaceHelloInterval  18000L
#define LEAF_5060pimInterfaceTrigHelloInterval   10
#define MIN_5060pimInterfaceTrigHelloInterval  0L
#define MAX_5060pimInterfaceTrigHelloInterval  60L
#define LEAF_5060pimInterfaceHelloHoldtime   11
#define MIN_5060pimInterfaceHelloHoldtime  0L
#define MAX_5060pimInterfaceHelloHoldtime  65535L
#define LEAF_5060pimInterfaceJoinPruneInterval   12
#define MIN_pimInterfaceJoinPruneInterval  0L
#define MAX_pimInterfaceJoinPruneInterval  18000L
#define LEAF_pimInterfaceJoinPruneHoldtime   13
#define MIN_pimInterfaceJoinPruneHoldtime  0L
#define MAX_pimInterfaceJoinPruneHoldtime  65535L
#define LEAF_pimInterfaceDFElectionRobustness   14
#define LEAF_pimInterfaceLanDelayEnabled   15
#define VAL_pimInterfaceLanDelayEnabled_true 1L
#define VAL_pimInterfaceLanDelayEnabled_false 2L
#define LEAF_5060pimInterfacePropagationDelay   16
#define MIN_5060pimInterfacePropagationDelay  0L
#define MAX_5060pimInterfacePropagationDelay  32767L
#define LEAF_5060pimInterfaceOverrideInterval   17
#define MIN_5060pimInterfaceOverrideInterval  0L
#define MAX_5060pimInterfaceOverrideInterval  65535L
#define LEAF_pimInterfaceEffectPropagDelay   18
#define MIN_pimInterfaceEffectPropagDelay  0L
#define MAX_pimInterfaceEffectPropagDelay  32767L
#define LEAF_pimInterfaceEffectOverrideIvl   19
#define MIN_pimInterfaceEffectOverrideIvl  0L
#define MAX_pimInterfaceEffectOverrideIvl  65535L
#define LEAF_pimInterfaceSuppressionEnabled   20
#define VAL_pimInterfaceSuppressionEnabled_true 1L
#define VAL_pimInterfaceSuppressionEnabled_false 2L
#define LEAF_pimInterfaceBidirCapable   21
#define VAL_pimInterfaceBidirCapable_true 1L
#define VAL_pimInterfaceBidirCapable_false 2L
#define LEAF_pimInterfaceDomainBorder   22
#define VAL_pimInterfaceDomainBorder_true 1L
#define VAL_pimInterfaceDomainBorder_false 2L
#define LEAF_pimInterfaceStubInterface   23
#define VAL_pimInterfaceStubInterface_true 1L
#define VAL_pimInterfaceStubInterface_false 2L
#define LEAF_pimInterfacePruneLimitInterval   24
#define MIN_pimInterfacePruneLimitInterval  0L
#define MAX_pimInterfacePruneLimitInterval  65535L
#define LEAF_5060pimInterfaceGraftRetryInterval   25
#define MIN_pimInterfaceGraftRetryInterval  0L
#define MAX_pimInterfaceGraftRetryInterval  65535L
#define LEAF_pimInterfaceSRPriorityEnabled   26
#define VAL_pimInterfaceSRPriorityEnabled_true 1L
#define VAL_pimInterfaceSRPriorityEnabled_false 2L
#define LEAF_5060pimInterfaceStatus   27
#define VAL_pimInterfaceStatus_active 1L
#define VAL_pimInterfaceStatus_notInService 2L
#define VAL_pimInterfaceStatus_notReady 3L
#define VAL_pimInterfaceStatus_createAndGo 4L
#define VAL_pimInterfaceStatus_createAndWait 5L
#define VAL_pimInterfaceStatus_destroy 6L
#define LEAF_pimInterfaceStorageType   28
#define VAL_pimInterfaceStorageType_other 1L
#define VAL_pimInterfaceStorageType_volatile 2L
#define VAL_pimInterfaceStorageType_nonVolatile 3L
#define VAL_pimInterfaceStorageType_permanent 4L
#define VAL_pimInterfaceStorageType_readOnly 5L


#define LEAF_5060pimNeighborIfIndex   1
#define MIN_pimNeighborIfIndex  1L
#define MAX_pimNeighborIfIndex  2147483647L
#define LEAF_5060pimNeighborAddressType   2
#define VAL_pimNeighborAddressType_unknown 0L
#define VAL_pimNeighborAddressType_ipv4 1L
#define VAL_pimNeighborAddressType_ipv6 2L
#define VAL_pimNeighborAddressType_ipv4z 3L
#define VAL_pimNeighborAddressType_ipv6z 4L
#define VAL_pimNeighborAddressType_dns 16L
#define LEAF_5060pimNeighborAddress   3
#define SIZE_pimNeighborAddress 20L
#define LEAF_pimNeighborGenerationIDPresent   4
#define VAL_pimNeighborGenerationIDPresent_true 1L
#define VAL_pimNeighborGenerationIDPresent_false 2L
#define LEAF_pimNeighborGenerationIDValue   5
#define LEAF_5060pimNeighborUpTime   6
#define LEAF_5060pimNeighborExpiryTime   7
#define LEAF_pimNeighborDRPriorityPresent   8
#define VAL_pimNeighborDRPriorityPresent_true 1L
#define VAL_pimNeighborDRPriorityPresent_false 2L
#define LEAF_pimNeighborDRPriority   9
#define LEAF_pimNeighborLanPruneDelayPresent   10
#define VAL_pimNeighborLanPruneDelayPresent_true 1L
#define VAL_pimNeighborLanPruneDelayPresent_false 2L
#define LEAF_pimNeighborTBit   11
#define VAL_pimNeighborTBit_true 1L
#define VAL_pimNeighborTBit_false 2L
#define LEAF_pimNeighborPropagationDelay   12
#define MIN_pimNeighborPropagationDelay  0L
#define MAX_pimNeighborPropagationDelay  32767L
#define LEAF_pimNeighborOverrideInterval   13
#define MIN_pimNeighborOverrideInterval  0L
#define MAX_pimNeighborOverrideInterval  65535L
#define LEAF_pimNeighborBidirCapable   14
#define VAL_pimNeighborBidirCapable_true 1L
#define VAL_pimNeighborBidirCapable_false 2L
#define LEAF_pimNeighborSRCapable   15
#define VAL_pimNeighborSRCapable_true 1L
#define VAL_pimNeighborSRCapable_false 2L

#define LEAF_pimNbrSecAddressIfIndex   1
#define MIN_pimNbrSecAddressIfIndex  1L
#define MAX_pimNbrSecAddressIfIndex  2147483647L
#define LEAF_pimNbrSecAddressType   2
#define VAL_pimNbrSecAddressType_unknown 0L
#define VAL_pimNbrSecAddressType_ipv4 1L
#define VAL_pimNbrSecAddressType_ipv6 2L
#define VAL_pimNbrSecAddressType_ipv4z 3L
#define VAL_pimNbrSecAddressType_ipv6z 4L
#define VAL_pimNbrSecAddressType_dns 16L
#define LEAF_pimNbrSecAddressPrimary   3
#define SIZE_pimNbrSecAddressPrimary 20L
#define LEAF_pimNbrSecAddress   4
#define SIZE_pimNbrSecAddress 20L


#define LEAF_pimStarGAddressType   1
#define VAL_pimStarGAddressType_unknown 0L
#define VAL_pimStarGAddressType_ipv4 1L
#define VAL_pimStarGAddressType_ipv6 2L
#define VAL_pimStarGAddressType_ipv4z 3L
#define VAL_pimStarGAddressType_ipv6z 4L
#define VAL_pimStarGAddressType_dns 16L
#define LEAF_pimStarGGrpAddress   2
#define SIZE_pimStarGGrpAddress 20L
#define LEAF_pimStarGUpTime   3
#define LEAF_pimStarGPimMode   4
#define VAL_pimStarGPimMode_asm 3L
#define VAL_pimStarGPimMode_bidir 4L
#define LEAF_pimStarGRPAddressType   5
#define VAL_pimStarGRPAddressType_unknown 0L
#define VAL_pimStarGRPAddressType_ipv4 1L
#define VAL_pimStarGRPAddressType_ipv6 2L
#define VAL_pimStarGRPAddressType_ipv4z 3L
#define VAL_pimStarGRPAddressType_ipv6z 4L
#define VAL_pimStarGRPAddressType_dns 16L
#define LEAF_pimStarGRPAddress   6
#define SIZE_pimStarGRPAddress 20L
#define LEAF_pimStarGPimModeOrigin   7
#define VAL_pimStarGPimModeOrigin_fixed 1L
#define VAL_pimStarGPimModeOrigin_configRp 2L
#define VAL_pimStarGPimModeOrigin_configSsm 3L
#define VAL_pimStarGPimModeOrigin_bsr 4L
#define VAL_pimStarGPimModeOrigin_autoRP 5L
#define VAL_pimStarGPimModeOrigin_embedded 6L
#define VAL_pimStarGPimModeOrigin_other 7L
#define LEAF_pimStarGRPIsLocal   8
#define VAL_pimStarGRPIsLocal_true 1L
#define VAL_pimStarGRPIsLocal_false 2L
#define LEAF_pimStarGUpstreamJoinState   9
#define VAL_pimStarGUpstreamJoinState_notJoined 1L
#define VAL_pimStarGUpstreamJoinState_joined 2L
#define LEAF_pimStarGUpstreamJoinTimer   10
#define LEAF_pimStarGUpstreamNeighborType   11
#define VAL_pimStarGUpstreamNeighborType_unknown 0L
#define VAL_pimStarGUpstreamNeighborType_ipv4 1L
#define VAL_pimStarGUpstreamNeighborType_ipv6 2L
#define VAL_pimStarGUpstreamNeighborType_ipv4z 3L
#define VAL_pimStarGUpstreamNeighborType_ipv6z 4L
#define VAL_pimStarGUpstreamNeighborType_dns 16L
#define LEAF_pimStarGUpstreamNeighbor   12
#define SIZE_pimStarGUpstreamNeighbor 20L
#define LEAF_pimStarGRPFIfIndex   13
#define MIN_pimStarGRPFIfIndex  0L
#define MAX_pimStarGRPFIfIndex  2147483647L
#define LEAF_pimStarGRPFNextHopType   14
#define VAL_pimStarGRPFNextHopType_unknown 0L
#define VAL_pimStarGRPFNextHopType_ipv4 1L
#define VAL_pimStarGRPFNextHopType_ipv6 2L
#define VAL_pimStarGRPFNextHopType_ipv4z 3L
#define VAL_pimStarGRPFNextHopType_ipv6z 4L
#define VAL_pimStarGRPFNextHopType_dns 16L
#define LEAF_pimStarGRPFNextHop   15
#define SIZE_pimStarGRPFNextHop 20L
#define LEAF_pimStarGRPFRouteProtocol   16
#define VAL_pimStarGRPFRouteProtocol_other 1L
#define VAL_pimStarGRPFRouteProtocol_local 2L
#define VAL_pimStarGRPFRouteProtocol_netmgmt 3L
#define VAL_pimStarGRPFRouteProtocol_icmp 4L
#define VAL_pimStarGRPFRouteProtocol_egp 5L
#define VAL_pimStarGRPFRouteProtocol_ggp 6L
#define VAL_pimStarGRPFRouteProtocol_hello 7L
#define VAL_pimStarGRPFRouteProtocol_rip 8L
#define VAL_pimStarGRPFRouteProtocol_isIs 9L
#define VAL_pimStarGRPFRouteProtocol_esIs 10L
#define VAL_pimStarGRPFRouteProtocol_ciscoIgrp 11L
#define VAL_pimStarGRPFRouteProtocol_bbnSpfIgp 12L
#define VAL_pimStarGRPFRouteProtocol_ospf 13L
#define VAL_pimStarGRPFRouteProtocol_bgp 14L
#define VAL_pimStarGRPFRouteProtocol_idpr 15L
#define VAL_pimStarGRPFRouteProtocol_ciscoEigrp 16L
#define VAL_pimStarGRPFRouteProtocol_dvmrp 17L
#define LEAF_pimStarGRPFRouteAddress   17
#define SIZE_pimStarGRPFRouteAddress 20L
#define LEAF_pimStarGRPFRoutePrefixLength   18
#define MIN_pimStarGRPFRoutePrefixLength  0L
#define MAX_pimStarGRPFRoutePrefixLength  2040L
#define LEAF_pimStarGRPFRouteMetricPref   19
#define MIN_pimStarGRPFRouteMetricPref  0L
#define MAX_pimStarGRPFRouteMetricPref  2147483647L
#define LEAF_pimStarGRPFRouteMetric   20


#define LEAF_pimSGAddressType   1
#define VAL_pimSGAddressType_unknown 0L
#define VAL_pimSGAddressType_ipv4 1L
#define VAL_pimSGAddressType_ipv6 2L
#define VAL_pimSGAddressType_ipv4z 3L
#define VAL_pimSGAddressType_ipv6z 4L
#define VAL_pimSGAddressType_dns 16L
#define LEAF_pimSGGrpAddress   2
#define SIZE_pimSGGrpAddress 20L
#define LEAF_pimSGSrcAddress   3
#define SIZE_pimSGSrcAddress 20L
#define LEAF_pimSGUpTime   4
#define LEAF_pimSGPimMode   5
#define VAL_pimSGPimMode_ssm 2L
#define VAL_pimSGPimMode_asm 3L
#define LEAF_pimSGUpstreamJoinState   6
#define VAL_pimSGUpstreamJoinState_notJoined 1L
#define VAL_pimSGUpstreamJoinState_joined 2L
#define LEAF_pimSGUpstreamJoinTimer   7
#define LEAF_pimSGUpstreamNeighbor   8
#define SIZE_pimSGUpstreamNeighbor 20L
#define LEAF_pimSGRPFIfIndex   9
#define MIN_pimSGRPFIfIndex  0L
#define MAX_pimSGRPFIfIndex  2147483647L
#define LEAF_pimSGRPFNextHopType   10
#define VAL_pimSGRPFNextHopType_unknown 0L
#define VAL_pimSGRPFNextHopType_ipv4 1L
#define VAL_pimSGRPFNextHopType_ipv6 2L
#define VAL_pimSGRPFNextHopType_ipv4z 3L
#define VAL_pimSGRPFNextHopType_ipv6z 4L
#define VAL_pimSGRPFNextHopType_dns 16L
#define LEAF_pimSGRPFNextHop   11
#define SIZE_pimSGRPFNextHop 20L
#define LEAF_pimSGRPFRouteProtocol   12
#define VAL_pimSGRPFRouteProtocol_other 1L
#define VAL_pimSGRPFRouteProtocol_local 2L
#define VAL_pimSGRPFRouteProtocol_netmgmt 3L
#define VAL_pimSGRPFRouteProtocol_icmp 4L
#define VAL_pimSGRPFRouteProtocol_egp 5L
#define VAL_pimSGRPFRouteProtocol_ggp 6L
#define VAL_pimSGRPFRouteProtocol_hello 7L
#define VAL_pimSGRPFRouteProtocol_rip 8L
#define VAL_pimSGRPFRouteProtocol_isIs 9L
#define VAL_pimSGRPFRouteProtocol_esIs 10L
#define VAL_pimSGRPFRouteProtocol_ciscoIgrp 11L
#define VAL_pimSGRPFRouteProtocol_bbnSpfIgp 12L
#define VAL_pimSGRPFRouteProtocol_ospf 13L
#define VAL_pimSGRPFRouteProtocol_bgp 14L
#define VAL_pimSGRPFRouteProtocol_idpr 15L
#define VAL_pimSGRPFRouteProtocol_ciscoEigrp 16L
#define VAL_pimSGRPFRouteProtocol_dvmrp 17L
#define LEAF_pimSGRPFRouteAddress   13
#define SIZE_pimSGRPFRouteAddress 20L
#define LEAF_pimSGRPFRoutePrefixLength   14
#define MIN_pimSGRPFRoutePrefixLength  0L
#define MAX_pimSGRPFRoutePrefixLength  2040L
#define LEAF_pimSGRPFRouteMetricPref   15
#define MIN_pimSGRPFRouteMetricPref  0L
#define MAX_pimSGRPFRouteMetricPref  2147483647L
#define LEAF_pimSGRPFRouteMetric   16
#define LEAF_pimSGSPTBit   17
#define VAL_pimSGSPTBit_true 1L
#define VAL_pimSGSPTBit_false 2L
#define LEAF_pimSGKeepaliveTimer   18
#define LEAF_pimSGDRRegisterState   19
#define VAL_pimSGDRRegisterState_noInfo 1L
#define VAL_pimSGDRRegisterState_join 2L
#define VAL_pimSGDRRegisterState_joinPending 3L
#define VAL_pimSGDRRegisterState_prune 4L
#define LEAF_pimSGDRRegisterStopTimer   20
#define LEAF_pimSGRPRegisterPMBRAddressType   21
#define VAL_pimSGRPRegisterPMBRAddressType_unknown 0L
#define VAL_pimSGRPRegisterPMBRAddressType_ipv4 1L
#define VAL_pimSGRPRegisterPMBRAddressType_ipv6 2L
#define VAL_pimSGRPRegisterPMBRAddressType_ipv4z 3L
#define VAL_pimSGRPRegisterPMBRAddressType_ipv6z 4L
#define VAL_pimSGRPRegisterPMBRAddressType_dns 16L
#define LEAF_pimSGRPRegisterPMBRAddress   22
#define SIZE_pimSGRPRegisterPMBRAddress 20L
#define LEAF_pimSGUpstreamPruneState   23
#define VAL_pimSGUpstreamPruneState_forwarding 1L
#define VAL_pimSGUpstreamPruneState_ackpending 2L
#define VAL_pimSGUpstreamPruneState_pruned 3L
#define LEAF_pimSGUpstreamPruneLimitTimer   24
#define LEAF_pimSGOriginatorState   25
#define VAL_pimSGOriginatorState_notOriginator 1L
#define VAL_pimSGOriginatorState_originator 2L
#define LEAF_pimSGSourceActiveTimer   26
#define LEAF_pimSGStateRefreshTimer   27


#define LEAF_pimStarGIIfIndex   1
#define MIN_pimStarGIIfIndex  1L
#define MAX_pimStarGIIfIndex  2147483647L
#define LEAF_pimStarGIUpTime   2
#define LEAF_pimStarGILocalMembership   3
#define VAL_pimStarGILocalMembership_true 1L
#define VAL_pimStarGILocalMembership_false 2L
#define LEAF_pimStarGIJoinPruneState   4
#define VAL_pimStarGIJoinPruneState_noInfo 1L
#define VAL_pimStarGIJoinPruneState_join 2L
#define VAL_pimStarGIJoinPruneState_prunePending 3L
#define LEAF_pimStarGIPrunePendingTimer   5
#define LEAF_pimStarGIJoinExpiryTimer   6
#define LEAF_pimStarGIAssertState   7
#define VAL_pimStarGIAssertState_noInfo 1L
#define VAL_pimStarGIAssertState_iAmAssertWinner 2L
#define VAL_pimStarGIAssertState_iAmAssertLoser 3L
#define LEAF_pimStarGIAssertTimer   8
#define LEAF_pimStarGIAssertWinnerAddressType   9
#define VAL_pimStarGIAssertWinnerAddressType_unknown 0L
#define VAL_pimStarGIAssertWinnerAddressType_ipv4 1L
#define VAL_pimStarGIAssertWinnerAddressType_ipv6 2L
#define VAL_pimStarGIAssertWinnerAddressType_ipv4z 3L
#define VAL_pimStarGIAssertWinnerAddressType_ipv6z 4L
#define VAL_pimStarGIAssertWinnerAddressType_dns 16L
#define LEAF_pimStarGIAssertWinnerAddress   10
#define SIZE_pimStarGIAssertWinnerAddress 20L
#define LEAF_pimStarGIAssertWinnerMetricPref   11
#define MIN_pimStarGIAssertWinnerMetricPref  0L
#define MAX_pimStarGIAssertWinnerMetricPref  2147483647L
#define LEAF_pimStarGIAssertWinnerMetric   12

#define LEAF_pimSGIIfIndex   1
#define MIN_pimSGIIfIndex  1L
#define MAX_pimSGIIfIndex  2147483647L
#define LEAF_pimSGIUpTime   2
#define LEAF_pimSGILocalMembership   3
#define VAL_pimSGILocalMembership_true 1L
#define VAL_pimSGILocalMembership_false 2L
#define LEAF_pimSGIJoinPruneState   4
#define VAL_pimSGIJoinPruneState_noInfo 1L
#define VAL_pimSGIJoinPruneState_join 2L
#define VAL_pimSGIJoinPruneState_prunePending 3L
#define LEAF_pimSGIPrunePendingTimer   5
#define LEAF_pimSGIJoinExpiryTimer   6
#define LEAF_pimSGIAssertState   7
#define VAL_pimSGIAssertState_noInfo 1L
#define VAL_pimSGIAssertState_iAmAssertWinner 2L
#define VAL_pimSGIAssertState_iAmAssertLoser 3L
#define LEAF_pimSGIAssertTimer   8
#define LEAF_pimSGIAssertWinnerAddressType   9
#define VAL_pimSGIAssertWinnerAddressType_unknown 0L
#define VAL_pimSGIAssertWinnerAddressType_ipv4 1L
#define VAL_pimSGIAssertWinnerAddressType_ipv6 2L
#define VAL_pimSGIAssertWinnerAddressType_ipv4z 3L
#define VAL_pimSGIAssertWinnerAddressType_ipv6z 4L
#define VAL_pimSGIAssertWinnerAddressType_dns 16L
#define LEAF_pimSGIAssertWinnerAddress   10
#define SIZE_pimSGIAssertWinnerAddress 20L
#define LEAF_pimSGIAssertWinnerMetricPref   11
#define MIN_pimSGIAssertWinnerMetricPref  0L
#define MAX_pimSGIAssertWinnerMetricPref  2147483647L
#define LEAF_pimSGIAssertWinnerMetric   12


#define LEAF_pimStaticRPAddressType   1
#define VAL_pimStaticRPAddressType_unknown 0L
#define VAL_pimStaticRPAddressType_ipv4 1L
#define VAL_pimStaticRPAddressType_ipv6 2L
#define VAL_pimStaticRPAddressType_ipv4z 3L
#define VAL_pimStaticRPAddressType_ipv6z 4L
#define VAL_pimStaticRPAddressType_dns 16L
#define LEAF_pimStaticRPGrpAddress   2
#define SIZE_pimStaticRPGrpAddress 20L
#define LEAF_pimStaticRPGrpPrefixLength   3
#define MIN_pimStaticRPGrpPrefixLength  4L
#define MAX_pimStaticRPGrpPrefixLength  128L
#define LEAF_pimStaticRPRPAddress   4
#define SIZE_pimStaticRPRPAddress 20L
#define LEAF_pimStaticRPPimMode   5
#define VAL_pimStaticRPPimMode_ssm 2L
#define VAL_pimStaticRPPimMode_asm 3L
#define VAL_pimStaticRPPimMode_bidir 4L
#define LEAF_pimStaticRPOverrideDynamic   6
#define VAL_pimStaticRPOverrideDynamic_true 1L
#define VAL_pimStaticRPOverrideDynamic_false 2L
#define LEAF_pimStaticRPPrecedence   7
#define LEAF_pimStaticRPRowStatus   8
#define VAL_pimStaticRPRowStatus_active 1L
#define VAL_pimStaticRPRowStatus_notInService 2L
#define VAL_pimStaticRPRowStatus_notReady 3L
#define VAL_pimStaticRPRowStatus_createAndGo 4L
#define VAL_pimStaticRPRowStatus_createAndWait 5L
#define VAL_pimStaticRPRowStatus_destroy 6L
#define LEAF_pimStaticRPStorageType   9
#define VAL_pimStaticRPStorageType_other 1L
#define VAL_pimStaticRPStorageType_volatile 2L
#define VAL_pimStaticRPStorageType_nonVolatile 3L
#define VAL_pimStaticRPStorageType_permanent 4L
#define VAL_pimStaticRPStorageType_readOnly 5L


#define LEAF_pimSGRptSrcAddress   1
#define SIZE_pimSGRptSrcAddress 20L
#define LEAF_pimSGRptUpTime   2
#define LEAF_pimSGRptUpstreamPruneState   3
#define VAL_pimSGRptUpstreamPruneState_rptNotJoined 1L
#define VAL_pimSGRptUpstreamPruneState_pruned 2L
#define VAL_pimSGRptUpstreamPruneState_notPruned 3L
#define LEAF_pimSGRptUpstreamOverrideTimer   4



#define LEAF_pimSGRptIIfIndex   1
#define MIN_pimSGRptIIfIndex  1L
#define MAX_pimSGRptIIfIndex  2147483647L
#define LEAF_pimSGRptIUpTime   2
#define LEAF_pimSGRptILocalMembership   3
#define VAL_pimSGRptILocalMembership_true 1L
#define VAL_pimSGRptILocalMembership_false 2L
#define LEAF_pimSGRptIJoinPruneState   4
#define VAL_pimSGRptIJoinPruneState_noInfo 1L
#define VAL_pimSGRptIJoinPruneState_prune 2L
#define VAL_pimSGRptIJoinPruneState_prunePending 3L
#define LEAF_pimSGRptIPrunePendingTimer   5
#define LEAF_pimSGRptIPruneExpiryTimer   6


#define LEAF_pimGroupMappingOrigin   1
#define VAL_pimGroupMappingOrigin_fixed 1L
#define VAL_pimGroupMappingOrigin_configRp 2L
#define VAL_pimGroupMappingOrigin_configSsm 3L
#define VAL_pimGroupMappingOrigin_bsr 4L
#define VAL_pimGroupMappingOrigin_autoRP 5L
#define VAL_pimGroupMappingOrigin_embedded 6L
#define VAL_pimGroupMappingOrigin_other 7L
#define LEAF_pimGroupMappingAddressType   2
#define VAL_pimGroupMappingAddressType_unknown 0L
#define VAL_pimGroupMappingAddressType_ipv4 1L
#define VAL_pimGroupMappingAddressType_ipv6 2L
#define VAL_pimGroupMappingAddressType_ipv4z 3L
#define VAL_pimGroupMappingAddressType_ipv6z 4L
#define VAL_pimGroupMappingAddressType_dns 16L
#define LEAF_pimGroupMappingGrpAddress   3
#define SIZE_pimGroupMappingGrpAddress 20L
#define LEAF_pimGroupMappingGrpPrefixLength   4
#define MIN_pimGroupMappingGrpPrefixLength  4L
#define MAX_pimGroupMappingGrpPrefixLength  128L
#define LEAF_pimGroupMappingRPAddressType   5
#define VAL_pimGroupMappingRPAddressType_unknown 0L
#define VAL_pimGroupMappingRPAddressType_ipv4 1L
#define VAL_pimGroupMappingRPAddressType_ipv6 2L
#define VAL_pimGroupMappingRPAddressType_ipv4z 3L
#define VAL_pimGroupMappingRPAddressType_ipv6z 4L
#define VAL_pimGroupMappingRPAddressType_dns 16L
#define LEAF_pimGroupMappingRPAddress   6
#define SIZE_pimGroupMappingRPAddress 20L
#define LEAF_pimGroupMappingPimMode   7
#define VAL_pimGroupMappingPimMode_none 1L
#define VAL_pimGroupMappingPimMode_ssm 2L
#define VAL_pimGroupMappingPimMode_asm 3L
#define VAL_pimGroupMappingPimMode_bidir 4L
#define VAL_pimGroupMappingPimMode_dm 5L
#define VAL_pimGroupMappingPimMode_other 6L
#define LEAF_pimGroupMappingPrecedence   8


#endif

