/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 18:31:36 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1493-BRIDGE.mib, rfc1493.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_1493_H
#define  LEAF_1493_H

#define LEAF_dot1dBaseBridgeAddress	1
#define SIZE_dot1dBaseBridgeAddress	6L
#define LEAF_dot1dBaseNumPorts	2
#define LEAF_dot1dBaseType	3
#define VAL_dot1dBaseType_unknown	1L
#define VAL_dot1dBaseType_transparent_only	2L
#define VAL_dot1dBaseType_sourceroute_only	3L
#define VAL_dot1dBaseType_srt	4L
#define LEAF_dot1dBasePort	1
#define MIN_dot1dBasePort	1L
#define MAX_dot1dBasePort	65535L
#define LEAF_dot1dBasePortIfIndex	2
#define LEAF_dot1dBasePortCircuit	3
#define LEAF_dot1dBasePortDelayExceededDiscards	4
#define LEAF_dot1dBasePortMtuExceededDiscards	5
#define LEAF_dot1dStpProtocolSpecification	1
#define VAL_dot1dStpProtocolSpecification_unknown	1L
#define VAL_dot1dStpProtocolSpecification_decLb100	2L
#define VAL_dot1dStpProtocolSpecification_ieee8021d	3L
#define LEAF_dot1dStpPriority	2
#define MIN_dot1dStpPriority	0L
#define MAX_dot1dStpPriority	65535L
#define LEAF_dot1dStpTimeSinceTopologyChange	3
#define LEAF_dot1dStpTopChanges	4
#define LEAF_dot1dStpDesignatedRoot	5
#define SIZE_dot1dStpDesignatedRoot	8L
#define LEAF_dot1dStpRootCost	6
#define LEAF_dot1dStpRootPort	7
#define LEAF_dot1dStpMaxAge	8
#define LEAF_dot1dStpHelloTime	9
#define LEAF_dot1dStpHoldTime	10
#define LEAF_dot1dStpForwardDelay	11
#define LEAF_dot1dStpBridgeMaxAge	12
#define MIN_dot1dStpBridgeMaxAge	600L
#define MAX_dot1dStpBridgeMaxAge	4000L
#define LEAF_dot1dStpBridgeHelloTime	13
#define MIN_dot1dStpBridgeHelloTime	100L
#define MAX_dot1dStpBridgeHelloTime	1000L
#define LEAF_dot1dStpBridgeForwardDelay	14
#define MIN_dot1dStpBridgeForwardDelay	400L
#define MAX_dot1dStpBridgeForwardDelay	3000L
#define LEAF_dot1dStpPort	1
#define MIN_dot1dStpPort	1L
#define MAX_dot1dStpPort	65535L
#define LEAF_dot1dStpPortPriority	2
#define MIN_dot1dStpPortPriority	0L
#define MAX_dot1dStpPortPriority	255L
#define LEAF_dot1dStpPortState	3
#define VAL_dot1dStpPortState_disabled	1L
#define VAL_dot1dStpPortState_blocking	2L
#define VAL_dot1dStpPortState_listening	3L
#define VAL_dot1dStpPortState_learning	4L
#define VAL_dot1dStpPortState_forwarding	5L
#define VAL_dot1dStpPortState_broken	6L
#define LEAF_dot1dStpPortEnable	4
#define VAL_dot1dStpPortEnable_enabled	1L
#define VAL_dot1dStpPortEnable_disabled	2L
#define LEAF_dot1dStpPortPathCost	5
#define MIN_dot1dStpPortPathCost	1L
#define MAX_dot1dStpPortPathCost	65535L
#define LEAF_dot1dStpPortDesignatedRoot	6
#define SIZE_dot1dStpPortDesignatedRoot	8L
#define LEAF_dot1dStpPortDesignatedCost	7
#define LEAF_dot1dStpPortDesignatedBridge	8
#define SIZE_dot1dStpPortDesignatedBridge	8L
#define LEAF_dot1dStpPortDesignatedPort	9
#define SIZE_dot1dStpPortDesignatedPort	2L
#define LEAF_dot1dStpPortForwardTransitions	10
#define LEAF_dot1dTpLearnedEntryDiscards	1
#define LEAF_dot1dTpAgingTime	2
#define MIN_dot1dTpAgingTime	10L
#define MAX_dot1dTpAgingTime	1000000L
#define LEAF_dot1dTpFdbAddress	1
#define SIZE_dot1dTpFdbAddress	6L
#define LEAF_dot1dTpFdbPort	2
#define LEAF_dot1dTpFdbStatus	3
#define VAL_dot1dTpFdbStatus_other	1L
#define VAL_dot1dTpFdbStatus_invalid	2L
#define VAL_dot1dTpFdbStatus_learned	3L
#define VAL_dot1dTpFdbStatus_self	4L
#define VAL_dot1dTpFdbStatus_mgmt	5L
#define LEAF_dot1dTpPort	1
#define MIN_dot1dTpPort	1L
#define MAX_dot1dTpPort	65535L
#define LEAF_dot1dTpPortMaxInfo	2
#define LEAF_dot1dTpPortInFrames	3
#define LEAF_dot1dTpPortOutFrames	4
#define LEAF_dot1dTpPortInDiscards	5
#define LEAF_dot1dStaticAddress	1
#define SIZE_dot1dStaticAddress	6L
#define LEAF_dot1dStaticReceivePort	2
#define LEAF_dot1dStaticAllowedToGoTo	3
#define LEAF_dot1dStaticStatus	4
#define VAL_dot1dStaticStatus_other	1L
#define VAL_dot1dStaticStatus_invalid	2L
#define VAL_dot1dStaticStatus_permanent	3L
#define VAL_dot1dStaticStatus_deleteOnReset	4L
#define VAL_dot1dStaticStatus_deleteOnTimeout	5L

#endif /* end of #ifndef  LEAF_1493_H */
