/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 ****
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 ****
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 ****
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 ****
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 ****
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 ****
 **** DO NOT MODIFY THIS FILE BY HAND.
 ****
 **** Last build date: Thu May 31 15:03:09 2007
 **** from files:
 ****  ..\MibFiles\Rfc1213.mib, ctl\Rfc1213.ctl,
 ****  ..\MibFiles\IanaIfType_Rfc1573.mib, ..\MibFiles\SnmpV2_Rfc1907.mib,
 ****  ctl\SnmpV2_Rfc1907.ctl, ..\MibFiles\If_Rfc2863.mib, ctl\If_Rfc2863.ctl,
 ****  ..\MibFiles\Rmon_Rfc2819.mib, ctl\Rmon_Rfc2819.ctl,
 ****  ..\MibFiles\TokenRingRmon_Rfc1513.mib, ctl\TokenRingRmon_Rfc1513.ctl,
 ****  ..\MibFiles\Rmon2_Rfc2021.mib, ctl\Rmon2_Rfc2021.ctl,
 ****  ..\MibFiles\Bridge_Rfc1493.mib, ctl\Bridge_Rfc1493.ctl,
 ****  ..\MibFiles\PBridge_Rfc2674.mib, ctl\PBridge_Rfc2674.ctl,
 ****  ..\MibFiles\SnmpFramework_Rfc2271.mib, ctl\SnmpFramework_Rfc2271.ctl,
 ****  ..\MibFiles\Vrrp_Rfc2787.mib, ctl\Vrrp_Rfc2787.ctl,
 ****  ..\MibFiles\HcnumTc.mib, ..\MibFiles\Ip_Rfc2011.mib,
 ****  ..\MibFiles\InetAddress_Rfc3291.mib,
 ****  ..\MibFiles\IntegratedServices_Rfc2213.mib,
 ****  ..\MibFiles\DiffServDscpTc_Rfc3289.mib,
 ****  ..\MibFiles\DiffServ_Rfc3289.mib, ..\MibFiles\Ieee8021Pae.mib,
 ****  ctl\Ieee8021Pae.ctl, ..\MibFiles\IANA-ADDRESS-FAMILY-NUMBERS-MIB.mib,
 ****  ..\MibFiles\Q-BRIDGE-MIB.mib, ..\MibFiles\lldp.mib,
 ****  ..\MibFiles\TRANSPORT-ADDRESS-MIB.mib, ..\MibFiles\LLDP-EXT-MED-MIB.mib
 ******************************************************************************
 ******************************************************************************
 */

#define LEAF_lldpXMedLocDeviceClass	1
#define VAL_lldpXMedLocDeviceClass_notDefined	0L
#define VAL_lldpXMedLocDeviceClass_endpointClass1	1L
#define VAL_lldpXMedLocDeviceClass_endpointClass2	2L
#define VAL_lldpXMedLocDeviceClass_endpointClass3	3L
#define VAL_lldpXMedLocDeviceClass_networkConnectivity	4L
#define LEAF_lldpXMedPortCapSupported	1
#define SIZE_lldpXMedPortCapSupported   2L
#define VAL_lldpXMedPortCapSupported_capabilities	0L
#define VAL_lldpXMedPortCapSupported_networkPolicy	1L
#define VAL_lldpXMedPortCapSupported_location	2L
#define VAL_lldpXMedPortCapSupported_extendedPSE	3L
#define VAL_lldpXMedPortCapSupported_extendedPD	4L
#define VAL_lldpXMedPortCapSupported_inventory	5L
#define LEAF_lldpXMedPortConfigTLVsTxEnable	2
#define SIZE_lldpXMedPortConfigTLVsTxEnable 2L
#define VAL_lldpXMedPortConfigTLVsTxEnable_capabilities	0L
#define VAL_lldpXMedPortConfigTLVsTxEnable_networkPolicy	1L
#define VAL_lldpXMedPortConfigTLVsTxEnable_location	2L
#define VAL_lldpXMedPortConfigTLVsTxEnable_extendedPSE	3L
#define VAL_lldpXMedPortConfigTLVsTxEnable_extendedPD	4L
#define VAL_lldpXMedPortConfigTLVsTxEnable_inventory	5L
#define LEAF_lldpXMedPortConfigNotifEnable	3
#define VAL_lldpXMedPortConfigNotifEnable_true	1L
#define VAL_lldpXMedPortConfigNotifEnable_false	2L
#define LEAF_lldpXMedFastStartRepeatCount	3
#define MIN_lldpXMedFastStartRepeatCount	1L
#define MAX_lldpXMedFastStartRepeatCount	10L
#define LEAF_lldpXMedLocMediaPolicyAppType	1
#define SIZE_lldpXMedLocMediaPolicyAppType  1L
#define VAL_lldpXMedLocMediaPolicyAppType_unknown	0L
#define VAL_lldpXMedLocMediaPolicyAppType_voice	1L
#define VAL_lldpXMedLocMediaPolicyAppType_voiceSignaling	2L
#define VAL_lldpXMedLocMediaPolicyAppType_guestVoice	3L
#define VAL_lldpXMedLocMediaPolicyAppType_guestVoiceSignaling	4L
#define VAL_lldpXMedLocMediaPolicyAppType_softPhoneVoice	5L
#define VAL_lldpXMedLocMediaPolicyAppType_videoconferencing	6L
#define VAL_lldpXMedLocMediaPolicyAppType_streamingVideo	7L
#define VAL_lldpXMedLocMediaPolicyAppType_videoSignaling	8L
#define LEAF_lldpXMedLocMediaPolicyVlanID	2
#define MIN_lldpXMedLocMediaPolicyVlanID	0L
#define MAX_lldpXMedLocMediaPolicyVlanID	4095L
#define LEAF_lldpXMedLocMediaPolicyPriority	3
#define MIN_lldpXMedLocMediaPolicyPriority	0L
#define MAX_lldpXMedLocMediaPolicyPriority	7L
#define LEAF_lldpXMedLocMediaPolicyDscp	4
#define MIN_lldpXMedLocMediaPolicyDscp	0L
#define MAX_lldpXMedLocMediaPolicyDscp	63L
#define LEAF_lldpXMedLocMediaPolicyUnknown	5
#define VAL_lldpXMedLocMediaPolicyUnknown_true	1L
#define VAL_lldpXMedLocMediaPolicyUnknown_false	2L
#define LEAF_lldpXMedLocMediaPolicyTagged	6
#define VAL_lldpXMedLocMediaPolicyTagged_true	1L
#define VAL_lldpXMedLocMediaPolicyTagged_false	2L
#define LEAF_lldpXMedLocHardwareRev	2
#define MINSIZE_lldpXMedLocHardwareRev	0L
#define MAXSIZE_lldpXMedLocHardwareRev	32L
#define LEAF_lldpXMedLocFirmwareRev	3
#define MINSIZE_lldpXMedLocFirmwareRev	0L
#define MAXSIZE_lldpXMedLocFirmwareRev	32L
#define LEAF_lldpXMedLocSoftwareRev	4
#define MINSIZE_lldpXMedLocSoftwareRev	0L
#define MAXSIZE_lldpXMedLocSoftwareRev	32L
#define LEAF_lldpXMedLocSerialNum	5
#define MINSIZE_lldpXMedLocSerialNum	0L
#define MAXSIZE_lldpXMedLocSerialNum	32L
#define LEAF_lldpXMedLocMfgName	6
#define MINSIZE_lldpXMedLocMfgName	0L
#define MAXSIZE_lldpXMedLocMfgName	32L
#define LEAF_lldpXMedLocModelName	7
#define MINSIZE_lldpXMedLocModelName	0L
#define MAXSIZE_lldpXMedLocModelName	32L
#define LEAF_lldpXMedLocAssetID	8
#define MINSIZE_lldpXMedLocAssetID	0L
#define MAXSIZE_lldpXMedLocAssetID	32L
#define LEAF_lldpXMedLocLocationSubtype	1
#define VAL_lldpXMedLocLocationSubtype_unknown	1L
#define VAL_lldpXMedLocLocationSubtype_coordinateBased	2L
#define VAL_lldpXMedLocLocationSubtype_civicAddress	3L
#define VAL_lldpXMedLocLocationSubtype_elin	4L
#define LEAF_lldpXMedLocLocationInfo	2
#define MINSIZE_lldpXMedLocLocationInfo	0L
#define MAXSIZE_lldpXMedLocLocationInfo	256L
#define LEAF_lldpXMedLocXPoEDeviceType	10
#define VAL_lldpXMedLocXPoEDeviceType_unknown	1L
#define VAL_lldpXMedLocXPoEDeviceType_pseDevice	2L
#define VAL_lldpXMedLocXPoEDeviceType_pdDevice	3L
#define VAL_lldpXMedLocXPoEDeviceType_none	4L
#define LEAF_lldpXMedLocXPoEPSEPortPowerAv	1
#define MIN_lldpXMedLocXPoEPSEPortPowerAv	0L
#define MAX_lldpXMedLocXPoEPSEPortPowerAv	1023L
#define LEAF_lldpXMedLocXPoEPSEPortPDPriority	2
#define VAL_lldpXMedLocXPoEPSEPortPDPriority_unknown	1L
#define VAL_lldpXMedLocXPoEPSEPortPDPriority_critical	2L
#define VAL_lldpXMedLocXPoEPSEPortPDPriority_high	3L
#define VAL_lldpXMedLocXPoEPSEPortPDPriority_low	4L
#define LEAF_lldpXMedLocXPoEPSEPowerSource	12
#define VAL_lldpXMedLocXPoEPSEPowerSource_unknown	1L
#define VAL_lldpXMedLocXPoEPSEPowerSource_primary	2L
#define VAL_lldpXMedLocXPoEPSEPowerSource_backup	3L
#define LEAF_lldpXMedLocXPoEPDPowerReq	13
#define MIN_lldpXMedLocXPoEPDPowerReq	0L
#define MAX_lldpXMedLocXPoEPDPowerReq	1023L
#define LEAF_lldpXMedLocXPoEPDPowerSource	14
#define VAL_lldpXMedLocXPoEPDPowerSource_unknown	1L
#define VAL_lldpXMedLocXPoEPDPowerSource_fromPSE	2L
#define VAL_lldpXMedLocXPoEPDPowerSource_local	3L
#define VAL_lldpXMedLocXPoEPDPowerSource_localAndPSE	4L
#define LEAF_lldpXMedLocXPoEPDPowerPriority	15
#define VAL_lldpXMedLocXPoEPDPowerPriority_unknown	1L
#define VAL_lldpXMedLocXPoEPDPowerPriority_critical	2L
#define VAL_lldpXMedLocXPoEPDPowerPriority_high	3L
#define VAL_lldpXMedLocXPoEPDPowerPriority_low	4L
#define LEAF_lldpXMedRemCapSupported	1
#define SIZE_lldpXMedRemCapSupported    2L
#define VAL_lldpXMedRemCapSupported_capabilities	0L
#define VAL_lldpXMedRemCapSupported_networkPolicy	1L
#define VAL_lldpXMedRemCapSupported_location	2L
#define VAL_lldpXMedRemCapSupported_extendedPSE	3L
#define VAL_lldpXMedRemCapSupported_extendedPD	4L
#define VAL_lldpXMedRemCapSupported_inventory	5L
#define LEAF_lldpXMedRemCapCurrent	2
#define SIZE_lldpXMedRemCapCurrent  2L
#define VAL_lldpXMedRemCapCurrent_capabilities	0L
#define VAL_lldpXMedRemCapCurrent_networkPolicy	1L
#define VAL_lldpXMedRemCapCurrent_location	2L
#define VAL_lldpXMedRemCapCurrent_extendedPSE	3L
#define VAL_lldpXMedRemCapCurrent_extendedPD	4L
#define VAL_lldpXMedRemCapCurrent_inventory	5L
#define LEAF_lldpXMedRemDeviceClass	3
#define VAL_lldpXMedRemDeviceClass_notDefined	0L
#define VAL_lldpXMedRemDeviceClass_endpointClass1	1L
#define VAL_lldpXMedRemDeviceClass_endpointClass2	2L
#define VAL_lldpXMedRemDeviceClass_endpointClass3	3L
#define VAL_lldpXMedRemDeviceClass_networkConnectivity	4L
#define LEAF_lldpXMedRemMediaPolicyAppType	1
#define SIZE_lldpXMedRemMediaPolicyAppType  1L
#define VAL_lldpXMedRemMediaPolicyAppType_unknown	0L
#define VAL_lldpXMedRemMediaPolicyAppType_voice	1L
#define VAL_lldpXMedRemMediaPolicyAppType_voiceSignaling	2L
#define VAL_lldpXMedRemMediaPolicyAppType_guestVoice	3L
#define VAL_lldpXMedRemMediaPolicyAppType_guestVoiceSignaling	4L
#define VAL_lldpXMedRemMediaPolicyAppType_softPhoneVoice	5L
#define VAL_lldpXMedRemMediaPolicyAppType_videoconferencing	6L
#define VAL_lldpXMedRemMediaPolicyAppType_streamingVideo	7L
#define VAL_lldpXMedRemMediaPolicyAppType_videoSignaling	8L
#define LEAF_lldpXMedRemMediaPolicyVlanID	2
#define MIN_lldpXMedRemMediaPolicyVlanID	0L
#define MAX_lldpXMedRemMediaPolicyVlanID	4095L
#define LEAF_lldpXMedRemMediaPolicyPriority	3
#define MIN_lldpXMedRemMediaPolicyPriority	0L
#define MAX_lldpXMedRemMediaPolicyPriority	7L
#define LEAF_lldpXMedRemMediaPolicyDscp	4
#define MIN_lldpXMedRemMediaPolicyDscp	0L
#define MAX_lldpXMedRemMediaPolicyDscp	63L
#define LEAF_lldpXMedRemMediaPolicyUnknown	5
#define VAL_lldpXMedRemMediaPolicyUnknown_true	1L
#define VAL_lldpXMedRemMediaPolicyUnknown_false	2L
#define LEAF_lldpXMedRemMediaPolicyTagged	6
#define VAL_lldpXMedRemMediaPolicyTagged_true	1L
#define VAL_lldpXMedRemMediaPolicyTagged_false	2L
#define LEAF_lldpXMedRemHardwareRev	1
#define MINSIZE_lldpXMedRemHardwareRev	0L
#define MAXSIZE_lldpXMedRemHardwareRev	32L
#define LEAF_lldpXMedRemFirmwareRev	2
#define MINSIZE_lldpXMedRemFirmwareRev	0L
#define MAXSIZE_lldpXMedRemFirmwareRev	32L
#define LEAF_lldpXMedRemSoftwareRev	3
#define MINSIZE_lldpXMedRemSoftwareRev	0L
#define MAXSIZE_lldpXMedRemSoftwareRev	32L
#define LEAF_lldpXMedRemSerialNum	4
#define MINSIZE_lldpXMedRemSerialNum	0L
#define MAXSIZE_lldpXMedRemSerialNum	32L
#define LEAF_lldpXMedRemMfgName	5
#define MINSIZE_lldpXMedRemMfgName	0L
#define MAXSIZE_lldpXMedRemMfgName	32L
#define LEAF_lldpXMedRemModelName	6
#define MINSIZE_lldpXMedRemModelName	0L
#define MAXSIZE_lldpXMedRemModelName	32L
#define LEAF_lldpXMedRemAssetID	7
#define MINSIZE_lldpXMedRemAssetID	0L
#define MAXSIZE_lldpXMedRemAssetID	32L
#define LEAF_lldpXMedRemLocationSubtype	1
#define VAL_lldpXMedRemLocationSubtype_unknown	1L
#define VAL_lldpXMedRemLocationSubtype_coordinateBased	2L
#define VAL_lldpXMedRemLocationSubtype_civicAddress	3L
#define VAL_lldpXMedRemLocationSubtype_elin	4L
#define LEAF_lldpXMedRemLocationInfo	2
#define MINSIZE_lldpXMedRemLocationInfo	0L
#define MAXSIZE_lldpXMedRemLocationInfo	256L
#define LEAF_lldpXMedRemXPoEDeviceType	1
#define VAL_lldpXMedRemXPoEDeviceType_unknown	1L
#define VAL_lldpXMedRemXPoEDeviceType_pseDevice	2L
#define VAL_lldpXMedRemXPoEDeviceType_pdDevice	3L
#define VAL_lldpXMedRemXPoEDeviceType_none	4L
#define LEAF_lldpXMedRemXPoEPSEPowerAv	1
#define MIN_lldpXMedRemXPoEPSEPowerAv	0L
#define MAX_lldpXMedRemXPoEPSEPowerAv	1023L
#define LEAF_lldpXMedRemXPoEPSEPowerSource	2
#define VAL_lldpXMedRemXPoEPSEPowerSource_unknown	1L
#define VAL_lldpXMedRemXPoEPSEPowerSource_primary	2L
#define VAL_lldpXMedRemXPoEPSEPowerSource_backup	3L
#define LEAF_lldpXMedRemXPoEPSEPowerPriority	3
#define VAL_lldpXMedRemXPoEPSEPowerPriority_unknown	1L
#define VAL_lldpXMedRemXPoEPSEPowerPriority_critical	2L
#define VAL_lldpXMedRemXPoEPSEPowerPriority_high	3L
#define VAL_lldpXMedRemXPoEPSEPowerPriority_low	4L
#define LEAF_lldpXMedRemXPoEPDPowerReq	1
#define MIN_lldpXMedRemXPoEPDPowerReq	0L
#define MAX_lldpXMedRemXPoEPDPowerReq	1023L
#define LEAF_lldpXMedRemXPoEPDPowerSource	2
#define VAL_lldpXMedRemXPoEPDPowerSource_unknown	1L
#define VAL_lldpXMedRemXPoEPDPowerSource_fromPSE	2L
#define VAL_lldpXMedRemXPoEPDPowerSource_local	3L
#define VAL_lldpXMedRemXPoEPDPowerSource_localAndPSE	4L
#define LEAF_lldpXMedRemXPoEPDPowerPriority	3
#define VAL_lldpXMedRemXPoEPDPowerPriority_unknown	1L
#define VAL_lldpXMedRemXPoEPDPowerPriority_critical	2L
#define VAL_lldpXMedRemXPoEPDPowerPriority_high	3L
#define VAL_lldpXMedRemXPoEPDPowerPriority_low	4L

