/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 18:57:53 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1850-OSPF.mib, rfc1850.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_1850_H
#define  LEAF_1850_H

#define LEAF_ospfRouterId	1
#define LEAF_ospfAdminStat	2
#define VAL_ospfAdminStat_enabled	1L
#define VAL_ospfAdminStat_disabled	2L
#define LEAF_ospfVersionNumber	3
#define VAL_ospfVersionNumber_version2	2L
#define LEAF_ospfAreaBdrRtrStatus	4
#define VAL_ospfAreaBdrRtrStatus_true	1L
#define VAL_ospfAreaBdrRtrStatus_false	2L
#define LEAF_ospfASBdrRtrStatus	5
#define VAL_ospfASBdrRtrStatus_true	1L
#define VAL_ospfASBdrRtrStatus_false	2L
#define LEAF_ospfExternLsaCount	6
#define LEAF_ospfExternLsaCksumSum	7
#define LEAF_ospfTOSSupport	8
#define VAL_ospfTOSSupport_true	1L
#define VAL_ospfTOSSupport_false	2L
#define LEAF_ospfOriginateNewLsas	9
#define LEAF_ospfRxNewLsas	10
#define LEAF_ospfExtLsdbLimit	11
#define MIN_ospfExtLsdbLimit	-1L
#define MAX_ospfExtLsdbLimit	2147483647L
#define LEAF_ospfMulticastExtensions	12
#define LEAF_ospfExitOverflowInterval	13
#define MIN_ospfExitOverflowInterval	0L
#define MAX_ospfExitOverflowInterval	2147483647L
#define LEAF_ospfDemandExtensions	14
#define VAL_ospfDemandExtensions_true	1L
#define VAL_ospfDemandExtensions_false	2L
#define LEAF_ospfAreaId	1
#define LEAF_ospfAuthType	2
#define LEAF_ospfImportAsExtern	3
#define VAL_ospfImportAsExtern_importExternal	1L
#define VAL_ospfImportAsExtern_importNoExternal	2L
#define VAL_ospfImportAsExtern_importNssa	3L
#define LEAF_ospfSpfRuns	4
#define LEAF_ospfAreaBdrRtrCount	5
#define LEAF_ospfAsBdrRtrCount	6
#define LEAF_ospfAreaLsaCount	7
#define LEAF_ospfAreaLsaCksumSum	8
#define LEAF_ospfAreaSummary	9
#define VAL_ospfAreaSummary_noAreaSummary	1L
#define VAL_ospfAreaSummary_sendAreaSummary	2L
#define LEAF_ospfAreaStatus	10
#define VAL_ospfAreaStatus_active	1L
#define VAL_ospfAreaStatus_notInService	2L
#define VAL_ospfAreaStatus_notReady	3L
#define VAL_ospfAreaStatus_createAndGo	4L
#define VAL_ospfAreaStatus_createAndWait	5L
#define VAL_ospfAreaStatus_destroy	6L
#define LEAF_ospfStubAreaId	1
#define LEAF_ospfStubTOS	2
#define MIN_ospfStubTOS	0L
#define MAX_ospfStubTOS	30L
#define LEAF_ospfStubMetric	3
#define MIN_ospfStubMetric	0L
#define MAX_ospfStubMetric	16777215L
#define LEAF_ospfStubStatus	4
#define VAL_ospfStubStatus_active	1L
#define VAL_ospfStubStatus_notInService	2L
#define VAL_ospfStubStatus_notReady	3L
#define VAL_ospfStubStatus_createAndGo	4L
#define VAL_ospfStubStatus_createAndWait	5L
#define VAL_ospfStubStatus_destroy	6L
#define LEAF_ospfStubMetricType	5
#define VAL_ospfStubMetricType_ospfMetric	1L
#define VAL_ospfStubMetricType_comparableCost	2L
#define VAL_ospfStubMetricType_nonComparable	3L
#define LEAF_ospfLsdbAreaId	1
#define LEAF_ospfLsdbType	2
#define VAL_ospfLsdbType_routerLink	1L
#define VAL_ospfLsdbType_networkLink	2L
#define VAL_ospfLsdbType_summaryLink	3L
#define VAL_ospfLsdbType_asSummaryLink	4L
#define VAL_ospfLsdbType_asExternalLink	5L
#define VAL_ospfLsdbType_multicastLink	6L
#define VAL_ospfLsdbType_nssaExternalLink	7L
#define LEAF_ospfLsdbLsid	3
#define LEAF_ospfLsdbRouterId	4
#define LEAF_ospfLsdbSequence	5
#define LEAF_ospfLsdbAge	6
#define LEAF_ospfLsdbChecksum	7
#define LEAF_ospfLsdbAdvertisement	8
#define MINSIZE_ospfLsdbAdvertisement	1L
#define MAXSIZE_ospfLsdbAdvertisement	65535L
#define LEAF_ospfAreaRangeAreaId	1
#define LEAF_ospfAreaRangeNet	2
#define LEAF_ospfAreaRangeMask	3
#define LEAF_ospfAreaRangeStatus	4
#define VAL_ospfAreaRangeStatus_active	1L
#define VAL_ospfAreaRangeStatus_notInService	2L
#define VAL_ospfAreaRangeStatus_notReady	3L
#define VAL_ospfAreaRangeStatus_createAndGo	4L
#define VAL_ospfAreaRangeStatus_createAndWait	5L
#define VAL_ospfAreaRangeStatus_destroy	6L
#define LEAF_ospfAreaRangeEffect	5
#define VAL_ospfAreaRangeEffect_advertiseMatching	1L
#define VAL_ospfAreaRangeEffect_doNotAdvertiseMatching	2L
#define LEAF_ospfHostIpAddress	1
#define LEAF_ospfHostTOS	2
#define MIN_ospfHostTOS	0L
#define MAX_ospfHostTOS	30L
#define LEAF_ospfHostMetric	3
#define MIN_ospfHostMetric	0L
#define MAX_ospfHostMetric	65535L
#define LEAF_ospfHostStatus	4
#define VAL_ospfHostStatus_active	1L
#define VAL_ospfHostStatus_notInService	2L
#define VAL_ospfHostStatus_notReady	3L
#define VAL_ospfHostStatus_createAndGo	4L
#define VAL_ospfHostStatus_createAndWait	5L
#define VAL_ospfHostStatus_destroy	6L
#define LEAF_ospfHostAreaID	5
#define LEAF_ospfIfIpAddress	1
#define LEAF_ospfAddressLessIf	2
#define LEAF_ospfIfAreaId	3
#define LEAF_ospfIfType	4
#define VAL_ospfIfType_broadcast	1L
#define VAL_ospfIfType_nbma	2L
#define VAL_ospfIfType_pointToPoint	3L
#define VAL_ospfIfType_pointToMultipoint	5L
#define LEAF_ospfIfAdminStat	5
#define VAL_ospfIfAdminStat_enabled	1L
#define VAL_ospfIfAdminStat_disabled	2L
#define LEAF_ospfIfRtrPriority	6
#define MIN_ospfIfRtrPriority	0L
#define MAX_ospfIfRtrPriority	255L
#define LEAF_ospfIfTransitDelay	7
#define MIN_ospfIfTransitDelay	1L
#define MAX_ospfIfTransitDelay	65535L
#define LEAF_ospfIfRetransInterval	8
#define MIN_ospfIfRetransInterval	1L
#define MAX_ospfIfRetransInterval	65535L
#define LEAF_ospfIfHelloInterval	9
#define MIN_ospfIfHelloInterval	1L
#define MAX_ospfIfHelloInterval	65535L
#define LEAF_ospfIfRtrDeadInterval	10
#define MIN_ospfIfRtrDeadInterval	1L
#define MAX_ospfIfRtrDeadInterval	2147483647L
#define LEAF_ospfIfPollInterval	11
#define MIN_ospfIfPollInterval	0L
#define MAX_ospfIfPollInterval	2147483647L
#define LEAF_ospfIfState	12
#define VAL_ospfIfState_down	1L
#define VAL_ospfIfState_loopback	2L
#define VAL_ospfIfState_waiting	3L
#define VAL_ospfIfState_pointToPoint	4L
#define VAL_ospfIfState_designatedRouter	5L
#define VAL_ospfIfState_backupDesignatedRouter	6L
#define VAL_ospfIfState_otherDesignatedRouter	7L
#define LEAF_ospfIfDesignatedRouter	13
#define LEAF_ospfIfBackupDesignatedRouter	14
#define LEAF_ospfIfEvents	15
#define LEAF_ospfIfAuthKey	16
#define MINSIZE_ospfIfAuthKey	0L
#define MAXSIZE_ospfIfAuthKey	256L
#define LEAF_ospfIfStatus	17
#define VAL_ospfIfStatus_active	1L
#define VAL_ospfIfStatus_notInService	2L
#define VAL_ospfIfStatus_notReady	3L
#define VAL_ospfIfStatus_createAndGo	4L
#define VAL_ospfIfStatus_createAndWait	5L
#define VAL_ospfIfStatus_destroy	6L
#define LEAF_ospfIfMulticastForwarding	18
#define VAL_ospfIfMulticastForwarding_blocked	1L
#define VAL_ospfIfMulticastForwarding_multicast	2L
#define VAL_ospfIfMulticastForwarding_unicast	3L
#define LEAF_ospfIfDemand	19
#define VAL_ospfIfDemand_true	1L
#define VAL_ospfIfDemand_false	2L
#define LEAF_ospfIfAuthType	20
#define MIN_ospfIfAuthType	0L
#define MAX_ospfIfAuthType	255L
#define LEAF_ospfIfMetricIpAddress	1
#define LEAF_ospfIfMetricAddressLessIf	2
#define LEAF_ospfIfMetricTOS	3
#define MIN_ospfIfMetricTOS	0L
#define MAX_ospfIfMetricTOS	30L
#define LEAF_ospfIfMetricValue	4
#define MIN_ospfIfMetricValue	1L
#define MAX_ospfIfMetricValue	65535L
#define LEAF_ospfIfMetricStatus	5
#define VAL_ospfIfMetricStatus_active	1L
#define VAL_ospfIfMetricStatus_notInService	2L
#define VAL_ospfIfMetricStatus_notReady	3L
#define VAL_ospfIfMetricStatus_createAndGo	4L
#define VAL_ospfIfMetricStatus_createAndWait	5L
#define VAL_ospfIfMetricStatus_destroy	6L
#define LEAF_ospfVirtIfAreaId	1
#define LEAF_ospfVirtIfNeighbor	2
#define LEAF_ospfVirtIfTransitDelay	3
#define MIN_ospfVirtIfTransitDelay	0L
#define MAX_ospfVirtIfTransitDelay	3600L
#define LEAF_ospfVirtIfRetransInterval	4
#define MIN_ospfVirtIfRetransInterval	0L
#define MAX_ospfVirtIfRetransInterval	3600L
#define LEAF_ospfVirtIfHelloInterval	5
#define MIN_ospfVirtIfHelloInterval	1L
#define MAX_ospfVirtIfHelloInterval	65535L
#define LEAF_ospfVirtIfRtrDeadInterval	6
#define MIN_ospfVirtIfRtrDeadInterval	0L
#define MAX_ospfVirtIfRtrDeadInterval	2147483647L
#define LEAF_ospfVirtIfState	7
#define VAL_ospfVirtIfState_down	1L
#define VAL_ospfVirtIfState_pointToPoint	4L
#define LEAF_ospfVirtIfEvents	8
#define LEAF_ospfVirtIfAuthKey	9
#define MINSIZE_ospfVirtIfAuthKey	0L
#define MAXSIZE_ospfVirtIfAuthKey	256L
#define LEAF_ospfVirtIfStatus	10
#define VAL_ospfVirtIfStatus_active	1L
#define VAL_ospfVirtIfStatus_notInService	2L
#define VAL_ospfVirtIfStatus_notReady	3L
#define VAL_ospfVirtIfStatus_createAndGo	4L
#define VAL_ospfVirtIfStatus_createAndWait	5L
#define VAL_ospfVirtIfStatus_destroy	6L
#define LEAF_ospfVirtIfAuthType	11
#define MIN_ospfVirtIfAuthType	0L
#define MAX_ospfVirtIfAuthType	255L
#define LEAF_ospfNbrIpAddr	1
#define LEAF_ospfNbrAddressLessIndex	2
#define LEAF_ospfNbrRtrId	3
#define LEAF_ospfNbrOptions	4
#define LEAF_ospfNbrPriority	5
#define MIN_ospfNbrPriority	0L
#define MAX_ospfNbrPriority	255L
#define LEAF_ospfNbrState	6
#define VAL_ospfNbrState_down	1L
#define VAL_ospfNbrState_attempt	2L
#define VAL_ospfNbrState_init	3L
#define VAL_ospfNbrState_twoWay	4L
#define VAL_ospfNbrState_exchangeStart	5L
#define VAL_ospfNbrState_exchange	6L
#define VAL_ospfNbrState_loading	7L
#define VAL_ospfNbrState_full	8L
#define LEAF_ospfNbrEvents	7
#define LEAF_ospfNbrLsRetransQLen	8
#define LEAF_ospfNbmaNbrStatus	9
#define VAL_ospfNbmaNbrStatus_active	1L
#define VAL_ospfNbmaNbrStatus_notInService	2L
#define VAL_ospfNbmaNbrStatus_notReady	3L
#define VAL_ospfNbmaNbrStatus_createAndGo	4L
#define VAL_ospfNbmaNbrStatus_createAndWait	5L
#define VAL_ospfNbmaNbrStatus_destroy	6L
#define LEAF_ospfNbmaNbrPermanence	10
#define VAL_ospfNbmaNbrPermanence_dynamic	1L
#define VAL_ospfNbmaNbrPermanence_permanent	2L
#define LEAF_ospfNbrHelloSuppressed	11
#define VAL_ospfNbrHelloSuppressed_true	1L
#define VAL_ospfNbrHelloSuppressed_false	2L
#define LEAF_ospfVirtNbrArea	1
#define LEAF_ospfVirtNbrRtrId	2
#define LEAF_ospfVirtNbrIpAddr	3
#define LEAF_ospfVirtNbrOptions	4
#define LEAF_ospfVirtNbrState	5
#define VAL_ospfVirtNbrState_down	1L
#define VAL_ospfVirtNbrState_attempt	2L
#define VAL_ospfVirtNbrState_init	3L
#define VAL_ospfVirtNbrState_twoWay	4L
#define VAL_ospfVirtNbrState_exchangeStart	5L
#define VAL_ospfVirtNbrState_exchange	6L
#define VAL_ospfVirtNbrState_loading	7L
#define VAL_ospfVirtNbrState_full	8L
#define LEAF_ospfVirtNbrEvents	6
#define LEAF_ospfVirtNbrLsRetransQLen	7
#define LEAF_ospfVirtNbrHelloSuppressed	8
#define VAL_ospfVirtNbrHelloSuppressed_true	1L
#define VAL_ospfVirtNbrHelloSuppressed_false	2L
#define LEAF_ospfExtLsdbType	1
#define VAL_ospfExtLsdbType_asExternalLink	5L
#define LEAF_ospfExtLsdbLsid	2
#define LEAF_ospfExtLsdbRouterId	3
#define LEAF_ospfExtLsdbSequence	4
#define LEAF_ospfExtLsdbAge	5
#define LEAF_ospfExtLsdbChecksum	6
#define LEAF_ospfExtLsdbAdvertisement	7
#define SIZE_ospfExtLsdbAdvertisement	36L
#define LEAF_ospfAreaAggregateAreaID	1
#define LEAF_ospfAreaAggregateLsdbType	2
#define VAL_ospfAreaAggregateLsdbType_summaryLink	3L
#define VAL_ospfAreaAggregateLsdbType_nssaExternalLink	7L
#define LEAF_ospfAreaAggregateNet	3
#define LEAF_ospfAreaAggregateMask	4
#define LEAF_ospfAreaAggregateStatus	5
#define VAL_ospfAreaAggregateStatus_active	1L
#define VAL_ospfAreaAggregateStatus_notInService	2L
#define VAL_ospfAreaAggregateStatus_notReady	3L
#define VAL_ospfAreaAggregateStatus_createAndGo	4L
#define VAL_ospfAreaAggregateStatus_createAndWait	5L
#define VAL_ospfAreaAggregateStatus_destroy	6L
#define LEAF_ospfAreaAggregateEffect	6
#define VAL_ospfAreaAggregateEffect_advertiseMatching	1L
#define VAL_ospfAreaAggregateEffect_doNotAdvertiseMatching	2L

#endif /* end of #ifndef  LEAF_1850_H */

