/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 18:45:24 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1447-SNMPv2-PARTY.mib, Rfc1450-SNMPv2.mib,
 ****  E-Rfc1573-IANAifType.mib, Rfc2863-IF.mib, Rfc1659-RS-232.mib,
 ****  rfc1659.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_1659_H
#define  LEAF_1659_H

#define LEAF_rs232Number	1
#define LEAF_rs232PortIndex	1
#define MIN_rs232PortIndex	1L
#define MAX_rs232PortIndex	2147483647L
#define LEAF_rs232PortType	2
#define VAL_rs232PortType_other	1L
#define VAL_rs232PortType_rs232	2L
#define VAL_rs232PortType_rs422	3L
#define VAL_rs232PortType_rs423	4L
#define VAL_rs232PortType_v35	5L
#define VAL_rs232PortType_x21	6L
#define LEAF_rs232PortInSigNumber	3
#define LEAF_rs232PortOutSigNumber	4
#define LEAF_rs232PortInSpeed	5
#define LEAF_rs232PortOutSpeed	6
#define LEAF_rs232PortInFlowType	7
#define VAL_rs232PortInFlowType_none	1L
#define VAL_rs232PortInFlowType_ctsRts	2L
#define VAL_rs232PortInFlowType_dsrDtr	3L
#define LEAF_rs232PortOutFlowType	8
#define VAL_rs232PortOutFlowType_none	1L
#define VAL_rs232PortOutFlowType_ctsRts	2L
#define VAL_rs232PortOutFlowType_dsrDtr	3L
#define LEAF_rs232AsyncPortIndex	1
#define MIN_rs232AsyncPortIndex	1L
#define MAX_rs232AsyncPortIndex	2147483647L
#define LEAF_rs232AsyncPortBits	2
#define MIN_rs232AsyncPortBits	5L
#define MAX_rs232AsyncPortBits	8L
#define LEAF_rs232AsyncPortStopBits	3
#define VAL_rs232AsyncPortStopBits_one	1L
#define VAL_rs232AsyncPortStopBits_two	2L
#define VAL_rs232AsyncPortStopBits_oneAndHalf	3L
#define VAL_rs232AsyncPortStopBits_dynamic	4L
#define LEAF_rs232AsyncPortParity	4
#define VAL_rs232AsyncPortParity_none	1L
#define VAL_rs232AsyncPortParity_odd	2L
#define VAL_rs232AsyncPortParity_even	3L
#define VAL_rs232AsyncPortParity_mark	4L
#define VAL_rs232AsyncPortParity_space	5L
#define LEAF_rs232AsyncPortAutobaud	5
#define VAL_rs232AsyncPortAutobaud_enabled	1L
#define VAL_rs232AsyncPortAutobaud_disabled	2L
#define LEAF_rs232AsyncPortParityErrs	6
#define LEAF_rs232AsyncPortFramingErrs	7
#define LEAF_rs232AsyncPortOverrunErrs	8
#define LEAF_rs232SyncPortIndex	1
#define MIN_rs232SyncPortIndex	1L
#define MAX_rs232SyncPortIndex	2147483647L
#define LEAF_rs232SyncPortClockSource	2
#define VAL_rs232SyncPortClockSource_internal	1L
#define VAL_rs232SyncPortClockSource_external	2L
#define VAL_rs232SyncPortClockSource_split	3L
#define LEAF_rs232SyncPortFrameCheckErrs	3
#define LEAF_rs232SyncPortTransmitUnderrunErrs	4
#define LEAF_rs232SyncPortReceiveOverrunErrs	5
#define LEAF_rs232SyncPortInterruptedFrames	6
#define LEAF_rs232SyncPortAbortedFrames	7
#define LEAF_rs232SyncPortRole	8
#define VAL_rs232SyncPortRole_dte	1L
#define VAL_rs232SyncPortRole_dce	2L
#define LEAF_rs232SyncPortEncoding	9
#define VAL_rs232SyncPortEncoding_nrz	1L
#define VAL_rs232SyncPortEncoding_nrzi	2L
#define LEAF_rs232SyncPortRTSControl	10
#define VAL_rs232SyncPortRTSControl_controlled	1L
#define VAL_rs232SyncPortRTSControl_constant	2L
#define LEAF_rs232SyncPortRTSCTSDelay	11
#define LEAF_rs232SyncPortMode	12
#define VAL_rs232SyncPortMode_fdx	1L
#define VAL_rs232SyncPortMode_hdx	2L
#define VAL_rs232SyncPortMode_simplex_receive	3L
#define VAL_rs232SyncPortMode_simplex_send	4L
#define LEAF_rs232SyncPortIdlePattern	13
#define VAL_rs232SyncPortIdlePattern_mark	1L
#define VAL_rs232SyncPortIdlePattern_space	2L
#define LEAF_rs232SyncPortMinFlags	14
#define LEAF_rs232InSigPortIndex	1
#define MIN_rs232InSigPortIndex	1L
#define MAX_rs232InSigPortIndex	2147483647L
#define LEAF_rs232InSigName	2
#define VAL_rs232InSigName_rts	1L
#define VAL_rs232InSigName_cts	2L
#define VAL_rs232InSigName_dsr	3L
#define VAL_rs232InSigName_dtr	4L
#define VAL_rs232InSigName_ri	5L
#define VAL_rs232InSigName_dcd	6L
#define VAL_rs232InSigName_sq	7L
#define VAL_rs232InSigName_srs	8L
#define VAL_rs232InSigName_srts	9L
#define VAL_rs232InSigName_scts	10L
#define VAL_rs232InSigName_sdcd	11L
#define LEAF_rs232InSigState	3
#define VAL_rs232InSigState_none	1L
#define VAL_rs232InSigState_on	2L
#define VAL_rs232InSigState_off	3L
#define LEAF_rs232InSigChanges	4
#define LEAF_rs232OutSigPortIndex	1
#define MIN_rs232OutSigPortIndex	1L
#define MAX_rs232OutSigPortIndex	2147483647L
#define LEAF_rs232OutSigName	2
#define VAL_rs232OutSigName_rts	1L
#define VAL_rs232OutSigName_cts	2L
#define VAL_rs232OutSigName_dsr	3L
#define VAL_rs232OutSigName_dtr	4L
#define VAL_rs232OutSigName_ri	5L
#define VAL_rs232OutSigName_dcd	6L
#define VAL_rs232OutSigName_sq	7L
#define VAL_rs232OutSigName_srs	8L
#define VAL_rs232OutSigName_srts	9L
#define VAL_rs232OutSigName_scts	10L
#define VAL_rs232OutSigName_sdcd	11L
#define LEAF_rs232OutSigState	3
#define VAL_rs232OutSigState_none	1L
#define VAL_rs232OutSigState_on	2L
#define VAL_rs232OutSigState_off	3L
#define LEAF_rs232OutSigChanges	4

#endif /* end of #ifndef  LEAF_1659_H */
