/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Wed Oct 27 10:05:23 2004
 **** from files:
 ****  ..\MibFiles\Rfc1213.mib, ctl\Rfc1213.ctl,
 ****  ..\MibFiles\IanaIfType_Rfc1573.mib, ..\MibFiles\SnmpV2_Rfc1907.mib,
 ****  ctl\SnmpV2_Rfc1907.ctl, ..\MibFiles\If_Rfc2863.mib, ctl\If_Rfc2863.ctl,
 ****  ..\MibFiles\SnmpFramework_Rfc2271.mib, ctl\SnmpFramework_Rfc2271.ctl,
 ****  ..\MibFiles\Ieee8021Pae.mib, ctl\Ieee8021Pae.ctl,
 ****  ..\MibFiles\RFC2108.MIB, ..\MibFiles\3COM0045.mib,
 ****  ..\MibFiles\3COM0004.mib, ..\MibFiles\3fc-407R.mib
 ******************************************************************************
 ******************************************************************************
 */

#define LEAF_a3ComPaePortAssignEnable	1
#define VAL_a3ComPaePortAssignEnable_true	1L
#define VAL_a3ComPaePortAssignEnable_false	2L
#define LEAF_a3ComPaePortVlanAssignment	2
#define MINSIZE_a3ComPaePortVlanAssignment	0L
#define MAXSIZE_a3ComPaePortVlanAssignment	128L
#define LEAF_a3ComPaePortQosAssignment	3
#define MINSIZE_a3ComPaePortQosAssignment	0L
#define MAXSIZE_a3ComPaePortQosAssignment	128L
#define LEAF_snmpTrapOID	1
#define LEAF_snmpTrapEnterprise	3
