/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri May 31 11:02:40 2002
 **** from file:
 ****  Rfc2011.mib
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_2011_H
#define  LEAF_2011_H

#define LEAF_ipForwarding	1
#define VAL_ipForwarding_forwarding	1L
#define VAL_ipForwarding_notForwarding	2L
#define LEAF_ipDefaultTTL	2
#define MIN_ipDefaultTTL	1L
#define MAX_ipDefaultTTL	255L
#define LEAF_ipInReceives	3
#define LEAF_ipInHdrErrors	4
#define LEAF_ipInAddrErrors	5
#define LEAF_ipForwDatagrams	6
#define LEAF_ipInUnknownProtos	7
#define LEAF_ipInDiscards	8
#define LEAF_ipInDelivers	9
#define LEAF_ipOutRequests	10
#define LEAF_ipOutDiscards	11
#define LEAF_ipOutNoRoutes	12
#define LEAF_ipReasmTimeout	13
#define LEAF_ipReasmReqds	14
#define LEAF_ipReasmOKs	15
#define LEAF_ipReasmFails	16
#define LEAF_ipFragOKs	17
#define LEAF_ipFragFails	18
#define LEAF_ipFragCreates	19
#define LEAF_ipAdEntAddr	1
#define LEAF_ipAdEntIfIndex	2
#define MIN_ipAdEntIfIndex	1L
#define MAX_ipAdEntIfIndex	2147483647L
#define LEAF_ipAdEntNetMask	3
#define LEAF_ipAdEntBcastAddr	4
#define MIN_ipAdEntBcastAddr	0L
#define MAX_ipAdEntBcastAddr	1L
#define LEAF_ipAdEntReasmMaxSize	5
#define MIN_ipAdEntReasmMaxSize	0L
#define MAX_ipAdEntReasmMaxSize	65535L
#define LEAF_ipNetToMediaIfIndex	1
#define MIN_ipNetToMediaIfIndex	1L
#define MAX_ipNetToMediaIfIndex	2147483647L
#define LEAF_ipNetToMediaPhysAddress	2
#define LEAF_ipNetToMediaNetAddress	3
#define LEAF_ipNetToMediaType	4
#define VAL_ipNetToMediaType_other	1L
#define VAL_ipNetToMediaType_invalid	2L
#define VAL_ipNetToMediaType_dynamic	3L
#define VAL_ipNetToMediaType_static	4L
#define LEAF_ipRoutingDiscards	23
#define LEAF_icmpInMsgs	1
#define LEAF_icmpInErrors	2
#define LEAF_icmpInDestUnreachs	3
#define LEAF_icmpInTimeExcds	4
#define LEAF_icmpInParmProbs	5
#define LEAF_icmpInSrcQuenchs	6
#define LEAF_icmpInRedirects	7
#define LEAF_icmpInEchos	8
#define LEAF_icmpInEchoReps	9
#define LEAF_icmpInTimestamps	10
#define LEAF_icmpInTimestampReps	11
#define LEAF_icmpInAddrMasks	12
#define LEAF_icmpInAddrMaskReps	13
#define LEAF_icmpOutMsgs	14
#define LEAF_icmpOutErrors	15
#define LEAF_icmpOutDestUnreachs	16
#define LEAF_icmpOutTimeExcds	17
#define LEAF_icmpOutParmProbs	18
#define LEAF_icmpOutSrcQuenchs	19
#define LEAF_icmpOutRedirects	20
#define LEAF_icmpOutEchos	21
#define LEAF_icmpOutEchoReps	22
#define LEAF_icmpOutTimestamps	23
#define LEAF_icmpOutTimestampReps	24
#define LEAF_icmpOutAddrMasks	25
#define LEAF_icmpOutAddrMaskReps	26

#endif /* end of #ifndef  LEAF_2011_H */
