/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 23:28:11 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1493-BRIDGE.mib, Rfc2271-SNMP-FRAMEWORK.mib,
 ****  Rfc2674-P-BRIDGE.mib, Rfc1757-RMON-MIB.mib,
 ****  E-Rfc1513-TOKEN-RING-RMON.mib, Rfc2021-RMON2.mib, Rfc2674-Q-BRIDGE.mib,
 ****  U-BRIDGE.mib, u-bridge.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_UBRIDGE_H
#define  LEAF_UBRIDGE_H

#define LEAF_dot1qNextFreeLocalVlanIndex	4
#define MIN_dot1qNextFreeLocalVlanIndex_1	0L
#define MAX_dot1qNextFreeLocalVlanIndex_1	0L
#define MIN_dot1qNextFreeLocalVlanIndex_2	4096L
#define MAX_dot1qNextFreeLocalVlanIndex_2	2147483647L
#define LEAF_dot1qPortRestrictedRegistration	1
#define VAL_dot1qPortRestrictedRegistration_true	1L
#define VAL_dot1qPortRestrictedRegistration_false	2L

#endif /* end of #ifndef  LEAF_UBRIDGE_H */

