/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 18:54:46 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1757-RMON-MIB.mib, rfc1757.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_1757_H
#define  LEAF_1757_H

#define LEAF_etherStatsIndex	1
#define MIN_etherStatsIndex	1L
#define MAX_etherStatsIndex	65535L
#define LEAF_etherStatsDataSource	2
#define LEAF_etherStatsDropEvents	3
#define LEAF_etherStatsOctets	4
#define LEAF_etherStatsPkts	5
#define LEAF_etherStatsBroadcastPkts	6
#define LEAF_etherStatsMulticastPkts	7
#define LEAF_etherStatsCRCAlignErrors	8
#define LEAF_etherStatsUndersizePkts	9
#define LEAF_etherStatsOversizePkts	10
#define LEAF_etherStatsFragments	11
#define LEAF_etherStatsJabbers	12
#define LEAF_etherStatsCollisions	13
#define LEAF_etherStatsPkts64Octets	14
#define LEAF_etherStatsPkts65to127Octets	15
#define LEAF_etherStatsPkts128to255Octets	16
#define LEAF_etherStatsPkts256to511Octets	17
#define LEAF_etherStatsPkts512to1023Octets	18
#define LEAF_etherStatsPkts1024to1518Octets	19
#define LEAF_etherStatsOwner	20
#define LEAF_etherStatsStatus	21
#define VAL_etherStatsStatus_valid	1L
#define VAL_etherStatsStatus_createRequest	2L
#define VAL_etherStatsStatus_underCreation	3L
#define VAL_etherStatsStatus_invalid	4L
#define LEAF_historyControlIndex	1
#define MIN_historyControlIndex	1L
#define MAX_historyControlIndex	65535L
#define LEAF_historyControlDataSource	2
#define LEAF_historyControlBucketsRequested	3
#define MIN_historyControlBucketsRequested	1L
#define MAX_historyControlBucketsRequested	65535L
#define LEAF_historyControlBucketsGranted	4
#define MIN_historyControlBucketsGranted	1L
#define MAX_historyControlBucketsGranted	65535L
#define LEAF_historyControlInterval	5
#define MIN_historyControlInterval	1L
#define MAX_historyControlInterval	3600L
#define LEAF_historyControlOwner	6
#define LEAF_historyControlStatus	7
#define VAL_historyControlStatus_valid	1L
#define VAL_historyControlStatus_createRequest	2L
#define VAL_historyControlStatus_underCreation	3L
#define VAL_historyControlStatus_invalid	4L
#define LEAF_etherHistoryIndex	1
#define MIN_etherHistoryIndex	1L
#define MAX_etherHistoryIndex	65535L
#define LEAF_etherHistorySampleIndex	2
#define MIN_etherHistorySampleIndex	1L
#define MAX_etherHistorySampleIndex	2147483647L
#define LEAF_etherHistoryIntervalStart	3
#define LEAF_etherHistoryDropEvents	4
#define LEAF_etherHistoryOctets	5
#define LEAF_etherHistoryPkts	6
#define LEAF_etherHistoryBroadcastPkts	7
#define LEAF_etherHistoryMulticastPkts	8
#define LEAF_etherHistoryCRCAlignErrors	9
#define LEAF_etherHistoryUndersizePkts	10
#define LEAF_etherHistoryOversizePkts	11
#define LEAF_etherHistoryFragments	12
#define LEAF_etherHistoryJabbers	13
#define LEAF_etherHistoryCollisions	14
#define LEAF_etherHistoryUtilization	15
#define MIN_etherHistoryUtilization	0L
#define MAX_etherHistoryUtilization	10000L
#define LEAF_alarmIndex	1
#define MIN_alarmIndex	1L
#define MAX_alarmIndex	65535L
#define LEAF_alarmInterval	2
#define LEAF_alarmVariable	3
#define LEAF_alarmSampleType	4
#define VAL_alarmSampleType_absoluteValue	1L
#define VAL_alarmSampleType_deltaValue	2L
#define LEAF_alarmValue	5
#define LEAF_alarmStartupAlarm	6
#define VAL_alarmStartupAlarm_risingAlarm	1L
#define VAL_alarmStartupAlarm_fallingAlarm	2L
#define VAL_alarmStartupAlarm_risingOrFallingAlarm	3L
#define LEAF_alarmRisingThreshold	7
#define LEAF_alarmFallingThreshold	8
#define LEAF_alarmRisingEventIndex	9
#define MIN_alarmRisingEventIndex	0L
#define MAX_alarmRisingEventIndex	65535L
#define LEAF_alarmFallingEventIndex	10
#define MIN_alarmFallingEventIndex	0L
#define MAX_alarmFallingEventIndex	65535L
#define LEAF_alarmOwner	11
#define LEAF_alarmStatus	12
#define VAL_alarmStatus_valid	1L
#define VAL_alarmStatus_createRequest	2L
#define VAL_alarmStatus_underCreation	3L
#define VAL_alarmStatus_invalid	4L
#define LEAF_hostControlIndex	1
#define MIN_hostControlIndex	1L
#define MAX_hostControlIndex	65535L
#define LEAF_hostControlDataSource	2
#define LEAF_hostControlTableSize	3
#define LEAF_hostControlLastDeleteTime	4
#define LEAF_hostControlOwner	5
#define LEAF_hostControlStatus	6
#define VAL_hostControlStatus_valid	1L
#define VAL_hostControlStatus_createRequest	2L
#define VAL_hostControlStatus_underCreation	3L
#define VAL_hostControlStatus_invalid	4L
#define LEAF_hostAddress	1
#define LEAF_hostCreationOrder	2
#define MIN_hostCreationOrder	1L
#define MAX_hostCreationOrder	65535L
#define LEAF_hostIndex	3
#define MIN_hostIndex	1L
#define MAX_hostIndex	65535L
#define LEAF_hostInPkts	4
#define LEAF_hostOutPkts	5
#define LEAF_hostInOctets	6
#define LEAF_hostOutOctets	7
#define LEAF_hostOutErrors	8
#define LEAF_hostOutBroadcastPkts	9
#define LEAF_hostOutMulticastPkts	10
#define LEAF_hostTimeAddress	1
#define LEAF_hostTimeCreationOrder	2
#define MIN_hostTimeCreationOrder	1L
#define MAX_hostTimeCreationOrder	65535L
#define LEAF_hostTimeIndex	3
#define MIN_hostTimeIndex	1L
#define MAX_hostTimeIndex	65535L
#define LEAF_hostTimeInPkts	4
#define LEAF_hostTimeOutPkts	5
#define LEAF_hostTimeInOctets	6
#define LEAF_hostTimeOutOctets	7
#define LEAF_hostTimeOutErrors	8
#define LEAF_hostTimeOutBroadcastPkts	9
#define LEAF_hostTimeOutMulticastPkts	10
#define LEAF_hostTopNControlIndex	1
#define MIN_hostTopNControlIndex	1L
#define MAX_hostTopNControlIndex	65535L
#define LEAF_hostTopNHostIndex	2
#define MIN_hostTopNHostIndex	1L
#define MAX_hostTopNHostIndex	65535L
#define LEAF_hostTopNRateBase	3
#define VAL_hostTopNRateBase_hostTopNInPkts	1L
#define VAL_hostTopNRateBase_hostTopNOutPkts	2L
#define VAL_hostTopNRateBase_hostTopNInOctets	3L
#define VAL_hostTopNRateBase_hostTopNOutOctets	4L
#define VAL_hostTopNRateBase_hostTopNOutErrors	5L
#define VAL_hostTopNRateBase_hostTopNOutBroadcastPkts	6L
#define VAL_hostTopNRateBase_hostTopNOutMulticastPkts	7L
#define LEAF_hostTopNTimeRemaining	4
#define LEAF_hostTopNDuration	5
#define LEAF_hostTopNRequestedSize	6
#define LEAF_hostTopNGrantedSize	7
#define LEAF_hostTopNStartTime	8
#define LEAF_hostTopNOwner	9
#define LEAF_hostTopNStatus	10
#define VAL_hostTopNStatus_valid	1L
#define VAL_hostTopNStatus_createRequest	2L
#define VAL_hostTopNStatus_underCreation	3L
#define VAL_hostTopNStatus_invalid	4L
#define LEAF_hostTopNReport	1
#define MIN_hostTopNReport	1L
#define MAX_hostTopNReport	65535L
#define LEAF_hostTopNIndex	2
#define MIN_hostTopNIndex	1L
#define MAX_hostTopNIndex	65535L
#define LEAF_hostTopNAddress	3
#define LEAF_hostTopNRate	4
#define LEAF_matrixControlIndex	1
#define MIN_matrixControlIndex	1L
#define MAX_matrixControlIndex	65535L
#define LEAF_matrixControlDataSource	2
#define LEAF_matrixControlTableSize	3
#define LEAF_matrixControlLastDeleteTime	4
#define LEAF_matrixControlOwner	5
#define LEAF_matrixControlStatus	6
#define VAL_matrixControlStatus_valid	1L
#define VAL_matrixControlStatus_createRequest	2L
#define VAL_matrixControlStatus_underCreation	3L
#define VAL_matrixControlStatus_invalid	4L
#define LEAF_matrixSDSourceAddress	1
#define LEAF_matrixSDDestAddress	2
#define LEAF_matrixSDIndex	3
#define MIN_matrixSDIndex	1L
#define MAX_matrixSDIndex	65535L
#define LEAF_matrixSDPkts	4
#define LEAF_matrixSDOctets	5
#define LEAF_matrixSDErrors	6
#define LEAF_matrixDSSourceAddress	1
#define LEAF_matrixDSDestAddress	2
#define LEAF_matrixDSIndex	3
#define MIN_matrixDSIndex	1L
#define MAX_matrixDSIndex	65535L
#define LEAF_matrixDSPkts	4
#define LEAF_matrixDSOctets	5
#define LEAF_matrixDSErrors	6
#define LEAF_filterIndex	1
#define MIN_filterIndex	1L
#define MAX_filterIndex	65535L
#define LEAF_filterChannelIndex	2
#define MIN_filterChannelIndex	1L
#define MAX_filterChannelIndex	65535L
#define LEAF_filterPktDataOffset	3
#define LEAF_filterPktData	4
#define LEAF_filterPktDataMask	5
#define LEAF_filterPktDataNotMask	6
#define LEAF_filterPktStatus	7
#define LEAF_filterPktStatusMask	8
#define LEAF_filterPktStatusNotMask	9
#define LEAF_filterOwner	10
#define LEAF_filterStatus	11
#define VAL_filterStatus_valid	1L
#define VAL_filterStatus_createRequest	2L
#define VAL_filterStatus_underCreation	3L
#define VAL_filterStatus_invalid	4L
#define LEAF_channelIndex	1
#define MIN_channelIndex	1L
#define MAX_channelIndex	65535L
#define LEAF_channelIfIndex	2
#define MIN_channelIfIndex	1L
#define MAX_channelIfIndex	65535L
#define LEAF_channelAcceptType	3
#define VAL_channelAcceptType_acceptMatched	1L
#define VAL_channelAcceptType_acceptFailed	2L
#define LEAF_channelDataControl	4
#define VAL_channelDataControl_on	1L
#define VAL_channelDataControl_off	2L
#define LEAF_channelTurnOnEventIndex	5
#define MIN_channelTurnOnEventIndex	0L
#define MAX_channelTurnOnEventIndex	65535L
#define LEAF_channelTurnOffEventIndex	6
#define MIN_channelTurnOffEventIndex	0L
#define MAX_channelTurnOffEventIndex	65535L
#define LEAF_channelEventIndex	7
#define MIN_channelEventIndex	0L
#define MAX_channelEventIndex	65535L
#define LEAF_channelEventStatus	8
#define VAL_channelEventStatus_eventReady	1L
#define VAL_channelEventStatus_eventFired	2L
#define VAL_channelEventStatus_eventAlwaysReady	3L
#define LEAF_channelMatches	9
#define LEAF_channelDescription	10
#define MINSIZE_channelDescription	0L
#define MAXSIZE_channelDescription	127L
#define LEAF_channelOwner	11
#define LEAF_channelStatus	12
#define VAL_channelStatus_valid	1L
#define VAL_channelStatus_createRequest	2L
#define VAL_channelStatus_underCreation	3L
#define VAL_channelStatus_invalid	4L
#define LEAF_bufferControlIndex	1
#define MIN_bufferControlIndex	1L
#define MAX_bufferControlIndex	65535L
#define LEAF_bufferControlChannelIndex	2
#define MIN_bufferControlChannelIndex	1L
#define MAX_bufferControlChannelIndex	65535L
#define LEAF_bufferControlFullStatus	3
#define VAL_bufferControlFullStatus_spaceAvailable	1L
#define VAL_bufferControlFullStatus_full	2L
#define LEAF_bufferControlFullAction	4
#define VAL_bufferControlFullAction_lockWhenFull	1L
#define VAL_bufferControlFullAction_wrapWhenFull	2L
#define LEAF_bufferControlCaptureSliceSize	5
#define LEAF_bufferControlDownloadSliceSize	6
#define LEAF_bufferControlDownloadOffset	7
#define LEAF_bufferControlMaxOctetsRequested	8
#define LEAF_bufferControlMaxOctetsGranted	9
#define LEAF_bufferControlCapturedPackets	10
#define LEAF_bufferControlTurnOnTime	11
#define LEAF_bufferControlOwner	12
#define LEAF_bufferControlStatus	13
#define VAL_bufferControlStatus_valid	1L
#define VAL_bufferControlStatus_createRequest	2L
#define VAL_bufferControlStatus_underCreation	3L
#define VAL_bufferControlStatus_invalid	4L
#define LEAF_captureBufferControlIndex	1
#define MIN_captureBufferControlIndex	1L
#define MAX_captureBufferControlIndex	65535L
#define LEAF_captureBufferIndex	2
#define MIN_captureBufferIndex	1L
#define MAX_captureBufferIndex	2147483647L
#define LEAF_captureBufferPacketID	3
#define LEAF_captureBufferPacketData	4
#define LEAF_captureBufferPacketLength	5
#define LEAF_captureBufferPacketTime	6
#define LEAF_captureBufferPacketStatus	7
#define LEAF_eventIndex	1
#define MIN_eventIndex	1L
#define MAX_eventIndex	65535L
#define LEAF_eventDescription	2
#define MINSIZE_eventDescription	0L
#define MAXSIZE_eventDescription	127L
#define LEAF_eventType	3
#define VAL_eventType_none	1L
#define VAL_eventType_log	2L
#define VAL_eventType_snmp_trap	3L
#define VAL_eventType_log_and_trap	4L
#define LEAF_eventCommunity	4
#define MINSIZE_eventCommunity	0L
#define MAXSIZE_eventCommunity	127L
#define LEAF_eventLastTimeSent	5
#define LEAF_eventOwner	6
#define LEAF_eventStatus	7
#define VAL_eventStatus_valid	1L
#define VAL_eventStatus_createRequest	2L
#define VAL_eventStatus_underCreation	3L
#define VAL_eventStatus_invalid	4L
#define LEAF_logEventIndex	1
#define MIN_logEventIndex	1L
#define MAX_logEventIndex	65535L
#define LEAF_logIndex	2
#define MIN_logIndex	1L
#define MAX_logIndex	2147483647L
#define LEAF_logTime	3
#define LEAF_logDescription	4
#define MINSIZE_logDescription	0L
#define MAXSIZE_logDescription	255L

#endif /* end of #ifndef  LEAF_1757_H */
