/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Oct 22 15:44:50 2004
 **** from files:
 ****  ..\MibFiles\Rfc1213.mib, ctl\Rfc1213.ctl,
 ****  ..\MibFiles\SnmpV2_Rfc1907.mib, ctl\SnmpV2_Rfc1907_NotSupport.ctl,
 ****  ..\MibFiles\IanaIfType_Rfc1573.mib, ..\MibFiles\If_Rfc2863.mib,
 ****  ..\MibFiles\Mau_Rfc3636.mib
 ******************************************************************************
 ******************************************************************************
 */

#ifndef  LEAF_3636_H
#define  LEAF_3636_H

#define LEAF_rpMauGroupIndex	1
#define MIN_rpMauGroupIndex	1L
#define MAX_rpMauGroupIndex	2147483647L
#define LEAF_rpMauPortIndex	2
#define MIN_rpMauPortIndex	1L
#define MAX_rpMauPortIndex	2147483647L
#define LEAF_rpMauIndex	3
#define MIN_rpMauIndex	1L
#define MAX_rpMauIndex	2147483647L
#define LEAF_rpMauType	4
#define LEAF_rpMauStatus	5
#define VAL_rpMauStatus_other	1L
#define VAL_rpMauStatus_unknown	2L
#define VAL_rpMauStatus_operational	3L
#define VAL_rpMauStatus_standby	4L
#define VAL_rpMauStatus_shutdown	5L
#define VAL_rpMauStatus_reset	6L
#define LEAF_rpMauMediaAvailable	6
#define VAL_rpMauMediaAvailable_other	1L
#define VAL_rpMauMediaAvailable_unknown	2L
#define VAL_rpMauMediaAvailable_available	3L
#define VAL_rpMauMediaAvailable_notAvailable	4L
#define VAL_rpMauMediaAvailable_remoteFault	5L
#define VAL_rpMauMediaAvailable_invalidSignal	6L
#define VAL_rpMauMediaAvailable_remoteJabber	7L
#define VAL_rpMauMediaAvailable_remoteLinkLoss	8L
#define VAL_rpMauMediaAvailable_remoteTest	9L
#define VAL_rpMauMediaAvailable_offline	10L
#define VAL_rpMauMediaAvailable_autoNegError	11L
#define LEAF_rpMauMediaAvailableStateExits	7
#define LEAF_rpMauJabberState	8
#define VAL_rpMauJabberState_other	1L
#define VAL_rpMauJabberState_unknown	2L
#define VAL_rpMauJabberState_noJabber	3L
#define VAL_rpMauJabberState_jabbering	4L
#define LEAF_rpMauJabberingStateEnters	9
#define LEAF_rpMauFalseCarriers	10
#define LEAF_rpJackIndex	1
#define MIN_rpJackIndex	1L
#define MAX_rpJackIndex	2147483647L
#define LEAF_rpJackType	2
#define VAL_rpJackType_other	1L
#define VAL_rpJackType_rj45	2L
#define VAL_rpJackType_rj45S	3L
#define VAL_rpJackType_db9	4L
#define VAL_rpJackType_bnc	5L
#define VAL_rpJackType_fAUI	6L
#define VAL_rpJackType_mAUI	7L
#define VAL_rpJackType_fiberSC	8L
#define VAL_rpJackType_fiberMIC	9L
#define VAL_rpJackType_fiberST	10L
#define VAL_rpJackType_telco	11L
#define VAL_rpJackType_mtrj	12L
#define VAL_rpJackType_hssdc	13L
#define VAL_rpJackType_fiberLC	14L
#define LEAF_ifMauIfIndex	1
#define MIN_ifMauIfIndex	1L
#define MAX_ifMauIfIndex	2147483647L
#define LEAF_ifMauIndex	2
#define MIN_ifMauIndex	1L
#define MAX_ifMauIndex	2147483647L
#define LEAF_ifMauType	3
#define LEAF_ifMauStatus	4
#define VAL_ifMauStatus_other	1L
#define VAL_ifMauStatus_unknown	2L
#define VAL_ifMauStatus_operational	3L
#define VAL_ifMauStatus_standby	4L
#define VAL_ifMauStatus_shutdown	5L
#define VAL_ifMauStatus_reset	6L
#define LEAF_ifMauMediaAvailable	5
#define VAL_ifMauMediaAvailable_other	1L
#define VAL_ifMauMediaAvailable_unknown	2L
#define VAL_ifMauMediaAvailable_available	3L
#define VAL_ifMauMediaAvailable_notAvailable	4L
#define VAL_ifMauMediaAvailable_remoteFault	5L
#define VAL_ifMauMediaAvailable_invalidSignal	6L
#define VAL_ifMauMediaAvailable_remoteJabber	7L
#define VAL_ifMauMediaAvailable_remoteLinkLoss	8L
#define VAL_ifMauMediaAvailable_remoteTest	9L
#define VAL_ifMauMediaAvailable_offline	10L
#define VAL_ifMauMediaAvailable_autoNegError	11L
#define VAL_ifMauMediaAvailable_pmdLinkFault	12L
#define VAL_ifMauMediaAvailable_wisFrameLoss	13L
#define VAL_ifMauMediaAvailable_wisSignalLoss	14L
#define VAL_ifMauMediaAvailable_pcsLinkFault	15L
#define VAL_ifMauMediaAvailable_excessiveBER	16L
#define VAL_ifMauMediaAvailable_dxsLinkFault	17L
#define VAL_ifMauMediaAvailable_pxsLinkFault	18L
#define LEAF_ifMauMediaAvailableStateExits	6
#define LEAF_ifMauJabberState	7
#define VAL_ifMauJabberState_other	1L
#define VAL_ifMauJabberState_unknown	2L
#define VAL_ifMauJabberState_noJabber	3L
#define VAL_ifMauJabberState_jabbering	4L
#define LEAF_ifMauJabberingStateEnters	8
#define LEAF_ifMauFalseCarriers	9
#define LEAF_ifMauTypeList	10
#define LEAF_ifMauDefaultType	11
#define LEAF_ifMauAutoNegSupported	12
#define VAL_ifMauAutoNegSupported_true	1L
#define VAL_ifMauAutoNegSupported_false	2L
#define LEAF_ifMauTypeListBits	13
#define VAL_ifMauTypeListBits_bOther	0L
#define VAL_ifMauTypeListBits_bAUI	1L
#define VAL_ifMauTypeListBits_b10base5	2L
#define VAL_ifMauTypeListBits_bFoirl	3L
#define VAL_ifMauTypeListBits_b10base2	4L
#define VAL_ifMauTypeListBits_b10baseT	5L
#define VAL_ifMauTypeListBits_b10baseFP	6L
#define VAL_ifMauTypeListBits_b10baseFB	7L
#define VAL_ifMauTypeListBits_b10baseFL	8L
#define VAL_ifMauTypeListBits_b10broad36	9L
#define VAL_ifMauTypeListBits_b10baseTHD	10L
#define VAL_ifMauTypeListBits_b10baseTFD	11L
#define VAL_ifMauTypeListBits_b10baseFLHD	12L
#define VAL_ifMauTypeListBits_b10baseFLFD	13L
#define VAL_ifMauTypeListBits_b100baseT4	14L
#define VAL_ifMauTypeListBits_b100baseTXHD	15L
#define VAL_ifMauTypeListBits_b100baseTXFD	16L
#define VAL_ifMauTypeListBits_b100baseFXHD	17L
#define VAL_ifMauTypeListBits_b100baseFXFD	18L
#define VAL_ifMauTypeListBits_b100baseT2HD	19L
#define VAL_ifMauTypeListBits_b100baseT2FD	20L
#define VAL_ifMauTypeListBits_b1000baseXHD	21L
#define VAL_ifMauTypeListBits_b1000baseXFD	22L
#define VAL_ifMauTypeListBits_b1000baseLXHD	23L
#define VAL_ifMauTypeListBits_b1000baseLXFD	24L
#define VAL_ifMauTypeListBits_b1000baseSXHD	25L
#define VAL_ifMauTypeListBits_b1000baseSXFD	26L
#define VAL_ifMauTypeListBits_b1000baseCXHD	27L
#define VAL_ifMauTypeListBits_b1000baseCXFD	28L
#define VAL_ifMauTypeListBits_b1000baseTHD	29L
#define VAL_ifMauTypeListBits_b1000baseTFD	30L
#define VAL_ifMauTypeListBits_b10GbaseX	31L
#define VAL_ifMauTypeListBits_b10GbaseLX4	32L
#define VAL_ifMauTypeListBits_b10GbaseR	33L
#define VAL_ifMauTypeListBits_b10GbaseER	34L
#define VAL_ifMauTypeListBits_b10GbaseLR	35L
#define VAL_ifMauTypeListBits_b10GbaseSR	36L
#define VAL_ifMauTypeListBits_b10GbaseW	37L
#define VAL_ifMauTypeListBits_b10GbaseEW	38L
#define VAL_ifMauTypeListBits_b10GbaseLW	39L
#define VAL_ifMauTypeListBits_b10GbaseSW	40L
#define LEAF_ifMauHCFalseCarriers	14
#define LEAF_ifJackIndex	1
#define MIN_ifJackIndex	1L
#define MAX_ifJackIndex	2147483647L
#define LEAF_ifJackType	2
#define VAL_ifJackType_other	1L
#define VAL_ifJackType_rj45	2L
#define VAL_ifJackType_rj45S	3L
#define VAL_ifJackType_db9	4L
#define VAL_ifJackType_bnc	5L
#define VAL_ifJackType_fAUI	6L
#define VAL_ifJackType_mAUI	7L
#define VAL_ifJackType_fiberSC	8L
#define VAL_ifJackType_fiberMIC	9L
#define VAL_ifJackType_fiberST	10L
#define VAL_ifJackType_telco	11L
#define VAL_ifJackType_mtrj	12L
#define VAL_ifJackType_hssdc	13L
#define VAL_ifJackType_fiberLC	14L
#define LEAF_broadMauIfIndex	1
#define MIN_broadMauIfIndex	1L
#define MAX_broadMauIfIndex	2147483647L
#define LEAF_broadMauIndex	2
#define MIN_broadMauIndex	1L
#define MAX_broadMauIndex	2147483647L
#define LEAF_broadMauXmtRcvSplitType	3
#define VAL_broadMauXmtRcvSplitType_other	1L
#define VAL_broadMauXmtRcvSplitType_single	2L
#define VAL_broadMauXmtRcvSplitType_dual	3L
#define LEAF_broadMauXmtCarrierFreq	4
#define LEAF_broadMauTranslationFreq	5
#define LEAF_ifMauAutoNegAdminStatus	1
#define VAL_ifMauAutoNegAdminStatus_enabled	1L
#define VAL_ifMauAutoNegAdminStatus_disabled	2L
#define LEAF_ifMauAutoNegRemoteSignaling	2
#define VAL_ifMauAutoNegRemoteSignaling_detected	1L
#define VAL_ifMauAutoNegRemoteSignaling_notdetected	2L
#define LEAF_ifMauAutoNegConfig	4
#define VAL_ifMauAutoNegConfig_other	1L
#define VAL_ifMauAutoNegConfig_configuring	2L
#define VAL_ifMauAutoNegConfig_complete	3L
#define VAL_ifMauAutoNegConfig_disabled	4L
#define VAL_ifMauAutoNegConfig_parallelDetectFail	5L
#define LEAF_ifMauAutoNegCapability	5
#define LEAF_ifMauAutoNegCapAdvertised	6
#define LEAF_ifMauAutoNegCapReceived	7
#define LEAF_ifMauAutoNegRestart	8
#define VAL_ifMauAutoNegRestart_restart	1L
#define VAL_ifMauAutoNegRestart_norestart	2L
#define LEAF_ifMauAutoNegCapabilityBits	9
#define VAL_ifMauAutoNegCapabilityBits_bOther	0L
#define VAL_ifMauAutoNegCapabilityBits_b10baseT	1L
#define VAL_ifMauAutoNegCapabilityBits_b10baseTFD	2L
#define VAL_ifMauAutoNegCapabilityBits_b100baseT4	3L
#define VAL_ifMauAutoNegCapabilityBits_b100baseTX	4L
#define VAL_ifMauAutoNegCapabilityBits_b100baseTXFD	5L
#define VAL_ifMauAutoNegCapabilityBits_b100baseT2	6L
#define VAL_ifMauAutoNegCapabilityBits_b100baseT2FD	7L
#define VAL_ifMauAutoNegCapabilityBits_bfdxPause	8L
#define VAL_ifMauAutoNegCapabilityBits_bfdxAPause	9L
#define VAL_ifMauAutoNegCapabilityBits_bfdxSPause	10L
#define VAL_ifMauAutoNegCapabilityBits_bfdxBPause	11L
#define VAL_ifMauAutoNegCapabilityBits_b1000baseX	12L
#define VAL_ifMauAutoNegCapabilityBits_b1000baseXFD	13L
#define VAL_ifMauAutoNegCapabilityBits_b1000baseT	14L
#define VAL_ifMauAutoNegCapabilityBits_b1000baseTFD	15L
#define LEAF_ifMauAutoNegCapAdvertisedBits	10
#define VAL_ifMauAutoNegCapAdvertisedBits_bOther	0L
#define VAL_ifMauAutoNegCapAdvertisedBits_b10baseT	1L
#define VAL_ifMauAutoNegCapAdvertisedBits_b10baseTFD	2L
#define VAL_ifMauAutoNegCapAdvertisedBits_b100baseT4	3L
#define VAL_ifMauAutoNegCapAdvertisedBits_b100baseTX	4L
#define VAL_ifMauAutoNegCapAdvertisedBits_b100baseTXFD	5L
#define VAL_ifMauAutoNegCapAdvertisedBits_b100baseT2	6L
#define VAL_ifMauAutoNegCapAdvertisedBits_b100baseT2FD	7L
#define VAL_ifMauAutoNegCapAdvertisedBits_bFdxPause	8L
#define VAL_ifMauAutoNegCapAdvertisedBits_bFdxAPause	9L
#define VAL_ifMauAutoNegCapAdvertisedBits_bFdxSPause	10L
#define VAL_ifMauAutoNegCapAdvertisedBits_bFdxBPause	11L
#define VAL_ifMauAutoNegCapAdvertisedBits_b1000baseX	12L
#define VAL_ifMauAutoNegCapAdvertisedBits_b1000baseXFD	13L
#define VAL_ifMauAutoNegCapAdvertisedBits_b1000baseT	14L
#define VAL_ifMauAutoNegCapAdvertisedBits_b1000baseTFD	15L
#define LEAF_ifMauAutoNegCapReceivedBits	11
#define VAL_ifMauAutoNegCapReceivedBits_bOther	0L
#define VAL_ifMauAutoNegCapReceivedBits_b10baseT	1L
#define VAL_ifMauAutoNegCapReceivedBits_b10baseTFD	2L
#define VAL_ifMauAutoNegCapReceivedBits_b100baseT4	3L
#define VAL_ifMauAutoNegCapReceivedBits_b100baseTX	4L
#define VAL_ifMauAutoNegCapReceivedBits_b100baseTXFD	5L
#define VAL_ifMauAutoNegCapReceivedBits_b100baseT2	6L
#define VAL_ifMauAutoNegCapReceivedBits_b100baseT2FD	7L
#define VAL_ifMauAutoNegCapReceivedBits_bFdxPause	8L
#define VAL_ifMauAutoNegCapReceivedBits_bFdxAPause	9L
#define VAL_ifMauAutoNegCapReceivedBits_bFdxSPause	10L
#define VAL_ifMauAutoNegCapReceivedBits_bFdxBPause	11L
#define VAL_ifMauAutoNegCapReceivedBits_b1000baseX	12L
#define VAL_ifMauAutoNegCapReceivedBits_b1000baseXFD	13L
#define VAL_ifMauAutoNegCapReceivedBits_b1000baseT	14L
#define VAL_ifMauAutoNegCapReceivedBits_b1000baseTFD	15L
#define LEAF_ifMauAutoNegRemoteFaultAdvertised	12
#define VAL_ifMauAutoNegRemoteFaultAdvertised_noError	1L
#define VAL_ifMauAutoNegRemoteFaultAdvertised_offline	2L
#define VAL_ifMauAutoNegRemoteFaultAdvertised_linkFailure	3L
#define VAL_ifMauAutoNegRemoteFaultAdvertised_autoNegError	4L
#define LEAF_ifMauAutoNegRemoteFaultReceived	13
#define VAL_ifMauAutoNegRemoteFaultReceived_noError	1L
#define VAL_ifMauAutoNegRemoteFaultReceived_offline	2L
#define VAL_ifMauAutoNegRemoteFaultReceived_linkFailure	3L
#define VAL_ifMauAutoNegRemoteFaultReceived_autoNegError	4L

#endif /* end of #ifndef  LEAF_3636_H */

