#ifndef _LEAF_IEEELLDPEXT_H
#define _LEAF_IEEELLDPEXT_H

#define LEAF_lldpXdot1ConfigPortVlanTxEnable   1
#define VAL_lldpXdot1ConfigPortVlanTxEnable_true 1L
#define VAL_lldpXdot1ConfigPortVlanTxEnable_false 2L
#define LEAF_lldpXdot1ConfigVlanNameTxEnable   1
#define VAL_lldpXdot1ConfigVlanNameTxEnable_true 1L
#define VAL_lldpXdot1ConfigVlanNameTxEnable_false 2L
#define LEAF_lldpXdot1ConfigProtoVlanTxEnable   1
#define VAL_lldpXdot1ConfigProtoVlanTxEnable_true 1L
#define VAL_lldpXdot1ConfigProtoVlanTxEnable_false 2L
#define LEAF_lldpXdot1ConfigProtocolTxEnable   1
#define VAL_lldpXdot1ConfigProtocolTxEnable_true 1L
#define VAL_lldpXdot1ConfigProtocolTxEnable_false 2L
#define LEAF_lldpXdot1LocPortVlanId   1
#define MIN_lldpXdot1LocPortVlanId  1L
#define MAX_lldpXdot1LocPortVlanId  4094L
#define LEAF_lldpXdot1LocProtoVlanId   1
#define MIN_lldpXdot1LocProtoVlanId  1L
#define MAX_lldpXdot1LocProtoVlanId  4094L
#define LEAF_lldpXdot1LocProtoVlanSupported   2
#define VAL_lldpXdot1LocProtoVlanSupported_true 1L
#define VAL_lldpXdot1LocProtoVlanSupported_false 2L
#define LEAF_lldpXdot1LocProtoVlanEnabled   3
#define VAL_lldpXdot1LocProtoVlanEnabled_true 1L
#define VAL_lldpXdot1LocProtoVlanEnabled_false 2L
#define LEAF_lldpXdot1LocVlanId   1
#define MIN_lldpXdot1LocVlanId  1L
#define MAX_lldpXdot1LocVlanId  4094L
#define LEAF_lldpXdot1LocVlanName   2
#define MINSIZE_lldpXdot1LocVlanName  1L
#define MAXSIZE_lldpXdot1LocVlanName  32L
#define LEAF_lldpXdot1LocProtocolIndex   1
#define MIN_lldpXdot1LocProtocolIndex  1L
#define MAX_lldpXdot1LocProtocolIndex  2147483647L
#define LEAF_lldpXdot1LocProtocolId   2
#define MINSIZE_lldpXdot1LocProtocolId  1L
#define MAXSIZE_lldpXdot1LocProtocolId  255L
#define LEAF_lldpXdot1RemPortVlanId   1
#define MIN_lldpXdot1RemPortVlanId  1L
#define MAX_lldpXdot1RemPortVlanId  4094L
#define LEAF_lldpXdot1RemProtoVlanId   1
#define MIN_lldpXdot1RemProtoVlanId  1L
#define MAX_lldpXdot1RemProtoVlanId  4094L
#define LEAF_lldpXdot1RemProtoVlanSupported   2
#define VAL_lldpXdot1RemProtoVlanSupported_true 1L
#define VAL_lldpXdot1RemProtoVlanSupported_false 2L
#define LEAF_lldpXdot1RemProtoVlanEnabled   3
#define VAL_lldpXdot1RemProtoVlanEnabled_true 1L
#define VAL_lldpXdot1RemProtoVlanEnabled_false 2L
#define LEAF_lldpXdot1RemVlanId   1
#define MIN_lldpXdot1RemVlanId  1L
#define MAX_lldpXdot1RemVlanId  4094L
#define LEAF_lldpXdot1RemVlanName   2
#define MINSIZE_lldpXdot1RemVlanName  1L
#define MAXSIZE_lldpXdot1RemVlanName  32L
#define LEAF_lldpXdot1RemProtocolIndex   1
#define MIN_lldpXdot1RemProtocolIndex  1L
#define MAX_lldpXdot1RemProtocolIndex  2147483647L
#define LEAF_lldpXdot1RemProtocolId   2
#define MINSIZE_lldpXdot1RemProtocolId  1L
#define MAXSIZE_lldpXdot1RemProtocolId  255L

#if 0 /* Already move to Leaf_ieee8021ab_ext_dot3.h */
#define LEAF_lldpXdot3PortConfigTLVsTxEnable   1
#define VAL_lldpXdot3PortConfigTLVsTxEnable_macPhyConfigStatus 0L
#define VAL_lldpXdot3PortConfigTLVsTxEnable_powerViaMDI 1L
#define VAL_lldpXdot3PortConfigTLVsTxEnable_linkAggregation 2L
#define VAL_lldpXdot3PortConfigTLVsTxEnable_maxFrameSize 3L
#define SIZE_lldpXdot3PortConfigTLVsTxEnable    1L
#define LEAF_lldpXdot3LocPortAutoNegSupported   1
#define VAL_lldpXdot3LocPortAutoNegSupported_true 1L
#define VAL_lldpXdot3LocPortAutoNegSupported_false 2L
#define LEAF_lldpXdot3LocPortAutoNegEnabled   2
#define VAL_lldpXdot3LocPortAutoNegEnabled_true 1L
#define VAL_lldpXdot3LocPortAutoNegEnabled_false 2L
#define LEAF_lldpXdot3LocPortAutoNegAdvertisedCap   3
#define SIZE_lldpXdot3LocPortAutoNegAdvertisedCap 2L
#define LEAF_lldpXdot3LocPortOperMauType   4
#define MIN_lldpXdot3LocPortOperMauType  0L
#define MAX_lldpXdot3LocPortOperMauType  2147483647L
#define LEAF_lldpXdot3LocPowerPortClass   1
#define VAL_lldpXdot3LocPowerPortClass_pClassPSE 1L
#define VAL_lldpXdot3LocPowerPortClass_pClassPD 2L
#define LEAF_lldpXdot3LocPowerMDISupported   2
#define VAL_lldpXdot3LocPowerMDISupported_true 1L
#define VAL_lldpXdot3LocPowerMDISupported_false 2L
#define LEAF_lldpXdot3LocPowerMDIEnabled   3
#define VAL_lldpXdot3LocPowerMDIEnabled_true 1L
#define VAL_lldpXdot3LocPowerMDIEnabled_false 2L
#define LEAF_lldpXdot3LocPowerPairControlable   4
#define VAL_lldpXdot3LocPowerPairControlable_true 1L
#define VAL_lldpXdot3LocPowerPairControlable_false 2L
#define LEAF_lldpXdot3LocPowerPairs   5
#define MIN_lldpXdot3LocPowerPairs  1L
#define MAX_lldpXdot3LocPowerPairs  2L
#define LEAF_lldpXdot3LocPowerClass   6
#define MIN_lldpXdot3LocPowerClass  1L
#define MAX_lldpXdot3LocPowerClass  5L
#define LEAF_lldpXdot3LocLinkAggStatus   1
#define VAL_lldpXdot3LocLinkAggStatus_aggCapable 0L
#define VAL_lldpXdot3LocLinkAggStatus_aggEnabled 1L
#define SIZE_lldpXdot3LocLinkAggStatus    1L
#define LEAF_lldpXdot3LocLinkAggPortId   2
#define MIN_lldpXdot3LocLinkAggPortId  1L
#define MAX_lldpXdot3LocLinkAggPortId  2147483647L
#define LEAF_lldpXdot3LocMaxFrameSize   1
#define MIN_lldpXdot3LocMaxFrameSize  0L
#define MAX_lldpXdot3LocMaxFrameSize  65535L
#define LEAF_lldpXdot3RemPortAutoNegSupported   1
#define VAL_lldpXdot3RemPortAutoNegSupported_true 1L
#define VAL_lldpXdot3RemPortAutoNegSupported_false 2L
#define LEAF_lldpXdot3RemPortAutoNegEnabled   2
#define VAL_lldpXdot3RemPortAutoNegEnabled_true 1L
#define VAL_lldpXdot3RemPortAutoNegEnabled_false 2L
#define LEAF_lldpXdot3RemPortAutoNegAdvertisedCap   3
#define SIZE_lldpXdot3RemPortAutoNegAdvertisedCap 2L
#define LEAF_lldpXdot3RemPortOperMauType   4
#define MIN_lldpXdot3RemPortOperMauType  0L
#define MAX_lldpXdot3RemPortOperMauType  2147483647L
#define LEAF_lldpXdot3RemPowerPortClass   1
#define VAL_lldpXdot3RemPowerPortClass_pClassPSE 1L
#define VAL_lldpXdot3RemPowerPortClass_pClassPD 2L
#define LEAF_lldpXdot3RemPowerMDISupported   2
#define VAL_lldpXdot3RemPowerMDISupported_true 1L
#define VAL_lldpXdot3RemPowerMDISupported_false 2L
#define LEAF_lldpXdot3RemPowerMDIEnabled   3
#define VAL_lldpXdot3RemPowerMDIEnabled_true 1L
#define VAL_lldpXdot3RemPowerMDIEnabled_false 2L
#define LEAF_lldpXdot3RemPowerPairControlable   4
#define VAL_lldpXdot3RemPowerPairControlable_true 1L
#define VAL_lldpXdot3RemPowerPairControlable_false 2L
#define LEAF_lldpXdot3RemPowerPairs   5
#define MIN_lldpXdot3RemPowerPairs  1L
#define MAX_lldpXdot3RemPowerPairs  2L
#define LEAF_lldpXdot3RemPowerClass   6
#define MIN_lldpXdot3RemPowerClass  1L
#define MAX_lldpXdot3RemPowerClass  5L
#define LEAF_lldpXdot3RemLinkAggStatus   1
#define VAL_lldpXdot3RemLinkAggStatus_aggCapable 0L
#define VAL_lldpXdot3RemLinkAggStatus_aggEnabled 1L
#define SIZE_lldpXdot3RemLinkAggStatus    1L
#define LEAF_lldpXdot3RemLinkAggPortId   2
#define MIN_lldpXdot3RemLinkAggPortId  1L
#define MAX_lldpXdot3RemLinkAggPortId  2147483647L
#define LEAF_lldpXdot3RemMaxFrameSize   1
#define MIN_lldpXdot3RemMaxFrameSize  0L
#define MAX_lldpXdot3RemMaxFrameSize  65535L
#endif

#endif

