/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_2620_H
#define  LEAF_2620_H

#define LEAF_radiusAccClientInvalidServerAddresses   1
#define LEAF_radiusAccClientIdentifier   2
#define MINSIZE_radiusAccClientIdentifier  0L
#define MAXSIZE_radiusAccClientIdentifier  255L
#define LEAF_radiusAccServerIndex   1
#define MIN_radiusAccServerIndex  1L
#define MAX_radiusAccServerIndex  2147483647L
#define LEAF_radiusAccServerAddress   2
#define LEAF_radiusAccClientServerPortNumber   3
#define MIN_radiusAccClientServerPortNumber  0L
#define MAX_radiusAccClientServerPortNumber  65535L
#define LEAF_radiusAccClientRoundTripTime   4
#define LEAF_radiusAccClientRequests   5
#define LEAF_radiusAccClientRetransmissions   6
#define LEAF_radiusAccClientResponses   7
#define LEAF_radiusAccClientMalformedResponses   8
#define LEAF_radiusAccClientBadAuthenticators   9
#define LEAF_radiusAccClientPendingRequests   10
#define LEAF_radiusAccClientTimeouts   11
#define LEAF_radiusAccClientUnknownTypes   12
#define LEAF_radiusAccClientPacketsDropped   13

#endif /* end of #ifndef  LEAF_2620_H */


