/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Wed Jan  9 15:33:53 2002
 **** from files:
 ****  Rfc2271-SNMP-FRAMEWORK.mib, Rfc2737-ENTITY.mib, rfc2737.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_2737_H
#define  LEAF_2737_H

#define LEAF_entPhysicalIndex	1
#define MIN_entPhysicalIndex	1L
#define MAX_entPhysicalIndex	2147483647L
#define LEAF_entPhysicalDescr	2
#define MINSIZE_entPhysicalDescr	0L
#define MAXSIZE_entPhysicalDescr	255L
#define LEAF_entPhysicalVendorType	3
#define LEAF_entPhysicalContainedIn	4
#define MIN_entPhysicalContainedIn	0L
#define MAX_entPhysicalContainedIn	2147483647L
#define LEAF_entPhysicalClass	5
#define VAL_entPhysicalClass_other	1L
#define VAL_entPhysicalClass_unknown	2L
#define VAL_entPhysicalClass_chassis	3L
#define VAL_entPhysicalClass_backplane	4L
#define VAL_entPhysicalClass_container	5L
#define VAL_entPhysicalClass_powerSupply	6L
#define VAL_entPhysicalClass_fan	7L
#define VAL_entPhysicalClass_sensor	8L
#define VAL_entPhysicalClass_module	9L
#define VAL_entPhysicalClass_port	10L
#define VAL_entPhysicalClass_stack	11L
#define LEAF_entPhysicalParentRelPos	6
#define MIN_entPhysicalParentRelPos	-1L
#define MAX_entPhysicalParentRelPos	2147483647L
#define LEAF_entPhysicalName	7
#define MINSIZE_entPhysicalName	0L
#define MAXSIZE_entPhysicalName	255L
#define LEAF_entPhysicalHardwareRev	8
#define MINSIZE_entPhysicalHardwareRev	0L
#define MAXSIZE_entPhysicalHardwareRev	255L
#define LEAF_entPhysicalFirmwareRev	9
#define MINSIZE_entPhysicalFirmwareRev	0L
#define MAXSIZE_entPhysicalFirmwareRev	255L
#define LEAF_entPhysicalSoftwareRev	10
#define MINSIZE_entPhysicalSoftwareRev	0L
#define MAXSIZE_entPhysicalSoftwareRev	255L
#define LEAF_entPhysicalSerialNum	11
#define MINSIZE_entPhysicalSerialNum	0L
#define MAXSIZE_entPhysicalSerialNum	32L
#define LEAF_entPhysicalMfgName	12
#define MINSIZE_entPhysicalMfgName	0L
#define MAXSIZE_entPhysicalMfgName	255L
#define LEAF_entPhysicalModelName	13
#define MINSIZE_entPhysicalModelName	0L
#define MAXSIZE_entPhysicalModelName	255L
#define LEAF_entPhysicalAlias	14
#define MINSIZE_entPhysicalAlias	0L
#define MAXSIZE_entPhysicalAlias	32L
#define LEAF_entPhysicalAssetID	15
#define MINSIZE_entPhysicalAssetID	0L
#define MAXSIZE_entPhysicalAssetID	32L
#define LEAF_entPhysicalIsFRU	16
#define VAL_entPhysicalIsFRU_true	1L
#define VAL_entPhysicalIsFRU_false	2L

#endif /* end of #ifndef  LEAF_2737_H */
