/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 21:43:26 2001
 **** from files:
 ****  Rfc2271-SNMP-FRAMEWORK.mib, Rfc2742-AGENTX.mib, rfc2742.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_2742_H
#define  LEAF_2742_H

#define LEAF_agentxDefaultTimeout	1
#define MIN_agentxDefaultTimeout	0L
#define MAX_agentxDefaultTimeout	255L
#define LEAF_agentxMasterAgentXVer	2
#define MIN_agentxMasterAgentXVer	1L
#define MAX_agentxMasterAgentXVer	255L
#define LEAF_agentxConnTableLastChange	1
#define LEAF_agentxConnIndex	1
#define MIN_agentxConnIndex	1L
#define MAX_agentxConnIndex	4294967295L
#define LEAF_agentxConnOpenTime	2
#define LEAF_agentxConnTransportDomain	3
#define LEAF_agentxConnTransportAddress	4
#define MINSIZE_agentxConnTransportAddress	0L
#define MAXSIZE_agentxConnTransportAddress	255L
#define LEAF_agentxSessionTableLastChange	1
#define LEAF_agentxSessionIndex	1
#define MIN_agentxSessionIndex	0L
#define MAX_agentxSessionIndex	4294967295L
#define LEAF_agentxSessionObjectID	2
#define LEAF_agentxSessionDescr	3
#define MINSIZE_agentxSessionDescr	0L
#define MAXSIZE_agentxSessionDescr	255L
#define LEAF_agentxSessionAdminStatus	4
#define VAL_agentxSessionAdminStatus_up	1L
#define VAL_agentxSessionAdminStatus_down	2L
#define LEAF_agentxSessionOpenTime	5
#define LEAF_agentxSessionAgentXVer	6
#define MIN_agentxSessionAgentXVer	1L
#define MAX_agentxSessionAgentXVer	255L
#define LEAF_agentxSessionTimeout	7
#define MIN_agentxSessionTimeout	0L
#define MAX_agentxSessionTimeout	255L
#define LEAF_agentxRegistrationTableLastChange	1
#define LEAF_agentxRegIndex	1
#define MIN_agentxRegIndex	1L
#define MAX_agentxRegIndex	4294967295L
#define LEAF_agentxRegContext	2
#define LEAF_agentxRegStart	3
#define LEAF_agentxRegRangeSubId	4
#define LEAF_agentxRegUpperBound	5
#define LEAF_agentxRegPriority	6
#define LEAF_agentxRegTimeout	7
#define MIN_agentxRegTimeout	0L
#define MAX_agentxRegTimeout	255L
#define LEAF_agentxRegInstance	8
#define VAL_agentxRegInstance_true	1L
#define VAL_agentxRegInstance_false	2L

#endif /* end of #ifndef  LEAF_2742_H */
