/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Epilogue Technology's
 **** Emissary SNMP MIB Compiler, version 6.3.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Nov  9 21:36:24 2001
 **** from files:
 ****  Rfc1213.mib, Rfc1493-BRIDGE.mib, Rfc2674-P-BRIDGE.mib,
 ****  Rfc1757-RMON-MIB.mib, E-Rfc1513-TOKEN-RING-RMON.mib, Rfc2021-RMON2.mib,
 ****  Rfc2271-SNMP-FRAMEWORK.mib, Rfc2674-Q-BRIDGE.mib, rfc2674q.ctl
 ******************************************************************************
 ******************************************************************************
 */
#ifndef  LEAF_2674Q_H
#define  LEAF_2674Q_H

#define LEAF_dot1qVlanVersionNumber	1
#define VAL_dot1qVlanVersionNumber_version1	1L
#define LEAF_dot1qMaxVlanId	2
#define MIN_dot1qMaxVlanId	1L
#define MAX_dot1qMaxVlanId	4094L
#define LEAF_dot1qMaxSupportedVlans	3
#define LEAF_dot1qNumVlans	4
#define LEAF_dot1qGvrpStatus	5
#define VAL_dot1qGvrpStatus_enabled	1L
#define VAL_dot1qGvrpStatus_disabled	2L
#define LEAF_dot1qFdbId	1
#define LEAF_dot1qFdbDynamicCount	2
#define LEAF_dot1qTpFdbAddress	1
#define SIZE_dot1qTpFdbAddress	6L
#define LEAF_dot1qTpFdbPort	2
#define MIN_dot1qTpFdbPort	0L
#define MAX_dot1qTpFdbPort	65535L
#define LEAF_dot1qTpFdbStatus	3
#define VAL_dot1qTpFdbStatus_other	1L
#define VAL_dot1qTpFdbStatus_invalid	2L
#define VAL_dot1qTpFdbStatus_learned	3L
#define VAL_dot1qTpFdbStatus_self	4L
#define VAL_dot1qTpFdbStatus_mgmt	5L
#define LEAF_dot1qTpGroupAddress	1
#define SIZE_dot1qTpGroupAddress	6L
#define LEAF_dot1qTpGroupEgressPorts	2
#define LEAF_dot1qTpGroupLearnt	3
#define LEAF_dot1qForwardAllPorts	1
#define LEAF_dot1qForwardAllStaticPorts	2
#define LEAF_dot1qForwardAllForbiddenPorts	3
#define LEAF_dot1qForwardUnregisteredPorts	1
#define LEAF_dot1qForwardUnregisteredStaticPorts	2
#define LEAF_dot1qForwardUnregisteredForbiddenPorts	3
#define LEAF_dot1qStaticUnicastAddress	1
#define SIZE_dot1qStaticUnicastAddress	6L
#define LEAF_dot1qStaticUnicastReceivePort	2
#define MIN_dot1qStaticUnicastReceivePort	0L
#define MAX_dot1qStaticUnicastReceivePort	65535L
#define LEAF_dot1qStaticUnicastAllowedToGoTo	3
#define LEAF_dot1qStaticUnicastStatus	4
#define VAL_dot1qStaticUnicastStatus_other	1L
#define VAL_dot1qStaticUnicastStatus_invalid	2L
#define VAL_dot1qStaticUnicastStatus_permanent	3L
#define VAL_dot1qStaticUnicastStatus_deleteOnReset	4L
#define VAL_dot1qStaticUnicastStatus_deleteOnTimeout	5L
#define LEAF_dot1qStaticMulticastAddress	1
#define SIZE_dot1qStaticMulticastAddress	6L
#define LEAF_dot1qStaticMulticastReceivePort	2
#define MIN_dot1qStaticMulticastReceivePort	0L
#define MAX_dot1qStaticMulticastReceivePort	65535L
#define LEAF_dot1qStaticMulticastStaticEgressPorts	3
#define LEAF_dot1qStaticMulticastForbiddenEgressPorts	4
#define LEAF_dot1qStaticMulticastStatus	5
#define VAL_dot1qStaticMulticastStatus_other	1L
#define VAL_dot1qStaticMulticastStatus_invalid	2L
#define VAL_dot1qStaticMulticastStatus_permanent	3L
#define VAL_dot1qStaticMulticastStatus_deleteOnReset	4L
#define VAL_dot1qStaticMulticastStatus_deleteOnTimeout	5L
#define LEAF_dot1qVlanNumDeletes	1
#define LEAF_dot1qVlanTimeMark	1
#define LEAF_dot1qVlanIndex	2
#define LEAF_dot1qVlanFdbId	3
#define LEAF_dot1qVlanCurrentEgressPorts	4
#define LEAF_dot1qVlanCurrentUntaggedPorts	5
#define LEAF_dot1qVlanStatus	6
#define VAL_dot1qVlanStatus_other	1L
#define VAL_dot1qVlanStatus_permanent	2L
#define VAL_dot1qVlanStatus_dynamicGvrp	3L
#define LEAF_dot1qVlanCreationTime	7
#define LEAF_dot1qVlanStaticName	1
#define MINSIZE_dot1qVlanStaticName	0L
#define MAXSIZE_dot1qVlanStaticName	32L
#define LEAF_dot1qVlanStaticEgressPorts	2
#define LEAF_dot1qVlanForbiddenEgressPorts	3
#define LEAF_dot1qVlanStaticUntaggedPorts	4
#define LEAF_dot1qVlanStaticRowStatus	5
#define VAL_dot1qVlanStaticRowStatus_active	1L
#define VAL_dot1qVlanStaticRowStatus_notInService	2L
#define VAL_dot1qVlanStaticRowStatus_notReady	3L
#define VAL_dot1qVlanStaticRowStatus_createAndGo	4L
#define VAL_dot1qVlanStaticRowStatus_createAndWait	5L
#define VAL_dot1qVlanStaticRowStatus_destroy	6L
#define LEAF_dot1qNextFreeLocalVlanIndex	4
#define MIN_dot1qNextFreeLocalVlanIndex_1	0L
#define MAX_dot1qNextFreeLocalVlanIndex_1	0L
#define MIN_dot1qNextFreeLocalVlanIndex_2	4096L
#define MAX_dot1qNextFreeLocalVlanIndex_2	2147483647L
#define LEAF_dot1qPvid	1
#define LEAF_dot1qPortAcceptableFrameTypes	2
#define VAL_dot1qPortAcceptableFrameTypes_admitAll	1L
#define VAL_dot1qPortAcceptableFrameTypes_admitOnlyVlanTagged	2L
#define LEAF_dot1qPortIngressFiltering	3
#define VAL_dot1qPortIngressFiltering_true	1L
#define VAL_dot1qPortIngressFiltering_false	2L
#define LEAF_dot1qPortGvrpStatus	4
#define VAL_dot1qPortGvrpStatus_enabled	1L
#define VAL_dot1qPortGvrpStatus_disabled	2L
#define LEAF_dot1qPortGvrpFailedRegistrations	5
#define LEAF_dot1qPortGvrpLastPduOrigin	6
#define SIZE_dot1qPortGvrpLastPduOrigin	6L
#define LEAF_dot1qTpVlanPortInFrames	1
#define LEAF_dot1qTpVlanPortOutFrames	2
#define LEAF_dot1qTpVlanPortInDiscards	3
#define LEAF_dot1qTpVlanPortInOverflowFrames	4
#define LEAF_dot1qTpVlanPortOutOverflowFrames	5
#define LEAF_dot1qTpVlanPortInOverflowDiscards	6
#define LEAF_dot1qTpVlanPortHCInFrames	1
#define LEAF_dot1qTpVlanPortHCOutFrames	2
#define LEAF_dot1qTpVlanPortHCInDiscards	3
#define LEAF_dot1qConstraintVlan	1
#define LEAF_dot1qConstraintSet	2
#define MIN_dot1qConstraintSet	0L
#define MAX_dot1qConstraintSet	65535L
#define LEAF_dot1qConstraintType	3
#define VAL_dot1qConstraintType_independent	1L
#define VAL_dot1qConstraintType_shared	2L
#define LEAF_dot1qConstraintStatus	4
#define VAL_dot1qConstraintStatus_active	1L
#define VAL_dot1qConstraintStatus_notInService	2L
#define VAL_dot1qConstraintStatus_notReady	3L
#define VAL_dot1qConstraintStatus_createAndGo	4L
#define VAL_dot1qConstraintStatus_createAndWait	5L
#define VAL_dot1qConstraintStatus_destroy	6L
#define LEAF_dot1qConstraintSetDefault	9
#define MIN_dot1qConstraintSetDefault	0L
#define MAX_dot1qConstraintSetDefault	65535L
#define LEAF_dot1qConstraintTypeDefault	10
#define VAL_dot1qConstraintTypeDefault_independent	1L
#define VAL_dot1qConstraintTypeDefault_shared	2L

#endif /* end of #ifndef  LEAF_2674Q_H */
