/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: esw_dispatch.h,v 1.136.2.23 Broadcom SDK $
 * $Copyright: Copyright 2008 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * File:	esw_dispatch.h
 * Purpose:	esw driver BCM API dispatch table
 * Generator:	mkdispatch 1.28
 * Generated:	Wed Feb 27 14:42:42 2008
 */

#ifndef	_BCM_INT_ESW_DISPATCH_H
#define	_BCM_INT_ESW_DISPATCH_H

#include <bcm/types.h>
#include <bcm_int/dispatch.h>

#ifdef	BCM_ESW_SUPPORT

extern int _bcm_esw_attach(int,char *);
extern int _bcm_esw_detach(int);
/* _bcm_shutdown not dispatchable */
/* bcm_attach not dispatchable */
/* bcm_attach_check not dispatchable */
/* bcm_attach_max not dispatchable */
extern int bcm_esw_auth_detach(int);
extern int bcm_esw_auth_egress_get(int,int,int *);
extern int bcm_esw_auth_egress_set(int,int,int);
extern int bcm_esw_auth_init(int);
extern int bcm_esw_auth_mac_add(int,int,bcm_mac_t);
extern int bcm_esw_auth_mac_delete(int,int,bcm_mac_t);
extern int bcm_esw_auth_mac_delete_all(int,int);
extern int bcm_esw_auth_mode_get(int,int,uint32 *);
extern int bcm_esw_auth_mode_set(int,int,uint32);
extern int bcm_esw_auth_unauth_callback(int,bcm_auth_cb_t,void *);
extern int bcm_esw_clear(int);
extern int bcm_esw_cosq_config_get(int,int *);
extern int bcm_esw_cosq_config_set(int,int);
extern int bcm_esw_cosq_control_get(int,bcm_gport_t,bcm_cos_queue_t,bcm_cosq_control_t,int *);
extern int bcm_esw_cosq_control_set(int,bcm_gport_t,bcm_cos_queue_t,bcm_cosq_control_t,int);
extern int bcm_esw_cosq_detach(int);
extern int bcm_esw_cosq_discard_get(int,uint32 *);
extern int bcm_esw_cosq_discard_port_get(int,bcm_port_t,bcm_cos_queue_t,uint32,int *,int *,int *);
extern int bcm_esw_cosq_discard_port_set(int,bcm_port_t,bcm_cos_queue_t,uint32,int,int,int);
extern int bcm_esw_cosq_discard_set(int,uint32);
/* bcm_cosq_fabric_distribution_add mapped to bcm_e_unavail */
/* bcm_cosq_fabric_distribution_get mapped to bcm_e_unavail */
extern int bcm_esw_cosq_gport_add(int,bcm_gport_t,int,uint32,bcm_gport_t *);
extern int bcm_esw_cosq_gport_attach(int,bcm_gport_t,bcm_gport_t,bcm_cos_queue_t);
extern int bcm_esw_cosq_gport_attach_get(int,bcm_gport_t,bcm_gport_t *,bcm_cos_queue_t *);
extern int bcm_esw_cosq_gport_bandwidth_get(int,bcm_gport_t,bcm_cos_queue_t,uint32 *,uint32 *,uint32 *);
extern int bcm_esw_cosq_gport_bandwidth_set(int,bcm_gport_t,bcm_cos_queue_t,uint32,uint32,uint32);
extern int bcm_esw_cosq_gport_delete(int,bcm_gport_t);
extern int bcm_esw_cosq_gport_detach(int,bcm_gport_t,bcm_gport_t,bcm_cos_queue_t);
extern int bcm_esw_cosq_gport_discard_get(int,bcm_gport_t,bcm_cos_queue_t,bcm_cosq_gport_discard_t *);
extern int bcm_esw_cosq_gport_discard_set(int,bcm_gport_t,bcm_cos_queue_t,bcm_cosq_gport_discard_t *);
/* bcm_cosq_gport_discard_t_init not dispatchable */
extern int bcm_esw_cosq_gport_enable_get(int,bcm_gport_t,bcm_cos_queue_t,int *);
extern int bcm_esw_cosq_gport_enable_set(int,bcm_gport_t,bcm_cos_queue_t,int);
extern int bcm_esw_cosq_gport_get(int,bcm_gport_t,bcm_gport_t *,int *,uint32 *);
extern int bcm_esw_cosq_gport_mapping_get(int,bcm_gport_t,bcm_cos_t,bcm_cos_queue_t *);
extern int bcm_esw_cosq_gport_mapping_set(int,bcm_gport_t,bcm_cos_t,bcm_cos_queue_t);
extern int bcm_esw_cosq_gport_nexus_attach(int,bcm_gport_t,bcm_cos_queue_t,bcm_gport_t,bcm_cos_queue_t);
extern int bcm_esw_cosq_gport_nexus_detach(int,bcm_gport_t,bcm_cos_queue_t,bcm_gport_t,bcm_cos_queue_t);
extern int bcm_esw_cosq_gport_sched_get(int,bcm_gport_t,bcm_cos_queue_t,int *,int *);
extern int bcm_esw_cosq_gport_sched_set(int,bcm_gport_t,bcm_cos_queue_t,int,int);
extern int bcm_esw_cosq_gport_size_get(int,bcm_gport_t,bcm_cos_queue_t,uint32 *,uint32 *);
extern int bcm_esw_cosq_gport_size_set(int,bcm_gport_t,bcm_cos_queue_t,uint32,uint32);
extern int bcm_esw_cosq_gport_stat_enable_get(int,bcm_gport_t,int *);
extern int bcm_esw_cosq_gport_stat_enable_set(int,bcm_gport_t,int);
extern int bcm_esw_cosq_gport_stat_get(int,bcm_gport_t,bcm_cos_queue_t,bcm_cosq_gport_stats_t,uint64 *);
extern int bcm_esw_cosq_gport_stat_set(int,bcm_gport_t,bcm_cos_queue_t,bcm_cosq_gport_stats_t,uint64);
extern int bcm_esw_cosq_gport_traverse(int,bcm_cosq_gport_traverse_cb,void *);
extern int bcm_esw_cosq_init(int);
extern int bcm_esw_cosq_mapping_get(int,bcm_cos_t,bcm_cos_queue_t *);
extern int bcm_esw_cosq_mapping_set(int,bcm_cos_t,bcm_cos_queue_t);
extern int bcm_esw_cosq_port_bandwidth_get(int,bcm_port_t,bcm_cos_queue_t,uint32 *,uint32 *,uint32 *);
extern int bcm_esw_cosq_port_bandwidth_set(int,bcm_port_t,bcm_cos_queue_t,uint32,uint32,uint32);
extern int bcm_esw_cosq_port_mapping_get(int,bcm_port_t,bcm_cos_t,bcm_cos_queue_t *);
extern int bcm_esw_cosq_port_mapping_set(int,bcm_port_t,bcm_cos_t,bcm_cos_queue_t);
extern int bcm_esw_cosq_port_sched_get(int,bcm_pbmp_t,int *,int [BCM_COS_COUNT],int *);
extern int bcm_esw_cosq_port_sched_set(int,bcm_pbmp_t,int,const int [BCM_COS_COUNT],int);
extern int bcm_esw_cosq_sched_get(int,int *,int [BCM_COS_COUNT],int *);
extern int bcm_esw_cosq_sched_set(int,int,const int [BCM_COS_COUNT],int);
extern int bcm_esw_cosq_sched_weight_max_get(int,int,int *);
extern int bcm_common_custom_port_get(int,bcm_port_t,int,uint32 [BCM_CUSTOM_ARGS_MAX]);
extern int bcm_common_custom_port_set(int,bcm_port_t,int,uint32 [BCM_CUSTOM_ARGS_MAX]);
extern int bcm_common_custom_register(int,bcm_custom_cb_t);
extern int bcm_common_custom_unregister(int);
/* bcm_detach not dispatchable */
extern int bcm_esw_dmux_config_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_dmux_config_set(int,bcm_port_t,uint32);
extern int bcm_esw_dmux_dest_add(int,bcm_port_t,int,bcm_port_t);
extern int bcm_esw_dmux_dest_delete(int,bcm_port_t,int,bcm_port_t);
extern int bcm_esw_dmux_dest_delete_all(int,bcm_port_t);
extern int bcm_esw_dmux_dest_get(int,bcm_port_t,int,bcm_pbmp_t *);
extern int bcm_esw_dmux_detach(int);
extern int bcm_esw_dmux_init(int);
extern int bcm_esw_ds_classifier_create(int,int,bcm_ds_clfr_t *,bcm_ds_inprofile_actn_t *,bcm_ds_outprofile_actn_t *,bcm_ds_nomatch_actn_t *,int *);
extern int bcm_esw_ds_classifier_create_id(int,int,bcm_ds_clfr_t *,bcm_ds_inprofile_actn_t *,bcm_ds_outprofile_actn_t *,bcm_ds_nomatch_actn_t *,int);
extern int bcm_esw_ds_classifier_delete(int,int,int);
extern int bcm_esw_ds_classifier_get(int,int,int,bcm_ds_clfr_t *,bcm_ds_inprofile_actn_t *,bcm_ds_outprofile_actn_t *,bcm_ds_nomatch_actn_t *);
extern int bcm_esw_ds_classifier_traverse(int,int,bcm_ds_classifier_traverse_cb,void *);
extern int bcm_esw_ds_classifier_update(int,int,int,uint32,bcm_ds_inprofile_actn_t *,bcm_ds_outprofile_actn_t *);
/* bcm_ds_clfr_t_init not dispatchable */
extern int bcm_esw_ds_counter_get(int,int,int,bcm_ds_counters_t *);
/* bcm_ds_counters_t_init not dispatchable */
extern int bcm_esw_ds_datapath_create(int,uint32,bcm_pbmp_t,int *);
extern int bcm_esw_ds_datapath_create_id(int,uint32,bcm_pbmp_t,int);
extern int bcm_esw_ds_datapath_delete(int,int);
extern int bcm_esw_ds_datapath_install(int,int);
extern int bcm_esw_ds_dpid_cfid_bind(int,void *,int,int);
extern int bcm_esw_ds_dpid_cfid_get(int,void *,int,int *);
extern int bcm_esw_ds_dpid_cfid_unbind(int,void *,int,int);
extern int bcm_esw_ds_init(int);
/* bcm_ds_inprofile_actn_t_init not dispatchable */
/* bcm_ds_nomatch_actn_t_init not dispatchable */
/* bcm_ds_outprofile_actn_t_init not dispatchable */
extern int bcm_esw_ds_scheduler_add(int,int,bcm_ds_scheduler_t *);
/* bcm_ds_scheduler_t_init not dispatchable */
extern int bcm_esw_eav_bandwidth_get(int,bcm_port_t,bcm_eav_stream_class_t,uint32 *,uint32 *);
extern int bcm_esw_eav_bandwidth_set(int,bcm_port_t,bcm_eav_stream_class_t,uint32,uint32);
extern int bcm_esw_eav_control_get(int,bcm_eav_control_t,uint32 *,uint32 *);
extern int bcm_esw_eav_control_set(int,bcm_eav_control_t,uint32,uint32);
extern int bcm_esw_eav_init(int);
extern int bcm_esw_eav_link_status_get(int,bcm_port_t,int *);
extern int bcm_esw_eav_link_status_set(int,bcm_port_t,int);
extern int bcm_esw_eav_pcp_mapping_get(int,bcm_eav_stream_class_t,int *,int *);
extern int bcm_esw_eav_pcp_mapping_set(int,bcm_eav_stream_class_t,int,int);
extern int bcm_esw_eav_port_enable_get(int,bcm_port_t,int *);
extern int bcm_esw_eav_port_enable_set(int,bcm_port_t,int);
extern int bcm_esw_eav_srp_mac_ethertype_get(int,bcm_mac_t,bcm_port_ethertype_t *);
extern int bcm_esw_eav_srp_mac_ethertype_set(int,bcm_mac_t,bcm_port_ethertype_t);
extern int bcm_esw_eav_timestamp_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_eav_timesync_mac_get(int,bcm_mac_t);
extern int bcm_esw_eav_timesync_mac_set(int,bcm_mac_t);
/* bcm_fabric_control_get mapped to bcm_e_unavail */
/* bcm_fabric_control_redundancy_register mapped to bcm_e_unavail */
/* bcm_fabric_control_redundancy_unregister mapped to bcm_e_unavail */
/* bcm_fabric_control_set mapped to bcm_e_unavail */
/* bcm_fabric_crossbar_connection_get mapped to bcm_e_unavail */
/* bcm_fabric_crossbar_connection_set mapped to bcm_e_unavail */
/* bcm_fabric_crossbar_enable_get mapped to bcm_e_unavail */
/* bcm_fabric_crossbar_enable_set mapped to bcm_e_unavail */
/* bcm_fabric_crossbar_mapping_get mapped to bcm_e_unavail */
/* bcm_fabric_crossbar_mapping_set mapped to bcm_e_unavail */
/* bcm_fabric_crossbar_status_get mapped to bcm_e_unavail */
/* bcm_fabric_distribution_create mapped to bcm_e_unavail */
/* bcm_fabric_distribution_destroy mapped to bcm_e_unavail */
/* bcm_fabric_distribution_get mapped to bcm_e_unavail */
/* bcm_fabric_distribution_set mapped to bcm_e_unavail */
/* bcm_fabric_init mapped to bcm_e_unavail */
/* bcm_fabric_packet_adjust_get mapped to bcm_e_unavail */
/* bcm_fabric_packet_adjust_set mapped to bcm_e_unavail */
/* bcm_fabric_port_failover_get mapped to bcm_e_unavail */
/* bcm_fabric_port_failover_set mapped to bcm_e_unavail */
/* bcm_failover_create mapped to bcm_e_unavail */
/* bcm_failover_destroy mapped to bcm_e_unavail */
/* bcm_failover_get mapped to bcm_e_unavail */
/* bcm_failover_set mapped to bcm_e_unavail */
extern int bcm_esw_ffpcounter_create(int,int,int *);
extern int bcm_esw_ffpcounter_delete(int,int,int);
extern int bcm_esw_ffpcounter_delete_all(int);
extern int bcm_esw_ffpcounter_get(int,int,int,uint64 *);
extern int bcm_esw_ffpcounter_init(int);
extern int bcm_esw_ffpcounter_set(int,int,int,uint64);
extern int bcm_esw_ffppacketcounter_get(int,int,int,uint64 *);
extern int bcm_esw_ffppacketcounter_set(int,int,int,uint64);
extern int bcm_esw_field_action_add(int,bcm_field_entry_t,bcm_field_action_t,uint32,uint32);
extern int bcm_esw_field_action_delete(int,bcm_field_entry_t,bcm_field_action_t,uint32,uint32);
extern int bcm_esw_field_action_get(int,bcm_field_entry_t,bcm_field_action_t,uint32 *,uint32 *);
extern int bcm_esw_field_action_ports_add(int,bcm_field_entry_t,bcm_field_action_t,bcm_pbmp_t);
extern int bcm_esw_field_action_ports_get(int,bcm_field_entry_t,bcm_field_action_t,bcm_pbmp_t *);
extern int bcm_esw_field_action_remove(int,bcm_field_entry_t,bcm_field_action_t);
extern int bcm_esw_field_action_remove_all(int,bcm_field_entry_t);
extern int bcm_esw_field_control_get(int,bcm_field_control_t,uint32 *);
extern int bcm_esw_field_control_set(int,bcm_field_control_t,uint32);
extern int bcm_esw_field_counter_create(int,bcm_field_entry_t);
extern int bcm_esw_field_counter_destroy(int,bcm_field_entry_t);
extern int bcm_esw_field_counter_get(int,bcm_field_entry_t,int,uint64 *);
extern int bcm_esw_field_counter_get32(int,bcm_field_entry_t,int,uint32 *);
extern int bcm_esw_field_counter_set(int,bcm_field_entry_t,int,uint64);
extern int bcm_esw_field_counter_set32(int,bcm_field_entry_t,int,uint32);
extern int bcm_esw_field_counter_share(int,bcm_field_entry_t,bcm_field_entry_t);
/* bcm_field_data_ethertype_t_init not dispatchable */
/* bcm_field_data_ip_protocol_t_init not dispatchable */
/* bcm_field_data_packet_format_t_init not dispatchable */
extern int bcm_esw_field_data_qualifier_create(int,bcm_field_data_qualifier_t *);
extern int bcm_esw_field_data_qualifier_destroy(int,int);
extern int bcm_esw_field_data_qualifier_destroy_all(int);
extern int bcm_esw_field_data_qualifier_ethertype_add(int,int,bcm_field_data_ethertype_t *);
extern int bcm_esw_field_data_qualifier_ethertype_delete(int,int,bcm_field_data_ethertype_t *);
extern int bcm_esw_field_data_qualifier_ip_protocol_add(int,int,bcm_field_data_ip_protocol_t *);
extern int bcm_esw_field_data_qualifier_ip_protocol_delete(int,int,bcm_field_data_ip_protocol_t *);
extern int bcm_esw_field_data_qualifier_packet_format_add(int,int,bcm_field_data_packet_format_t *);
extern int bcm_esw_field_data_qualifier_packet_format_delete(int,int,bcm_field_data_packet_format_t *);
/* bcm_field_data_qualifier_t_init not dispatchable */
extern int bcm_esw_field_detach(int);
extern int bcm_esw_field_entry_copy(int,bcm_field_entry_t,bcm_field_entry_t *);
extern int bcm_esw_field_entry_copy_id(int,bcm_field_entry_t,bcm_field_entry_t);
extern int bcm_esw_field_entry_create(int,bcm_field_group_t,bcm_field_entry_t *);
extern int bcm_esw_field_entry_create_id(int,bcm_field_group_t,bcm_field_entry_t);
extern int bcm_esw_field_entry_destroy(int,bcm_field_entry_t);
extern int bcm_esw_field_entry_destroy_all(int);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_field_entry_dump(int,bcm_field_entry_t);
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_field_entry_install(int,bcm_field_entry_t);
extern int bcm_esw_field_entry_policer_attach(int,bcm_field_entry_t,int,bcm_policer_t);
extern int bcm_esw_field_entry_policer_detach(int,bcm_field_entry_t,int);
extern int bcm_esw_field_entry_policer_detach_all(int,bcm_field_entry_t);
extern int bcm_esw_field_entry_policer_get(int,bcm_field_entry_t,int,bcm_policer_t *);
extern int bcm_esw_field_entry_prio_get(int,bcm_field_entry_t,int *);
extern int bcm_esw_field_entry_prio_set(int,bcm_field_entry_t,int);
extern int bcm_esw_field_entry_reinstall(int,bcm_field_entry_t);
extern int bcm_esw_field_entry_remove(int,bcm_field_entry_t);
extern int bcm_esw_field_group_compress(int,bcm_field_group_t);
extern int bcm_esw_field_group_create(int,bcm_field_qset_t,int,bcm_field_group_t *);
extern int bcm_esw_field_group_create_id(int,bcm_field_qset_t,int,bcm_field_group_t);
extern int bcm_esw_field_group_create_mode(int,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t *);
extern int bcm_esw_field_group_create_mode_id(int,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t);
#if 1/* anzhen.zheng, 5/26/2008 */
extern int bcm_esw_field_group_create_mode_slice_id(int,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t,bcm_field_group_sbmp_t );
#endif
extern int bcm_esw_field_group_destroy(int,bcm_field_group_t);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_field_group_dump(int,bcm_field_group_t);
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_field_group_enable_get(int,bcm_field_group_t,int *);
extern int bcm_esw_field_group_enable_set(int,bcm_field_group_t,int);
extern int bcm_esw_field_group_flush(int,bcm_field_group_t);
extern int bcm_esw_field_group_get(int,bcm_field_group_t,bcm_field_qset_t *);
/* bcm_field_group_install mapped to bcm_e_unavail */
extern int bcm_esw_field_group_mode_get(int,bcm_field_group_t,bcm_field_group_mode_t *);
extern int bcm_esw_field_group_port_create_mode(int,bcm_port_t,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t *);
extern int bcm_esw_field_group_port_create_mode_id(int,bcm_port_t,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t);
extern int bcm_esw_field_group_ports_create_mode(int,bcm_pbmp_t,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t *);
extern int bcm_esw_field_group_ports_create_mode_id(int,bcm_pbmp_t,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t);
#if 1/* anzhen.zheng, 5/26/2008 */
extern int bcm_esw_field_group_ports_create_mode_slice_id(int,bcm_pbmp_t,bcm_field_qset_t,int,bcm_field_group_mode_t,bcm_field_group_t,bcm_field_group_sbmp_t);
#endif
extern int bcm_esw_field_group_priority_get(int,bcm_field_group_t,int *);
extern int bcm_esw_field_group_priority_set(int,bcm_field_group_t,int);
/* bcm_field_group_remove mapped to bcm_e_unavail */
extern int bcm_esw_field_group_satisfies_qset(int,bcm_field_group_t,bcm_field_qset_t);
extern int bcm_esw_field_group_set(int,bcm_field_group_t,bcm_field_qset_t);
extern int bcm_esw_field_group_status_get(int,bcm_field_group_t,bcm_field_group_status_t *);
/* bcm_field_group_status_t_init not dispatchable */
extern int bcm_esw_field_init(int);
/* bcm_field_llc_header_t_init not dispatchable */
extern int bcm_esw_field_meter_control_set(int, uint32);
extern int bcm_esw_field_meter_create(int,bcm_field_entry_t);
extern int bcm_esw_field_meter_destroy(int,bcm_field_entry_t);
extern int bcm_esw_field_meter_get(int,bcm_field_entry_t,int,uint32 *,uint32 *);
extern int bcm_esw_field_meter_set(int,bcm_field_entry_t,int,uint32,uint32);
extern int bcm_esw_field_meter_share(int,bcm_field_entry_t,bcm_field_entry_t);
extern int bcm_esw_field_qset_add_udf(int,bcm_field_qset_t *,bcm_field_udf_t);
extern int bcm_esw_field_qset_data_qualifier_add(int,bcm_field_qset_t *,int);
/* bcm_field_qset_t_init not dispatchable */
extern int bcm_esw_field_qualify_BigIcmpCheck(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_DSCP(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_Decap(int,bcm_field_entry_t,bcm_field_decap_t);
extern int bcm_esw_field_qualify_DosAttack(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_Drop(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_DstClassField(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_DstClassL2(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_DstClassL3(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_DstIp(int,bcm_field_entry_t,bcm_ip_t,bcm_ip_t);
extern int bcm_esw_field_qualify_DstIp6(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_DstIp6High(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_DstMac(int,bcm_field_entry_t,bcm_mac_t,bcm_mac_t);
extern int bcm_esw_field_qualify_DstModid(int,bcm_field_entry_t,bcm_module_t,bcm_module_t);
extern int bcm_esw_field_qualify_DstPort(int,bcm_field_entry_t,bcm_module_t,bcm_module_t,bcm_port_t,bcm_port_t);
extern int bcm_esw_field_qualify_DstPortTgid(int,bcm_field_entry_t,bcm_port_t,bcm_port_t);
extern int bcm_esw_field_qualify_DstTrunk(int,bcm_field_entry_t,bcm_trunk_t,bcm_trunk_t);
extern int bcm_esw_field_qualify_EqualL4Port(int,bcm_field_entry_t,uint32);
extern int bcm_esw_field_qualify_EtherType(int,bcm_field_entry_t,uint16,uint16);
extern int bcm_esw_field_qualify_ExtensionHeaderSubCode(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_ExtensionHeaderType(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_ForwardingVlanValid(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_HiGig(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_IcmpTypeCode(int,bcm_field_entry_t,uint16,uint16);
extern int bcm_esw_field_qualify_IgmpTypeMaxRespTime(int,bcm_field_entry_t,uint16,uint16);
extern int bcm_esw_field_qualify_InPort(int,bcm_field_entry_t,bcm_port_t,bcm_port_t);
extern int bcm_esw_field_qualify_InPorts(int,bcm_field_entry_t,bcm_pbmp_t,bcm_pbmp_t);
extern int bcm_esw_field_qualify_IngressStpState(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_InnerDSCP(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_InnerDstIp(int,bcm_field_entry_t,bcm_ip_t,bcm_ip_t);
extern int bcm_esw_field_qualify_InnerDstIp6(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_InnerDstIp6High(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_InnerIpFrag(int,bcm_field_entry_t,bcm_field_IpFrag_t);
extern int bcm_esw_field_qualify_InnerIpProtocol(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_InnerSrcIp(int,bcm_field_entry_t,bcm_ip_t,bcm_ip_t);
extern int bcm_esw_field_qualify_InnerSrcIp6(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_InnerSrcIp6High(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_InnerTpid(int,bcm_field_entry_t,uint16);
extern int bcm_esw_field_qualify_InnerTtl(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_InnerVlan(int,bcm_field_entry_t,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_field_qualify_InterfaceClassL2(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_InterfaceClassL3(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_InterfaceClassPort(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_Ip6FlowLabel(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_Ip6HopLimit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_Ip6NextHeader(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_Ip6TrafficClass(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_IpAuth(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_IpFlags(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_IpFrag(int,bcm_field_entry_t,bcm_field_IpFrag_t);
extern int bcm_esw_field_qualify_IpInfo(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_IpProtocol(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_IpProtocolCommon(int,bcm_field_entry_t,bcm_field_IpProtocolCommon_t);
extern int bcm_esw_field_qualify_IpType(int,bcm_field_entry_t,bcm_field_IpType_t);
extern int bcm_esw_field_qualify_IpmcStarGroupHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L2CacheHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L2DestHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L2Format(int,bcm_field_entry_t,bcm_field_L2Format_t);
extern int bcm_esw_field_qualify_L2SrcHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L2SrcStatic(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L2StationMove(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L3DestHostHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L3DestRouteHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L3IntfGroup(int,bcm_field_entry_t,bcm_if_group_t,bcm_if_group_t);
extern int bcm_esw_field_qualify_L3Routable(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L3SrcHostHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L4DstPort(int,bcm_field_entry_t,bcm_l4_port_t,bcm_l4_port_t);
extern int bcm_esw_field_qualify_L4Ports(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_L4SrcPort(int,bcm_field_entry_t,bcm_l4_port_t,bcm_l4_port_t);
extern int bcm_esw_field_qualify_Llc(int,bcm_field_entry_t,bcm_field_llc_header_t,bcm_field_llc_header_t);
extern int bcm_esw_field_qualify_LookupClass0(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_LookupStatus(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_MHOpcode(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_MirrorCopy(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_MplsTerminated(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_OutPort(int,bcm_field_entry_t,bcm_port_t,bcm_port_t);
extern int bcm_esw_field_qualify_OutPorts(int,bcm_field_entry_t,bcm_pbmp_t,bcm_pbmp_t);
extern int bcm_esw_field_qualify_OuterTpid(int,bcm_field_entry_t,uint16);
extern int bcm_esw_field_qualify_OuterVlan(int,bcm_field_entry_t,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_field_qualify_PacketFormat(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_PacketRes(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_PortClass(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_RangeCheck(int,bcm_field_entry_t,bcm_field_range_t,int);
extern int bcm_esw_field_qualify_Snap(int,bcm_field_entry_t,bcm_field_snap_header_t,bcm_field_snap_header_t);
extern int bcm_esw_field_qualify_SrcClassField(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_SrcClassL2(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_SrcClassL3(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_SrcIp(int,bcm_field_entry_t,bcm_ip_t,bcm_ip_t);
extern int bcm_esw_field_qualify_SrcIp6(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_SrcIp6High(int,bcm_field_entry_t,bcm_ip6_t,bcm_ip6_t);
extern int bcm_esw_field_qualify_SrcIpEqualDstIp(int,bcm_field_entry_t,uint32);
extern int bcm_esw_field_qualify_SrcMac(int,bcm_field_entry_t,bcm_mac_t,bcm_mac_t);
extern int bcm_esw_field_qualify_SrcMacGroup(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_SrcModid(int,bcm_field_entry_t,bcm_module_t,bcm_module_t);
extern int bcm_esw_field_qualify_SrcPort(int,bcm_field_entry_t,bcm_module_t,bcm_module_t,bcm_port_t,bcm_port_t);
extern int bcm_esw_field_qualify_SrcPortTgid(int,bcm_field_entry_t,bcm_port_t,bcm_port_t);
extern int bcm_esw_field_qualify_SrcTrunk(int,bcm_field_entry_t,bcm_trunk_t,bcm_trunk_t);
extern int bcm_esw_field_qualify_Stage(int,bcm_field_entry_t,bcm_field_stage_t);
extern int bcm_esw_field_qualify_TcpControl(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_TcpHeaderSize(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_TcpSequenceZero(int,bcm_field_entry_t,uint32);
extern int bcm_esw_field_qualify_Tos(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_Ttl(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_TunnelTerminated(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_UserDefined(int,bcm_field_entry_t,bcm_field_udf_t,uint8 [BCM_FIELD_USER_FIELD_SIZE],uint8 [BCM_FIELD_USER_FIELD_SIZE]);
extern int bcm_esw_field_qualify_VlanFormat(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_VlanTranslationHit(int,bcm_field_entry_t,uint8,uint8);
extern int bcm_esw_field_qualify_Vrf(int,bcm_field_entry_t,uint32,uint32);
extern int bcm_esw_field_qualify_clear(int,bcm_field_entry_t);
extern int bcm_esw_field_qualify_data(int,bcm_field_entry_t,int,uint8 *,uint8 *,uint16);
extern int bcm_esw_field_range_create(int,bcm_field_range_t *,uint32,bcm_l4_port_t,bcm_l4_port_t);
extern int bcm_esw_field_range_create_id(int,bcm_field_range_t,uint32,bcm_l4_port_t,bcm_l4_port_t);
extern int bcm_esw_field_range_destroy(int,bcm_field_range_t);
extern int bcm_esw_field_range_get(int,bcm_field_range_t,uint32 *,bcm_l4_port_t *,bcm_l4_port_t *);
extern int bcm_esw_field_range_group_create(int,bcm_field_range_t *,uint32,bcm_l4_port_t,bcm_l4_port_t,bcm_if_group_t);
extern int bcm_esw_field_range_group_create_id(int,bcm_field_range_t,uint32,bcm_l4_port_t,bcm_l4_port_t,bcm_if_group_t);
extern int bcm_esw_field_resync(int);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_field_show(int,const char *);
/* bcm_field_snap_header_t_init not dispatchable */
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_field_status_get(int,bcm_field_status_t *);
/* bcm_field_status_t_init not dispatchable */
extern int bcm_esw_field_udf_create(int,bcm_field_udf_spec_t *,bcm_field_udf_t *);
extern int bcm_esw_field_udf_create_id(int,bcm_field_udf_spec_t *,bcm_field_udf_t);
extern int bcm_esw_field_udf_destroy(int,bcm_field_udf_t);
extern int bcm_esw_field_udf_ethertype_get(int,int,bcm_port_frametype_t *,bcm_port_ethertype_t *);
extern int bcm_esw_field_udf_ethertype_set(int,int,bcm_port_frametype_t,bcm_port_ethertype_t);
extern int bcm_esw_field_udf_get(int,bcm_field_udf_spec_t *,bcm_field_udf_t);
extern int bcm_esw_field_udf_ipprotocol_get(int,int,uint32 *,uint8 *);
extern int bcm_esw_field_udf_ipprotocol_set(int,int,uint32,uint8);
extern int bcm_esw_field_udf_spec_get(int,bcm_field_udf_spec_t *,uint32 *,uint32 *);
extern int bcm_esw_field_udf_spec_set(int,bcm_field_udf_spec_t *,uint32,uint32);
/* bcm_field_udf_spec_t_init not dispatchable */
extern int bcm_esw_filter_action_match(int,bcm_filterid_t,bcm_filter_action_t,uint32);
extern int bcm_esw_filter_action_no_match(int,bcm_filterid_t,bcm_filter_action_t,uint32);
extern int bcm_esw_filter_action_out_profile(int,bcm_filterid_t,bcm_filter_action_t,uint32,int);
extern int bcm_esw_filter_copy(int,bcm_filterid_t,bcm_filterid_t *);
extern int bcm_esw_filter_copy_id(int,bcm_filterid_t,bcm_filterid_t);
extern int bcm_esw_filter_create(int,bcm_filterid_t *);
extern int bcm_esw_filter_create_id(int,bcm_filterid_t);
extern int bcm_esw_filter_destroy(int,bcm_filterid_t);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_filter_dump(int,bcm_filterid_t);
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_filter_init(int);
extern int bcm_esw_filter_install(int,bcm_filterid_t);
extern int bcm_esw_filter_qualify_broadcast(int,bcm_filterid_t);
extern int bcm_esw_filter_qualify_data(int,bcm_filterid_t,int,int,const uint8 *,const uint8 *);
extern int bcm_esw_filter_qualify_data16(int,bcm_filterid_t,int,uint16,uint16);
extern int bcm_esw_filter_qualify_data32(int,bcm_filterid_t,int,uint32,uint32);
extern int bcm_esw_filter_qualify_data8(int,bcm_filterid_t,int,uint8,uint8);
extern int bcm_esw_filter_qualify_data_cvt(int,bcm_filterid_t);
extern int bcm_esw_filter_qualify_egress(int,bcm_filterid_t,bcm_pbmp_t);
extern int bcm_esw_filter_qualify_egress_modid(int,bcm_filterid_t,int);
extern int bcm_esw_filter_qualify_format(int,bcm_filterid_t,bcm_filter_format_t);
extern int bcm_esw_filter_qualify_ingress(int,bcm_filterid_t,bcm_pbmp_t);
extern int bcm_esw_filter_qualify_known_mcast(int,bcm_filterid_t);
extern int bcm_esw_filter_qualify_known_ucast(int,bcm_filterid_t);
extern int bcm_esw_filter_qualify_priority(int,bcm_filterid_t,int);
extern int bcm_esw_filter_qualify_stop(int,bcm_filterid_t,int);
extern int bcm_esw_filter_qualify_unknown_mcast(int,bcm_filterid_t);
extern int bcm_esw_filter_qualify_unknown_ucast(int,bcm_filterid_t);
extern int bcm_esw_filter_reinstall(int,bcm_filterid_t);
extern int bcm_esw_filter_remove(int,bcm_filterid_t);
extern int bcm_esw_filter_remove_all(int);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_filter_show(int,const char *);
/* bcm_find not dispatchable */
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_htls_egress_port_get(int,bcm_port_t,int *,uint16 *,uint32 *);
extern int bcm_esw_htls_egress_port_set(int,bcm_port_t,int,uint16,uint32);
extern int bcm_esw_htls_mode_get(int,int *);
extern int bcm_esw_htls_mode_set(int,int);
extern int bcm_esw_htls_tunnel_label_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_htls_tunnel_label_set(int,bcm_port_t,uint32);
extern int bcm_esw_htls_uplink_da_get(int,bcm_port_t,bcm_mac_t);
extern int bcm_esw_htls_uplink_da_set(int,bcm_port_t,bcm_mac_t);
extern int bcm_esw_htls_uplink_sa_get(int,bcm_port_t,bcm_mac_t);
extern int bcm_esw_htls_uplink_sa_set(int,bcm_port_t,bcm_mac_t);
extern int bcm_esw_htls_vclabel_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_htls_vclabel_set(int,bcm_port_t,uint32);
#ifdef	INCLUDE_I2C
extern int bcm_esw_i2c_ioctl(int,int,int,void *,int);
extern int bcm_esw_i2c_open(int,char *,uint32,int);
extern int bcm_esw_i2c_read(int,int,uint32,uint8 *,uint32 *);
extern int bcm_esw_i2c_write(int,int,uint32,uint8 *,uint32);
#endif	/* INCLUDE_I2C */
extern int bcm_esw_igmp_snooping_enable_get(int,int *);
extern int bcm_esw_igmp_snooping_enable_set(int,int);
extern int bcm_esw_igmp_snooping_init(int);
extern int bcm_esw_info_get(int,bcm_info_t *);
/* bcm_info_t_init not dispatchable */
extern int bcm_esw_init(int);
extern int bcm_esw_init_check(int);
extern int bcm_esw_init_phy_id_map(int,int []);
extern int bcm_esw_init_selective(int,uint32);
/* bcm_ip6_mask_create not dispatchable */
/* bcm_ip6_mask_length not dispatchable */
/* bcm_ip_mask_create not dispatchable */
/* bcm_ip_mask_length not dispatchable */
extern int bcm_esw_ipfix_config_get(int,bcm_ipfix_stage_t,bcm_port_t,bcm_ipfix_config_t *);
extern int bcm_esw_ipfix_config_set(int,bcm_ipfix_stage_t,bcm_port_t,bcm_ipfix_config_t *);
/* bcm_ipfix_config_t_init not dispatchable */
extern int bcm_esw_ipfix_register(int,bcm_ipfix_callback_t,void *);
extern int bcm_esw_ipfix_unregister(int,bcm_ipfix_callback_t,void *);
#ifdef	INCLUDE_L3
extern int bcm_esw_ipmc_add(int,bcm_ipmc_addr_t *);
extern int bcm_esw_ipmc_add_l2_ports(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,bcm_pbmp_t,bcm_pbmp_t);
extern int bcm_esw_ipmc_add_l3_ports(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,bcm_pbmp_t);
/* bcm_ipmc_addr_t_init not dispatchable */
extern int bcm_esw_ipmc_age(int,uint32,bcm_ipmc_traverse_cb,void *);
extern int bcm_esw_ipmc_bitmap_del(int,int,bcm_port_t,bcm_pbmp_t);
extern int bcm_esw_ipmc_bitmap_get(int,int,bcm_port_t,bcm_pbmp_t *);
extern int bcm_esw_ipmc_bitmap_max_get(int,int *);
extern int bcm_esw_ipmc_bitmap_set(int,int,bcm_port_t,bcm_pbmp_t);
extern int bcm_esw_ipmc_cos_set(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int);
extern int bcm_esw_ipmc_counters_get(int,bcm_port_t,bcm_ipmc_counters_t *);
/* bcm_ipmc_counters_t_init not dispatchable */
extern int bcm_esw_ipmc_delete(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int);
extern int bcm_esw_ipmc_delete_all(int);
extern int bcm_esw_ipmc_delete_l2_ports(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,bcm_port_t);
extern int bcm_esw_ipmc_delete_l3_port(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,bcm_port_t);
extern int bcm_esw_ipmc_detach(int);
extern int bcm_esw_ipmc_egress_intf_add(int,int,bcm_port_t,bcm_l3_intf_t *);
extern int bcm_esw_ipmc_egress_intf_delete(int,int,bcm_port_t,bcm_l3_intf_t *);
extern int bcm_esw_ipmc_egress_intf_delete_all(int,int,bcm_port_t);
extern int bcm_esw_ipmc_egress_intf_get(int,int,bcm_port_t,int,bcm_if_t *,int *);
extern int bcm_esw_ipmc_egress_intf_set(int,int,bcm_port_t,int,bcm_if_t *);
extern int bcm_esw_ipmc_egress_port_get(int,bcm_port_t,bcm_mac_t,int *,bcm_vlan_t *,int *);
extern int bcm_esw_ipmc_egress_port_init(int);
extern int bcm_esw_ipmc_egress_port_set(int,bcm_port_t,const bcm_mac_t,int,bcm_vlan_t,int);
extern int bcm_esw_ipmc_enable(int,int);
extern int bcm_esw_ipmc_entry_enable_set(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int);
extern int bcm_esw_ipmc_find(int,bcm_ipmc_addr_t *);
extern int bcm_esw_ipmc_get(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,bcm_ipmc_addr_t *);
extern int bcm_esw_ipmc_get_by_index(int,int,bcm_ipmc_addr_t *);
extern int bcm_esw_ipmc_init(int);
extern int bcm_esw_ipmc_port_modid_set(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int);
extern int bcm_esw_ipmc_port_tgid_set(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int,int);
extern int bcm_esw_ipmc_remove(int,bcm_ipmc_addr_t *);
extern int bcm_esw_ipmc_remove_all(int);
extern int bcm_esw_ipmc_repl_add(int,int,bcm_pbmp_t,bcm_vlan_t);
extern int bcm_esw_ipmc_repl_delete(int,int,bcm_pbmp_t,bcm_vlan_t);
extern int bcm_esw_ipmc_repl_delete_all(int,int,bcm_pbmp_t);
extern int bcm_esw_ipmc_repl_get(int,int,bcm_port_t,bcm_vlan_vector_t);
extern int bcm_esw_ipmc_repl_set(int,int,bcm_port_t,bcm_vlan_vector_t);
extern int bcm_esw_ipmc_source_ip_search(int,int);
extern int bcm_esw_ipmc_source_port_check(int,int);
extern int bcm_esw_ipmc_sport_mismatch_action(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int);
extern int bcm_esw_ipmc_traverse(int,uint32,bcm_ipmc_traverse_cb,void *);
extern int bcm_esw_ipmc_ttl_threshold_set(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int);
#endif	/* INCLUDE_L3 */
extern int bcm_esw_l2_addr_add(int,bcm_l2_addr_t *);
extern int bcm_esw_l2_addr_delete(int,bcm_mac_t,bcm_vlan_t);
extern int bcm_esw_l2_addr_delete_by_mac(int,bcm_mac_t,uint32);
extern int bcm_esw_l2_addr_delete_by_mac_port(int,bcm_mac_t,bcm_module_t,bcm_port_t,uint32);
extern int bcm_esw_l2_addr_delete_by_port(int,bcm_module_t,bcm_port_t,uint32);
extern int bcm_esw_l2_addr_delete_by_trunk(int,bcm_trunk_t,uint32);
extern int bcm_esw_l2_addr_delete_by_vlan(int,bcm_vlan_t,uint32);
extern int bcm_esw_l2_addr_delete_by_vlan_port(int,bcm_vlan_t,bcm_module_t,bcm_port_t,uint32);
extern int bcm_esw_l2_addr_delete_by_vlan_trunk(int,bcm_vlan_t,bcm_trunk_t,uint32);
/* bcm_l2_addr_dump not dispatchable */
extern int bcm_esw_l2_addr_freeze(int);
extern int bcm_esw_l2_addr_get(int,bcm_mac_t,bcm_vlan_t,bcm_l2_addr_t *);
extern int bcm_esw_l2_addr_register(int,bcm_l2_addr_callback_t,void *);
/* bcm_l2_addr_t_init not dispatchable */
extern int bcm_esw_l2_addr_thaw(int);
extern int bcm_esw_l2_addr_unregister(int,bcm_l2_addr_callback_t,void *);
extern int bcm_esw_l2_age_timer_get(int,int *);
extern int bcm_esw_l2_age_timer_set(int,int);
extern int bcm_esw_l2_bpdu_count(int);
extern int bcm_esw_l2_bpdu_get(int,int,bcm_mac_t *);
extern int bcm_esw_l2_bpdu_set(int,int,bcm_mac_t);
/* bcm_l2_cache_addr_t_init not dispatchable */
extern int bcm_esw_l2_cache_delete(int,int);
extern int bcm_esw_l2_cache_delete_all(int);
extern int bcm_esw_l2_cache_get(int,int,bcm_l2_cache_addr_t *);
extern int bcm_esw_l2_cache_init(int);
extern int bcm_esw_l2_cache_set(int,int,bcm_l2_cache_addr_t *,int *);
extern int bcm_esw_l2_cache_size_get(int,int *);
extern int bcm_esw_l2_clear(int);
extern int bcm_esw_l2_conflict_get(int,bcm_l2_addr_t *,bcm_l2_addr_t *,int,int *);
extern int bcm_esw_l2_detach(int);
/* bcm_l2_egress_create mapped to bcm_e_unavail */
/* bcm_l2_egress_destroy mapped to bcm_e_unavail */
/* bcm_l2_egress_find mapped to bcm_e_unavail */
/* bcm_l2_egress_get mapped to bcm_e_unavail */
/* bcm_l2_egress_t_init not dispatchable */
/* bcm_l2_egress_traverse mapped to bcm_e_unavail */
extern int bcm_esw_l2_init(int);
extern int bcm_esw_l2_key_dump(int,char *,bcm_l2_addr_t *,char *);
extern int bcm_esw_l2_learn_class_get(int,int,int *,uint32 *);
extern int bcm_esw_l2_learn_class_set(int,int,int,uint32);
extern int bcm_esw_l2_learn_limit_get(int,bcm_l2_learn_limit_t *);
extern int bcm_esw_l2_learn_limit_set(int,bcm_l2_learn_limit_t *);
/* bcm_l2_learn_limit_t_init not dispatchable */
extern int bcm_esw_l2_learn_port_class_get(int,bcm_gport_t,int *);
extern int bcm_esw_l2_learn_port_class_set(int,bcm_gport_t,int);
extern int bcm_esw_l2_port_native(int,int,int);
extern int bcm_esw_l2_replace(int,uint32,bcm_l2_addr_t *,bcm_module_t,bcm_port_t,bcm_trunk_t);
/* bcm_l2_stat_enable_set mapped to bcm_e_unavail */
/* bcm_l2_stat_get mapped to bcm_e_unavail */
/* bcm_l2_stat_get32 mapped to bcm_e_unavail */
/* bcm_l2_stat_set mapped to bcm_e_unavail */
/* bcm_l2_stat_set32 mapped to bcm_e_unavail */
extern int bcm_esw_l2_traverse(int,bcm_l2_traverse_cb,void *);
extern int bcm_esw_l2_tunnel_add(int,bcm_mac_t,bcm_vlan_t);
extern int bcm_esw_l2_tunnel_delete(int,bcm_mac_t,bcm_vlan_t);
extern int bcm_esw_l2_tunnel_delete_all(int);
#ifdef	INCLUDE_L3
extern int bcm_esw_l3_age(int,uint32,bcm_l3_age_cb);
extern int bcm_esw_l3_cleanup(int);
extern int bcm_esw_l3_conflict_get(int,bcm_l3_key_t *,bcm_l3_key_t *,int,int *);
extern int bcm_esw_l3_defip_add(int,bcm_l3_route_t *);
extern int bcm_esw_l3_defip_age(int,bcm_l3_route_traverse_cb);
extern int bcm_esw_l3_defip_delete(int,bcm_l3_route_t *);
extern int bcm_esw_l3_defip_delete_all(int);
extern int bcm_esw_l3_defip_delete_by_interface(int,int);
extern int bcm_esw_l3_defip_find_index(int,int,bcm_l3_route_t *);
extern int bcm_esw_l3_defip_get(int,bcm_l3_route_t *);
extern int bcm_esw_l3_defip_max_ecmp_get(int,int *);
extern int bcm_esw_l3_defip_max_ecmp_set(int,int);
extern int bcm_esw_l3_egress_create(int,uint32,bcm_l3_egress_t *,bcm_if_t *);
extern int bcm_esw_l3_egress_destroy(int,bcm_if_t);
extern int bcm_esw_l3_egress_find(int,bcm_l3_egress_t *,bcm_if_t *);
extern int bcm_esw_l3_egress_get(int,bcm_if_t,bcm_l3_egress_t *);
extern int bcm_esw_l3_egress_multipath_add(int,bcm_if_t,bcm_if_t);
extern int bcm_esw_l3_egress_multipath_create(int,uint32,int,bcm_if_t *,bcm_if_t *);
extern int bcm_esw_l3_egress_multipath_delete(int,bcm_if_t,bcm_if_t);
extern int bcm_esw_l3_egress_multipath_destroy(int,bcm_if_t);
extern int bcm_esw_l3_egress_multipath_find(int,int,bcm_if_t *,bcm_if_t *);
extern int bcm_esw_l3_egress_multipath_get(int,bcm_if_t,int,bcm_if_t *,int *);
extern int bcm_esw_l3_egress_multipath_traverse(int,bcm_l3_egress_multipath_traverse_cb,void *);
/* bcm_l3_egress_stat_enable_set mapped to bcm_e_unavail */
/* bcm_l3_egress_stat_get mapped to bcm_e_unavail */
/* bcm_l3_egress_stat_get32 mapped to bcm_e_unavail */
/* bcm_l3_egress_stat_set mapped to bcm_e_unavail */
/* bcm_l3_egress_stat_set32 mapped to bcm_e_unavail */
/* bcm_l3_egress_t_init not dispatchable */
extern int bcm_esw_l3_egress_traverse(int,bcm_l3_egress_traverse_cb,void *);
extern int bcm_esw_l3_enable_set(int,int);
extern int bcm_esw_l3_ip4_enable_set(int,int);
extern int bcm_esw_l3_ip6_enable_set(int,int);
extern int bcm_esw_l3_host_add(int,bcm_l3_host_t *);
extern int bcm_esw_l3_host_age(int,uint32,bcm_l3_host_traverse_cb,void *);
extern int bcm_esw_l3_host_conflict_get(int,bcm_l3_key_t *,bcm_l3_key_t *,int,int *);
extern int bcm_esw_l3_host_delete(int,bcm_l3_host_t *);
extern int bcm_esw_l3_host_delete_all(int,bcm_l3_host_t *);
extern int bcm_esw_l3_host_delete_by_interface(int,bcm_l3_host_t *);
extern int bcm_esw_l3_host_delete_by_network(int,bcm_l3_route_t *);
extern int bcm_esw_l3_host_find(int,bcm_l3_host_t *);
extern int bcm_esw_l3_host_invalidate_entry(int,bcm_ip_t);
/* bcm_l3_host_stat_enable_set mapped to bcm_e_unavail */
/* bcm_l3_host_stat_get mapped to bcm_e_unavail */
/* bcm_l3_host_stat_get32 mapped to bcm_e_unavail */
/* bcm_l3_host_stat_set mapped to bcm_e_unavail */
/* bcm_l3_host_stat_set32 mapped to bcm_e_unavail */
/* bcm_l3_host_t_init not dispatchable */
extern int bcm_esw_l3_host_traverse(int,uint32,uint32,uint32,bcm_l3_host_traverse_cb,void *);
extern int bcm_esw_l3_host_validate_entry(int,bcm_ip_t);
extern int bcm_esw_l3_info(int,bcm_l3_info_t *);
/* bcm_l3_info_t_init not dispatchable */
extern int bcm_esw_l3_init(int);
extern int bcm_esw_l3_interface_create(int,bcm_mac_t,bcm_vlan_t,int);
extern int bcm_esw_l3_interface_destroy(int,int);
extern int bcm_esw_l3_interface_find(int,int,bcm_vlan_t *,bcm_mac_t);
extern int bcm_esw_l3_interface_find_by_vlan(int,bcm_vlan_t,int *);
extern int bcm_esw_l3_interface_id_create(int,bcm_mac_t,bcm_vlan_t,int,int);
extern int bcm_esw_l3_interface_id_update(int,bcm_mac_t,bcm_vlan_t,int,int);
extern int bcm_esw_l3_interface_lookup(int,bcm_mac_t,bcm_vlan_t,int *);
extern int bcm_esw_l3_intf_create(int,bcm_l3_intf_t *);
extern int bcm_esw_l3_intf_delete(int,bcm_l3_intf_t *);
extern int bcm_esw_l3_intf_delete_all(int);
extern int bcm_esw_l3_intf_find(int,bcm_l3_intf_t *);
extern int bcm_esw_l3_intf_find_vlan(int,bcm_l3_intf_t *);
extern int bcm_esw_l3_intf_get(int,bcm_l3_intf_t *);
/* bcm_l3_intf_t_init not dispatchable */
extern int bcm_esw_l3_invalidate_entry(int,bcm_ip_t);
extern int bcm_esw_l3_ip6_prefix_map_add(int,bcm_ip6_t);
extern int bcm_esw_l3_ip6_prefix_map_delete(int,bcm_ip6_t);
extern int bcm_esw_l3_ip6_prefix_map_delete_all(int);
extern int bcm_esw_l3_ip6_prefix_map_get(int,int,bcm_ip6_t *,int *);
extern int bcm_esw_l3_ip_add(int,bcm_l3_ip_t *);
extern int bcm_esw_l3_ip_delete(int,bcm_ip_t);
extern int bcm_esw_l3_ip_delete_all(int);
extern int bcm_esw_l3_ip_delete_by_interface(int,int);
extern int bcm_esw_l3_ip_delete_by_prefix(int,bcm_ip_t,bcm_ip_t);
extern int bcm_esw_l3_ip_find(int,bcm_l3_ip_t *);
extern int bcm_esw_l3_ip_find_index(int,int,bcm_l3_ip_t *);
extern int bcm_esw_l3_ip_update_entry_by_key(int,bcm_l3_ip_t *);
/* bcm_l3_key_t_init not dispatchable */
extern int bcm_esw_l3_route_add(int,bcm_l3_route_t *);
extern int bcm_esw_l3_route_age(int,uint32,bcm_l3_route_traverse_cb,void *);
extern int bcm_esw_l3_route_delete(int,bcm_l3_route_t *);
extern int bcm_esw_l3_route_delete_all(int,bcm_l3_route_t *);
extern int bcm_esw_l3_route_delete_by_interface(int,bcm_l3_route_t *);
extern int bcm_esw_l3_route_get(int,bcm_l3_route_t *);
extern int bcm_esw_l3_route_max_ecmp_get(int,int *);
extern int bcm_esw_l3_route_max_ecmp_set(int,int);
extern int bcm_esw_l3_route_multipath_get(int,bcm_l3_route_t *,bcm_l3_route_t *,int,int *);
/* bcm_l3_route_stat_enable_set mapped to bcm_e_unavail */
/* bcm_l3_route_stat_get mapped to bcm_e_unavail */
/* bcm_l3_route_stat_get32 mapped to bcm_e_unavail */
/* bcm_l3_route_stat_set mapped to bcm_e_unavail */
/* bcm_l3_route_stat_set32 mapped to bcm_e_unavail */
/* bcm_l3_route_t_init not dispatchable */
extern int bcm_esw_l3_route_traverse(int,uint32,uint32,uint32,bcm_l3_route_traverse_cb,void *);
extern int bcm_esw_l3_status(int,int *,int *,int *,int *);
extern int bcm_esw_l3_untagged_update(int);
extern int bcm_esw_l3_validate_entry(int,bcm_ip_t);
#endif	/* INCLUDE_L3 */
extern int bcm_esw_link_change(int,bcm_pbmp_t);
extern int bcm_esw_link_wait(int,bcm_pbmp_t *,int);
extern int bcm_esw_linkscan_detach(int);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_linkscan_dump(int);
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_linkscan_enable_get(int,int *);
extern int bcm_esw_linkscan_enable_port_get(int,bcm_port_t);
extern int bcm_esw_linkscan_enable_set(int,int);
extern int bcm_esw_linkscan_init(int);
extern int bcm_esw_linkscan_mode_get(int,bcm_port_t,int *);
extern int bcm_esw_linkscan_mode_set(int,bcm_port_t,int);
extern int bcm_esw_linkscan_mode_set_pbm(int,bcm_pbmp_t,int);
extern int bcm_esw_linkscan_port_register(int,bcm_port_t,bcm_linkscan_port_handler_t);
extern int bcm_esw_linkscan_port_unregister(int,bcm_port_t,bcm_linkscan_port_handler_t);
extern int bcm_esw_linkscan_register(int,bcm_linkscan_handler_t);
extern int bcm_esw_linkscan_unregister(int,bcm_linkscan_handler_t);
extern int bcm_esw_linkscan_update(int,bcm_pbmp_t);
extern int bcm_esw_mcast_addr_add(int,bcm_mcast_addr_t *);
extern int bcm_esw_mcast_addr_add_w_l2mcindex(int,bcm_mcast_addr_t *);
extern int bcm_esw_mcast_addr_remove(int,bcm_mac_t,bcm_vlan_t);
extern int bcm_esw_mcast_addr_remove_w_l2mcindex(int,bcm_mcast_addr_t *);
/* bcm_mcast_addr_t_init not dispatchable */
extern int bcm_esw_mcast_bitmap_del(int,int,bcm_port_t,bcm_pbmp_t);
extern int bcm_esw_mcast_bitmap_get(int,int,bcm_port_t,bcm_pbmp_t *);
extern int bcm_esw_mcast_bitmap_max_get(int,int *);
extern int bcm_esw_mcast_bitmap_set(int,int,bcm_port_t,bcm_pbmp_t);
extern int bcm_esw_mcast_init(int);
extern int bcm_esw_mcast_join(int,bcm_mac_t,bcm_vlan_t,int,bcm_mcast_addr_t *,bcm_pbmp_t *);
extern int bcm_esw_mcast_leave(int,bcm_mac_t,bcm_vlan_t,int);
extern int bcm_esw_mcast_port_add(int,bcm_mcast_addr_t *);
extern int bcm_esw_mcast_port_get(int,bcm_mac_t,bcm_vlan_t,bcm_mcast_addr_t *);
extern int bcm_esw_mcast_port_remove(int,bcm_mcast_addr_t *);
extern int bcm_esw_meter_create(int,int,int *);
extern int bcm_esw_meter_delete(int,int,int);
extern int bcm_esw_meter_delete_all(int);
extern int bcm_esw_meter_get(int,int,int,uint32 *,uint32 *);
extern int bcm_esw_meter_init(int);
extern int bcm_esw_meter_set(int,int,int,uint32,uint32);
/* bcm_mim_port_add mapped to bcm_e_unavail */
/* bcm_mim_port_delete mapped to bcm_e_unavail */
/* bcm_mim_port_delete_all mapped to bcm_e_unavail */
/* bcm_mim_port_get mapped to bcm_e_unavail */
/* bcm_mim_port_get_all mapped to bcm_e_unavail */
/* bcm_mim_port_t_init not dispatchable */
/* bcm_mim_vpn_config_t_init not dispatchable */
/* bcm_mim_vpn_create mapped to bcm_e_unavail */
/* bcm_mim_vpn_destroy mapped to bcm_e_unavail */
/* bcm_mim_vpn_destroy_all mapped to bcm_e_unavail */
/* bcm_mim_vpn_get mapped to bcm_e_unavail */
/* bcm_mim_vpn_traverse mapped to bcm_e_unavail */
extern int bcm_esw_mirror_destination_create(int,bcm_mirror_destination_t *);
extern int bcm_esw_mirror_destination_destroy(int,bcm_gport_t);
extern int bcm_esw_mirror_destination_get(int,bcm_gport_t,bcm_mirror_destination_t *);
/* bcm_mirror_destination_t_init not dispatchable */
extern int bcm_esw_mirror_destination_traverse(int,bcm_mirror_destination_traverse_cb,void *);
extern int bcm_esw_mirror_egress_get(int,bcm_port_t,int *);
extern int bcm_esw_mirror_egress_path_get(int,bcm_module_t,bcm_port_t *);
extern int bcm_esw_mirror_egress_path_set(int,bcm_module_t,bcm_port_t);
extern int bcm_esw_mirror_egress_set(int,bcm_port_t,int);
extern int bcm_esw_mirror_ingress_get(int,bcm_port_t,int *);
extern int bcm_esw_mirror_ingress_set(int,bcm_port_t,int);
extern int bcm_esw_mirror_init(int);
extern int bcm_esw_mirror_mode_get(int,int *);
extern int bcm_esw_mirror_mode_set(int,int);
extern int bcm_esw_mirror_pfmt_get(int,int *);
extern int bcm_esw_mirror_pfmt_set(int,int);
extern int bcm_esw_mirror_port_dest_add(int,bcm_port_t,uint32,bcm_gport_t);
extern int bcm_esw_mirror_port_dest_delete(int,bcm_port_t,uint32,bcm_gport_t);
extern int bcm_esw_mirror_port_dest_delete_all(int,bcm_port_t,uint32);
extern int bcm_esw_mirror_port_dest_get(int,bcm_port_t,uint32,int,bcm_gport_t *,int *);
extern int bcm_esw_mirror_port_get(int,bcm_port_t,bcm_module_t *,bcm_port_t *,uint32 *);
extern int bcm_esw_mirror_port_set(int,bcm_port_t,bcm_module_t,bcm_port_t,uint32);
extern int bcm_esw_mirror_to_get(int,bcm_port_t *);
extern int bcm_esw_mirror_to_pbmp_get(int,bcm_port_t,bcm_pbmp_t *);
extern int bcm_esw_mirror_to_pbmp_set(int,bcm_port_t,bcm_pbmp_t);
extern int bcm_esw_mirror_to_set(int,bcm_port_t);
extern int bcm_esw_mirror_vlan_get(int,bcm_port_t,uint16 *,uint16 *);
extern int bcm_esw_mirror_vlan_set(int,bcm_port_t,uint16,uint16);
/* bcm_module_name not dispatchable */
/* bcm_mpls_circuit_t_init not dispatchable */
#ifdef	INCLUDE_L3
extern int bcm_esw_mpls_cleanup(int);
/* bcm_mpls_egress_label_t_init not dispatchable */
extern int bcm_esw_mpls_exp_map_create(int,uint32,int *);
extern int bcm_esw_mpls_exp_map_destroy(int,int);
extern int bcm_esw_mpls_exp_map_get(int,int,bcm_mpls_exp_map_t *);
extern int bcm_esw_mpls_exp_map_set(int,int,bcm_mpls_exp_map_t *);
/* bcm_mpls_exp_map_t_init not dispatchable */
extern int bcm_esw_mpls_info(int,bcm_mpls_info_t *);
/* bcm_mpls_info_t_init not dispatchable */
extern int bcm_esw_mpls_init(int);
extern int bcm_esw_mpls_l3_initiator_clear(int,bcm_l3_intf_t *);
extern int bcm_esw_mpls_l3_initiator_clear_all(int);
extern int bcm_esw_mpls_l3_initiator_get(int,bcm_l3_intf_t *,bcm_mpls_l3_initiator_t *);
extern int bcm_esw_mpls_l3_initiator_set(int,bcm_l3_intf_t *,bcm_mpls_l3_initiator_t *);
/* bcm_mpls_l3_initiator_t_init not dispatchable */
extern int bcm_esw_mpls_label_stat_get(int,bcm_mpls_label_t,bcm_gport_t,bcm_mpls_stat_t,uint64 *);
extern int bcm_esw_mpls_label_stat_get32(int,bcm_mpls_label_t,bcm_gport_t,bcm_mpls_stat_t,uint32 *);
extern int bcm_esw_mpls_port_add(int,bcm_vpn_t,bcm_mpls_port_t *);
extern int bcm_esw_mpls_port_block_get(int,bcm_vpn_t,bcm_port_t,int *);
extern int bcm_esw_mpls_port_block_set(int,bcm_vpn_t,bcm_port_t,int);
extern int bcm_esw_mpls_port_delete(int,bcm_vpn_t,bcm_gport_t);
extern int bcm_esw_mpls_port_delete_all(int,bcm_vpn_t);
extern int bcm_esw_mpls_port_get(int,bcm_vpn_t,bcm_mpls_port_t *);
extern int bcm_esw_mpls_port_get_all(int,bcm_vpn_t,int,bcm_mpls_port_t *,int *);
extern int bcm_esw_mpls_port_stat_enable_set(int,bcm_gport_t,int);
extern int bcm_esw_mpls_port_stat_get(int,bcm_gport_t,bcm_cos_t,bcm_mpls_port_stat_t,uint64 *);
extern int bcm_esw_mpls_port_stat_get32(int,bcm_gport_t,bcm_cos_t,bcm_mpls_port_stat_t,uint32 *);
extern int bcm_esw_mpls_port_stat_set(int,bcm_gport_t,bcm_cos_t,bcm_mpls_port_stat_t,uint64);
extern int bcm_esw_mpls_port_stat_set32(int,bcm_gport_t,bcm_cos_t,bcm_mpls_port_stat_t,uint32);
/* bcm_mpls_port_t_init not dispatchable */
extern int bcm_esw_mpls_switch_add(int,bcm_mpls_switch_t *);
extern int bcm_esw_mpls_switch_delete(int,bcm_mpls_switch_t *);
extern int bcm_esw_mpls_switch_delete_all(int,int);
extern int bcm_esw_mpls_switch_get(int,bcm_mpls_switch_t *);
/* bcm_mpls_switch_t_init not dispatchable */
extern int bcm_esw_mpls_switch_traverse(int,uint32,uint32,uint32,bcm_mpls_switch_traverse_cb,void *);
extern int bcm_esw_mpls_tunnel_initiator_clear(int,bcm_if_t);
extern int bcm_esw_mpls_tunnel_initiator_clear_all(int);
extern int bcm_esw_mpls_tunnel_initiator_get(int,bcm_if_t,int,bcm_mpls_egress_label_t *,int *);
extern int bcm_esw_mpls_tunnel_initiator_set(int,bcm_if_t,int,bcm_mpls_egress_label_t *);
extern int bcm_esw_mpls_tunnel_switch_add(int,bcm_mpls_tunnel_switch_t *);
extern int bcm_esw_mpls_tunnel_switch_delete(int,bcm_mpls_tunnel_switch_t *);
extern int bcm_esw_mpls_tunnel_switch_delete_all(int);
extern int bcm_esw_mpls_tunnel_switch_get(int,bcm_mpls_tunnel_switch_t *);
/* bcm_mpls_tunnel_switch_t_init not dispatchable */
extern int bcm_esw_mpls_tunnel_switch_traverse(int,bcm_mpls_tunnel_switch_traverse_cb,void *);
extern int bcm_esw_mpls_vpn_add(int,bcm_vpn_t,bcm_mpls_vpn_t *);
extern int bcm_esw_mpls_vpn_circuit_add(int,bcm_vpn_t,bcm_mpls_circuit_t *);
extern int bcm_esw_mpls_vpn_circuit_delete(int,bcm_vpn_t,bcm_mpls_circuit_t *);
extern int bcm_esw_mpls_vpn_circuit_delete_all(int,bcm_vpn_t);
extern int bcm_esw_mpls_vpn_circuit_get(int,bcm_vpn_t,int,bcm_mpls_circuit_t *,int *);
/* bcm_mpls_vpn_config_t_init not dispatchable */
extern int bcm_esw_mpls_vpn_create(int,bcm_vpn_t,uint32);
extern int bcm_esw_mpls_vpn_delete(int,bcm_vpn_t,bcm_mpls_vpn_t *);
extern int bcm_esw_mpls_vpn_delete_all(int,bcm_vpn_t);
extern int bcm_esw_mpls_vpn_destroy(int,bcm_vpn_t);
extern int bcm_esw_mpls_vpn_get(int,bcm_vpn_t,int,bcm_mpls_vpn_t *,int *);
extern int bcm_esw_mpls_vpn_id_create(int,bcm_mpls_vpn_config_t *);
extern int bcm_esw_mpls_vpn_id_destroy(int,bcm_vpn_t);
extern int bcm_esw_mpls_vpn_id_destroy_all(int);
extern int bcm_esw_mpls_vpn_id_get(int,bcm_vpn_t,bcm_mpls_vpn_config_t *);
/* bcm_mpls_vpn_t_init not dispatchable */
#endif	/* INCLUDE_L3 */
extern int bcm_esw_multicast_create(int,uint32,bcm_multicast_t *);
extern int bcm_esw_multicast_destroy(int,bcm_multicast_t);
extern int bcm_esw_multicast_egress_add(int,bcm_multicast_t,bcm_gport_t,bcm_if_t);
extern int bcm_esw_multicast_egress_delete(int,bcm_multicast_t,bcm_gport_t,bcm_if_t);
extern int bcm_esw_multicast_egress_delete_all(int,bcm_multicast_t);
extern int bcm_esw_multicast_egress_get(int,bcm_multicast_t,int,bcm_gport_t *,bcm_if_t *,int *);
extern int bcm_esw_multicast_egress_set(int,bcm_multicast_t,int,bcm_gport_t *,bcm_if_t *);
extern int bcm_esw_multicast_l2_encap_get(int,bcm_multicast_t,bcm_gport_t,bcm_vlan_t,bcm_if_t *);
extern int bcm_esw_multicast_l3_encap_get(int,bcm_multicast_t,bcm_gport_t,bcm_if_t,bcm_if_t *);
extern int bcm_esw_multicast_mim_encap_get(int,bcm_multicast_t,bcm_gport_t,bcm_gport_t,bcm_if_t *);
extern int bcm_esw_multicast_subport_encap_get(int,bcm_multicast_t,bcm_gport_t,bcm_gport_t,bcm_if_t *);
extern int bcm_esw_multicast_vpls_encap_get(int,bcm_multicast_t,bcm_gport_t,bcm_gport_t,bcm_if_t *);
/* bcm_oam_ccm_endpoint_add mapped to bcm_e_unavail */
/* bcm_oam_ccm_endpoint_delete mapped to bcm_e_unavail */
/* bcm_oam_ccm_endpoint_delete_all mapped to bcm_e_unavail */
/* bcm_oam_ccm_endpoint_get mapped to bcm_e_unavail */
/* bcm_oam_ccm_register mapped to bcm_e_unavail */
/* bcm_oam_ccm_t_init not dispatchable */
/* bcm_oam_ccm_traverse mapped to bcm_e_unavail */
/* bcm_oam_ccm_unregister mapped to bcm_e_unavail */
/* bcm_oam_detach mapped to bcm_e_unavail */
/* bcm_oam_init mapped to bcm_e_unavail */
/* bcm_phy_config_t_init not dispatchable */
/* bcm_pkt_alloc not dispatchable */
/* bcm_pkt_blk_alloc not dispatchable */
/* bcm_pkt_blk_free not dispatchable */
/* bcm_pkt_blk_t_init not dispatchable */
/* bcm_pkt_byte_index not dispatchable */
/* bcm_pkt_clear not dispatchable */
/* bcm_pkt_flags_init not dispatchable */
/* bcm_pkt_flags_len_setup not dispatchable */
/* bcm_pkt_free not dispatchable */
/* bcm_pkt_memcpy not dispatchable */
/* bcm_pkt_rx_alloc not dispatchable */
/* bcm_pkt_rx_free not dispatchable */
/* bcm_pkt_t_init not dispatchable */
/* bcm_policer_config_t_init not dispatchable */
extern int bcm_esw_policer_create(int,bcm_policer_config_t *,bcm_policer_t *);
extern int bcm_esw_policer_destroy(int,bcm_policer_t);
extern int bcm_esw_policer_destroy_all(int);
extern int bcm_esw_policer_get(int,bcm_policer_t,bcm_policer_config_t *);
/* bcm_policer_group_create mapped to bcm_e_unavail */
extern int bcm_esw_policer_init(int);
extern int bcm_esw_policer_set(int,bcm_policer_t,bcm_policer_config_t *);
/* bcm_policer_stat_enable_get mapped to bcm_e_unavail */
/* bcm_policer_stat_enable_set mapped to bcm_e_unavail */
/* bcm_policer_stat_get mapped to bcm_e_unavail */
/* bcm_policer_stat_get32 mapped to bcm_e_unavail */
/* bcm_policer_stat_set mapped to bcm_e_unavail */
/* bcm_policer_stat_set32 mapped to bcm_e_unavail */
extern int bcm_esw_policer_traverse(int,bcm_policer_traverse_cb,void *);
extern int bcm_esw_port_ability_advert_get(int,bcm_port_t,bcm_port_ability_t *);
extern int bcm_esw_port_ability_advert_set(int,bcm_port_t,bcm_port_ability_t *);
extern int bcm_esw_port_ability_get(int,bcm_port_t,bcm_port_abil_t *);
extern int bcm_esw_port_ability_local_get(int,bcm_port_t,bcm_port_ability_t *);
extern int bcm_esw_port_ability_remote_get(int,bcm_port_t,bcm_port_ability_t *);
/* bcm_port_ability_t_init not dispatchable */
extern int bcm_esw_port_advert_get(int,bcm_port_t,bcm_port_abil_t *);
extern int bcm_esw_port_advert_remote_get(int,bcm_port_t,bcm_port_abil_t *);
extern int bcm_esw_port_advert_set(int,bcm_port_t,bcm_port_abil_t);
extern int bcm_esw_port_autoneg_get(int,bcm_port_t,int *);
extern int bcm_esw_port_autoneg_set(int,bcm_port_t,int);
extern int bcm_esw_port_bpdu_enable_get(int,bcm_port_t,int *);
extern int bcm_esw_port_bpdu_enable_set(int,bcm_port_t,int);
extern int bcm_esw_port_cable_diag(int,bcm_port_t,bcm_port_cable_diag_t *);
extern int bcm_esw_port_cfi_color_get(int,bcm_port_t,int,bcm_color_t *);
extern int bcm_esw_port_cfi_color_set(int,bcm_port_t,int,bcm_color_t);
extern int bcm_esw_port_class_get(int,bcm_port_t,bcm_port_class_t,uint32 *);
extern int bcm_esw_port_class_set(int,bcm_port_t,bcm_port_class_t,uint32);
extern int bcm_esw_port_clear(int);
extern int bcm_esw_port_config_get(int,bcm_port_config_t *);
/* bcm_port_config_t_init not dispatchable */
extern int bcm_esw_port_control_get(int,bcm_port_t,bcm_port_control_t,int *);
extern int bcm_esw_port_control_set(int,bcm_port_t,bcm_port_control_t,int);
extern int bcm_esw_port_detach(int,bcm_pbmp_t,bcm_pbmp_t *);
extern int bcm_esw_port_discard_get(int,bcm_port_t,int *);
extern int bcm_esw_port_discard_set(int,bcm_port_t,int);
extern int bcm_esw_port_dscp_map_get(int,bcm_port_t,int,int *,int *);
extern int bcm_esw_port_dscp_map_mode_get(int,bcm_port_t,int *);
extern int bcm_esw_port_dscp_map_mode_set(int,bcm_port_t,int);
extern int bcm_esw_port_dscp_map_set(int,bcm_port_t,int,int,int);
/* bcm_port_dscp_unmap_get mapped to bcm_e_unavail */
/* bcm_port_dscp_unmap_set mapped to bcm_e_unavail */
extern int bcm_esw_port_dtag_mode_get(int,bcm_port_t,int *);
extern int bcm_esw_port_dtag_mode_set(int,bcm_port_t,int);
extern int bcm_esw_port_duplex_get(int,bcm_port_t,int *);
extern int bcm_esw_port_duplex_set(int,bcm_port_t,int);
extern int bcm_esw_port_egress_get(int,bcm_port_t,int,bcm_pbmp_t *);
extern int bcm_esw_port_egress_set(int,bcm_port_t,int,bcm_pbmp_t);
extern int bcm_esw_port_enable_get(int,bcm_port_t,int *);
extern int bcm_esw_port_enable_set(int,bcm_port_t,int);
extern int bcm_esw_port_encap_get(int,bcm_port_t,int *);
extern int bcm_esw_port_encap_set(int,bcm_port_t,int);
extern int bcm_esw_port_fault_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_port_flood_block_get(int,bcm_port_t,bcm_port_t,uint32 *);
extern int bcm_esw_port_flood_block_set(int,bcm_port_t,bcm_port_t,uint32);
extern int bcm_esw_port_force_forward_get(int,bcm_port_t,bcm_port_t *,int *);
extern int bcm_esw_port_force_forward_set(int,bcm_port_t,bcm_port_t,int);
extern int bcm_esw_port_force_vlan_get(int,bcm_port_t,bcm_vlan_t *,int *,uint32 *);
extern int bcm_esw_port_force_vlan_set(int,bcm_port_t,bcm_vlan_t,int,uint32);
extern int bcm_esw_port_frame_max_get(int,bcm_port_t,int *);
extern int bcm_esw_port_frame_max_set(int,bcm_port_t,int);
extern int bcm_esw_port_gport_get(int,bcm_port_t,bcm_gport_t *);
extern int bcm_esw_port_ifg_get(int,bcm_port_t,int,bcm_port_duplex_t,int *);
extern int bcm_esw_port_ifg_set(int,bcm_port_t,int,bcm_port_duplex_t,int);
extern int bcm_esw_port_ifilter_get(int,bcm_port_t,int *);
extern int bcm_esw_port_ifilter_set(int,bcm_port_t,int);
extern int bcm_esw_port_info_get(int,bcm_port_t,bcm_port_info_t *);
extern int bcm_esw_port_info_restore(int,bcm_port_t,bcm_port_info_t *);
extern int bcm_esw_port_info_save(int,bcm_port_t,bcm_port_info_t *);
extern int bcm_esw_port_info_set(int,bcm_port_t,bcm_port_info_t *);
/* bcm_port_info_t_init not dispatchable */
extern int bcm_esw_port_init(int);
extern int bcm_esw_port_inner_tpid_get(int,bcm_port_t,uint16 *);
extern int bcm_esw_port_inner_tpid_set(int,bcm_port_t,uint16);
extern int bcm_esw_port_interface_get(int,bcm_port_t,bcm_port_if_t *);
extern int bcm_esw_port_interface_set(int,bcm_port_t,bcm_port_if_t);
extern int bcm_esw_port_ipmc_modify_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_port_ipmc_modify_set(int,bcm_port_t,uint32);
extern int bcm_esw_port_jam_get(int,bcm_port_t,int *);
extern int bcm_esw_port_jam_set(int,bcm_port_t,int);
extern int bcm_esw_port_l3_enable_get(int,bcm_port_t,int *);
extern int bcm_esw_port_l3_enable_set(int,bcm_port_t,int);
extern int bcm_esw_port_l3_modify_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_port_l3_modify_set(int,bcm_port_t,uint32);
extern int bcm_esw_port_l3_mtu_get(int,bcm_port_t,int *);
extern int bcm_esw_port_l3_mtu_set(int,bcm_port_t,int);
extern int bcm_esw_port_learn_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_port_learn_modify(int,bcm_port_t,uint32,uint32);
extern int bcm_esw_port_learn_set(int,bcm_port_t,uint32);
extern int bcm_esw_port_link_status_get(int,bcm_port_t,int *);
extern int bcm_esw_port_linkscan_get(int,bcm_port_t,int *);
extern int bcm_esw_port_linkscan_set(int,bcm_port_t,int);
extern int bcm_esw_port_loopback_get(int,bcm_port_t,int *);
extern int bcm_esw_port_loopback_set(int,bcm_port_t,int);
extern int bcm_esw_port_master_get(int,bcm_port_t,int *);
extern int bcm_esw_port_master_set(int,bcm_port_t,int);
extern int bcm_esw_port_mdix_get(int,bcm_port_t,bcm_port_mdix_t *);
extern int bcm_esw_port_mdix_set(int,bcm_port_t,bcm_port_mdix_t);
extern int bcm_esw_port_mdix_status_get(int,bcm_port_t,bcm_port_mdix_status_t *);
extern int bcm_esw_port_medium_config_get(int,bcm_port_t,bcm_port_medium_t,bcm_phy_config_t *);
extern int bcm_esw_port_medium_config_set(int,bcm_port_t,bcm_port_medium_t,bcm_phy_config_t *);
extern int bcm_esw_port_medium_get(int,bcm_port_t,bcm_port_medium_t *);
extern int bcm_esw_port_medium_status_register(int,bcm_port_t,bcm_port_medium_status_cb_t,void *);
extern int bcm_esw_port_medium_status_unregister(int,bcm_port_t,bcm_port_medium_status_cb_t,void *);
extern int bcm_esw_port_modid_egress_get(int,bcm_port_t,bcm_module_t,bcm_pbmp_t *);
extern int bcm_esw_port_modid_egress_set(int,bcm_port_t,bcm_module_t,bcm_pbmp_t);
extern int bcm_esw_port_modid_enable_get(int,bcm_port_t,int,int *);
extern int bcm_esw_port_modid_enable_set(int,bcm_port_t,int,int);
extern int bcm_esw_port_pause_addr_get(int,bcm_port_t,bcm_mac_t);
extern int bcm_esw_port_pause_addr_set(int,bcm_port_t,bcm_mac_t);
extern int bcm_esw_port_pause_get(int,bcm_port_t,int *,int *);
extern int bcm_esw_port_pause_set(int,bcm_port_t,int,int);
extern int bcm_esw_port_pause_sym_get(int,bcm_port_t,int *);
extern int bcm_esw_port_pause_sym_set(int,bcm_port_t,int);
extern int bcm_esw_port_pfm_get(int,bcm_port_t,int *);
extern int bcm_esw_port_pfm_set(int,bcm_port_t,int);
extern int bcm_esw_port_phy_control_get(int,bcm_port_t,bcm_port_phy_control_t,uint32 *);
extern int bcm_esw_port_phy_control_set(int,bcm_port_t,bcm_port_phy_control_t,uint32);
extern int bcm_esw_port_phy_drv_name_get(int,bcm_port_t,char *,int);
extern int bcm_esw_port_phy_get(int,bcm_port_t,uint32,uint32,uint32 *);
extern int bcm_esw_port_phy_reset(int,bcm_port_t);
extern int bcm_esw_port_phy_reset_register(int,bcm_port_t,bcm_port_phy_reset_cb_t,void *);
extern int bcm_esw_port_phy_reset_unregister(int,bcm_port_t,bcm_port_phy_reset_cb_t,void *);
extern int bcm_esw_port_phy_set(int,bcm_port_t,uint32,uint32,uint32);
extern int bcm_esw_port_priority_color_get(int,bcm_port_t,int,bcm_color_t *);
extern int bcm_esw_port_priority_color_set(int,bcm_port_t,int,bcm_color_t);
extern int bcm_esw_port_probe(int,bcm_pbmp_t,bcm_pbmp_t *);
extern int bcm_esw_port_protocol_vlan_add(int,bcm_port_t,bcm_port_frametype_t,bcm_port_ethertype_t,bcm_vlan_t);
extern int bcm_esw_port_protocol_vlan_delete(int,bcm_port_t,bcm_port_frametype_t,bcm_port_ethertype_t);
extern int bcm_esw_port_protocol_vlan_delete_all(int,bcm_port_t);
extern int bcm_esw_port_queued_count_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_port_rate_egress_get(int,bcm_port_t,uint32 *,uint32 *);
extern int bcm_esw_port_rate_egress_set(int,bcm_port_t,uint32,uint32);
/* bcm_port_rate_egress_traffic_get mapped to bcm_e_unavail */
/* bcm_port_rate_egress_traffic_set mapped to bcm_e_unavail */
extern int bcm_esw_port_rate_ingress_get(int,bcm_port_t,uint32 *,uint32 *);
extern int bcm_esw_port_rate_ingress_set(int,bcm_port_t,uint32,uint32);
extern int bcm_esw_egress_packet_ifg_set(int, uint32);
extern int bcm_esw_port_rate_pause_get(int,bcm_port_t,uint32 *,uint32 *);
extern int bcm_esw_port_rate_pause_set(int,bcm_port_t,uint32,uint32);
extern int bcm_esw_port_sample_rate_get(int,bcm_port_t,int *,int *);
extern int bcm_esw_port_sample_rate_set(int,bcm_port_t,int,int);
extern int bcm_esw_port_selective_get(int,bcm_port_t,bcm_port_info_t *);
extern int bcm_esw_port_selective_set(int,bcm_port_t,bcm_port_info_t *);
extern int bcm_esw_port_speed_get(int,bcm_port_t,int *);
extern int bcm_esw_port_speed_max(int,bcm_port_t,int *);
extern int bcm_esw_port_speed_set(int,bcm_port_t,int);
extern int bcm_esw_port_stp_get(int,bcm_port_t,int *);
extern int bcm_esw_port_stp_set(int,bcm_port_t,int);
extern int bcm_esw_port_tgid_get(int,bcm_port_t,int *,int *);
extern int bcm_esw_port_tgid_set(int,bcm_port_t,int,int);
extern int bcm_esw_port_tpid_add(int,bcm_port_t,uint16,int);
extern int bcm_esw_port_tpid_delete(int,bcm_port_t,uint16);
extern int bcm_esw_port_tpid_delete_all(int,bcm_port_t);
extern int bcm_esw_port_tpid_get(int,bcm_port_t,uint16 *);
extern int bcm_esw_port_tpid_set(int,bcm_port_t,uint16);
extern int bcm_esw_port_trunk_index_get(int,bcm_port_t,int *);
extern int bcm_esw_port_trunk_index_set(int,bcm_port_t,int);
extern int bcm_esw_port_untagged_priority_get(int,bcm_port_t,int *);
extern int bcm_esw_port_untagged_priority_set(int,bcm_port_t,int);
extern int bcm_esw_port_untagged_vlan_get(int,bcm_port_t,bcm_vlan_t *);
extern int bcm_esw_port_untagged_vlan_set(int,bcm_port_t,bcm_vlan_t);
extern int bcm_esw_port_update(int,bcm_port_t,int);
/* bcm_port_vlan_dscp_map_get mapped to bcm_e_unavail */
/* bcm_port_vlan_dscp_map_set mapped to bcm_e_unavail */
extern int bcm_esw_port_vlan_inner_tag_get(int,bcm_port_t,uint16 *);
extern int bcm_esw_port_vlan_inner_tag_set(int,bcm_port_t,uint16);
extern int bcm_esw_port_vlan_member_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_port_vlan_member_set(int,bcm_port_t,uint32);
/* bcm_port_vlan_pri_map_get mapped to bcm_e_unavail */
/* bcm_port_vlan_pri_map_set mapped to bcm_e_unavail */
extern int bcm_esw_port_vlan_priority_map_get(int,bcm_port_t,int,int,int *,bcm_color_t *);
extern int bcm_esw_port_vlan_priority_map_set(int,bcm_port_t,int,int,int,bcm_color_t);
extern int bcm_esw_port_vlan_priority_unmap_get(int,bcm_port_t,int,bcm_color_t,int *,int *);
extern int bcm_esw_port_vlan_priority_unmap_set(int,bcm_port_t,int,bcm_color_t,int,int);
#ifdef	INCLUDE_L3
extern int bcm_esw_proxy_client_set(int,bcm_port_t,bcm_proxy_proto_type_t,bcm_module_t,bcm_port_t,int);
extern int bcm_esw_proxy_server_get(int,bcm_port_t,bcm_proxy_mode_t,int *);
extern int bcm_esw_proxy_server_set(int,bcm_port_t,bcm_proxy_mode_t,int);
#endif	/* INCLUDE_L3 */
extern int bcm_esw_rate_bandwidth_get(int,bcm_port_t,int,uint32 *,uint32 *);
extern int bcm_esw_rate_bandwidth_set(int,bcm_port_t,int,uint32,uint32);
extern int bcm_esw_rate_bcast_get(int,int *,int *,int);
extern int bcm_esw_rate_bcast_set(int,int,int,int);
extern int bcm_esw_rate_dlfbc_get(int,int *,int *,int);
extern int bcm_esw_rate_dlfbc_set(int,int,int,int);
extern int bcm_esw_rate_get(int,int *,int *);
/* bcm_rate_limit_t_init not dispatchable */
extern int bcm_esw_rate_mcast_get(int,int *,int *,int);
extern int bcm_esw_rate_mcast_set(int,int,int,int);
extern int bcm_esw_rate_set(int,int,int);
extern int bcm_esw_rate_type_get(int,bcm_rate_limit_t *);
extern int bcm_esw_rate_type_set(int,bcm_rate_limit_t *);
extern int bcm_esw_rx_active(int);
extern int bcm_esw_rx_alloc(int,int,uint32,void **);
extern int bcm_esw_rx_burst_get(int,int *);
extern int bcm_esw_rx_burst_set(int,int);
extern int bcm_esw_rx_cfg_get(int,bcm_rx_cfg_t *);
extern int bcm_esw_rx_cfg_init(int);
/* bcm_rx_cfg_t_init not dispatchable */
extern int bcm_esw_rx_channels_running(int,uint32 *);
extern int bcm_esw_rx_clear(int);
extern int bcm_esw_rx_cos_burst_get(int,int,int *);
extern int bcm_esw_rx_cos_burst_set(int,int,int);
extern int bcm_esw_rx_cos_max_len_get(int,int,int *);
extern int bcm_esw_rx_cos_max_len_set(int,int,int);
extern int bcm_esw_rx_cos_rate_get(int,int,int *);
extern int bcm_esw_rx_cos_rate_set(int,int,int);
extern int bcm_esw_rx_cosq_mapping_delete(int,int);
extern int bcm_esw_rx_cosq_mapping_get(int,int,bcm_rx_reasons_t *,bcm_rx_reasons_t *,uint8 *,uint8 *,uint32 *,uint32 *,bcm_cos_queue_t *);
extern int bcm_esw_rx_cosq_mapping_reasons_get(int,bcm_rx_reasons_t *);
extern int bcm_esw_rx_cosq_mapping_set(int,int,bcm_rx_reasons_t,bcm_rx_reasons_t,uint8,uint8,uint32,uint32,bcm_cos_queue_t);
extern int bcm_esw_rx_cosq_mapping_size_get(int,int *);
extern int bcm_esw_rx_cpu_rate_get(int,int *);
extern int bcm_esw_rx_cpu_rate_set(int,int);
extern int bcm_esw_rx_free(int,void *);
extern int bcm_esw_rx_free_enqueue(int,void *);
extern int bcm_esw_rx_init(int);
/* bcm_rx_pool_alloc not dispatchable */
/* bcm_rx_pool_cleanup not dispatchable */
/* bcm_rx_pool_dump not dispatchable */
/* bcm_rx_pool_free not dispatchable */
/* bcm_rx_pool_free_verify not dispatchable */
/* bcm_rx_pool_own not dispatchable */
/* bcm_rx_pool_report not dispatchable */
/* bcm_rx_pool_setup not dispatchable */
/* bcm_rx_pool_setup_done not dispatchable */
extern int bcm_esw_rx_queue_channel_get(int,bcm_cos_queue_t,bcm_rx_chan_t *);
extern int bcm_esw_rx_queue_channel_set(int,bcm_cos_queue_t,bcm_rx_chan_t);
extern int bcm_esw_rx_queue_max_get(int,bcm_cos_queue_t *);
extern int bcm_esw_rx_queue_packet_count_get(int,bcm_cos_queue_t,int *);
extern int bcm_esw_rx_queue_rate_limit_status_get(int,bcm_cos_queue_t,int *);
extern int bcm_esw_rx_queue_register(int,const char *,bcm_cos_queue_t,bcm_rx_cb_f,uint8,void *,uint32);
extern int bcm_esw_rx_queue_unregister(int,bcm_cos_queue_t,bcm_rx_cb_f,uint8);
extern int bcm_esw_rx_rate_get(int,int *);
extern int bcm_esw_rx_rate_set(int,int);
extern int bcm_esw_rx_reasons_get(int,bcm_rx_reasons_t *);
/* bcm_rx_reasons_policer_set mapped to bcm_e_unavail */
extern int bcm_esw_rx_register(int,const char *,bcm_rx_cb_f,uint8,void *,uint32);
/* bcm_rx_remote_pkt_alloc not dispatchable */
extern int bcm_esw_rx_remote_pkt_enqueue(int,bcm_pkt_t *);
/* bcm_rx_remote_pkt_free not dispatchable */
extern int bcm_esw_rx_sched_register(int,bcm_rx_sched_cb);
extern int bcm_esw_rx_sched_unregister(int);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_rx_show(int);
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_rx_start(int,bcm_rx_cfg_t *);
extern int bcm_esw_rx_stop(int,bcm_rx_cfg_t *);
extern int bcm_esw_rx_unit_next_get(int,int *);
extern int bcm_esw_rx_unregister(int,bcm_rx_cb_f,uint8);
extern int bcm_esw_stat_clear(int,bcm_port_t);
extern int bcm_esw_stat_custom_add(int,bcm_port_t,bcm_stat_val_t,bcm_custom_stat_trigger_t);
extern int bcm_esw_stat_custom_check(int,bcm_port_t,bcm_stat_val_t,bcm_custom_stat_trigger_t,int *);
extern int bcm_esw_stat_custom_delete(int,bcm_port_t,bcm_stat_val_t,bcm_custom_stat_trigger_t);
extern int bcm_esw_stat_custom_delete_all(int,bcm_port_t,bcm_stat_val_t);
extern int bcm_esw_stat_custom_get(int,bcm_port_t,bcm_stat_val_t,uint32 *);
extern int bcm_esw_stat_custom_set(int,bcm_port_t,bcm_stat_val_t,uint32);
extern int bcm_esw_stat_get(int,bcm_port_t,bcm_stat_val_t,uint64 *);
extern int bcm_esw_stat_get32(int,bcm_port_t,bcm_stat_val_t,uint32 *);
extern int bcm_esw_stat_init(int);
extern int bcm_esw_stat_sync(int);
extern int bcm_esw_stg_clear(int);
extern int bcm_esw_stg_count_get(int,int *);
extern int bcm_esw_stg_create(int,bcm_stg_t *);
extern int bcm_esw_stg_create_id(int,bcm_stg_t);
extern int bcm_esw_stg_default_get(int,bcm_stg_t *);
extern int bcm_esw_stg_default_set(int,bcm_stg_t);
extern int bcm_esw_stg_destroy(int,bcm_stg_t);
extern int bcm_esw_stg_init(int);
extern int bcm_esw_stg_list(int,bcm_stg_t **,int *);
extern int bcm_esw_stg_list_destroy(int,bcm_stg_t *,int);
extern int bcm_esw_stg_stp_get(int,bcm_stg_t,bcm_port_t,int *);
extern int bcm_esw_stg_stp_set(int,bcm_stg_t,bcm_port_t,int);
extern int bcm_esw_stg_vlan_add(int,bcm_stg_t,bcm_vlan_t);
extern int bcm_esw_stg_vlan_list(int,bcm_stg_t,bcm_vlan_t **,int *);
extern int bcm_esw_stg_vlan_list_destroy(int,bcm_vlan_t *,int);
extern int bcm_esw_stg_vlan_remove(int,bcm_stg_t,bcm_vlan_t);
extern int bcm_esw_stg_vlan_remove_all(int,bcm_stg_t);
/* bcm_stk_fabric_map_get mapped to bcm_e_unavail */
/* bcm_stk_fabric_map_set mapped to bcm_e_unavail */
extern int bcm_esw_stk_fmod_lmod_mapping_get(int,bcm_port_t,bcm_module_t *,bcm_module_t *);
extern int bcm_esw_stk_fmod_lmod_mapping_set(int,bcm_port_t,bcm_module_t,bcm_module_t);
extern int bcm_esw_stk_fmod_smod_mapping_get(int,bcm_port_t,bcm_module_t,bcm_module_t *,bcm_port_t *,uint32 *);
extern int bcm_esw_stk_fmod_smod_mapping_set(int,bcm_port_t,bcm_module_t,bcm_module_t,bcm_port_t,uint32);
extern int bcm_esw_stk_init(int);
extern int bcm_esw_stk_mode_get(int,uint32 *);
extern int bcm_esw_stk_mode_set(int,uint32);
extern int bcm_esw_stk_modid_count(int,int *);
extern int bcm_esw_stk_modid_get(int,int *);
extern int bcm_esw_stk_modid_set(int,int);
extern int bcm_esw_stk_modmap_enable_get(int,bcm_port_t,int *);
extern int bcm_esw_stk_modmap_enable_set(int,bcm_port_t,int);
extern int bcm_esw_stk_modmap_map(int,int,bcm_module_t,bcm_port_t,bcm_module_t *,bcm_port_t *);
extern int bcm_esw_stk_modmap_register(int,bcm_stk_modmap_cb_t);
extern int bcm_esw_stk_modmap_unregister(int);
extern int bcm_esw_stk_modport_add(int,int,bcm_port_t);
extern int bcm_esw_stk_modport_clear(int,int);
extern int bcm_esw_stk_modport_clear_all(int);
extern int bcm_esw_stk_modport_delete(int,int,bcm_port_t);
extern int bcm_esw_stk_modport_get(int,int,int *);
extern int bcm_esw_stk_modport_set(int,int,int);
/* bcm_stk_module_enable mapped to bcm_e_unavail */
/* bcm_stk_module_protocol_get mapped to bcm_e_unavail */
/* bcm_stk_module_protocol_set mapped to bcm_e_unavail */
extern int bcm_esw_stk_my_modid_get(int,int *);
extern int bcm_esw_stk_my_modid_set(int,int);
extern int bcm_esw_stk_pbmp_get(int,bcm_pbmp_t *,bcm_pbmp_t *);
extern int bcm_esw_stk_port_get(int,bcm_port_t,uint32 *);
extern int bcm_esw_stk_port_modmap_group_get(int,bcm_port_t,int *);
extern int bcm_esw_stk_port_modmap_group_max_get(int,int *);
extern int bcm_esw_stk_port_modmap_group_set(int,bcm_port_t,int);
extern int bcm_esw_stk_port_set(int,bcm_port_t,uint32);
extern int bcm_esw_stk_sl_simplex_count_get(int,int *);
extern int bcm_esw_stk_sl_simplex_count_set(int,int);
extern int bcm_esw_stk_ucbitmap_del(int,bcm_port_t,int,bcm_pbmp_t);
extern int bcm_esw_stk_ucbitmap_get(int,int,int,bcm_pbmp_t *);
extern int bcm_esw_stk_ucbitmap_set(int,int,int,bcm_pbmp_t);
extern int bcm_esw_stk_update_callback_register(int,bcm_stk_cb_f,void *);
extern int bcm_esw_stk_update_callback_unregister(int,bcm_stk_cb_f,void *);
extern int bcm_esw_subport_cleanup(int);
/* bcm_subport_config_t_init not dispatchable */
/* bcm_subport_group_config_t_init not dispatchable */
extern int bcm_esw_subport_group_create(int,bcm_subport_group_config_t *,bcm_gport_t *);
extern int bcm_esw_subport_group_destroy(int,bcm_gport_t);
extern int bcm_esw_subport_group_get(int,bcm_gport_t,bcm_subport_group_config_t *);
extern int bcm_esw_subport_init(int);
extern int bcm_esw_subport_port_add(int,bcm_subport_config_t *,bcm_gport_t *);
extern int bcm_esw_subport_port_delete(int,bcm_gport_t);
extern int bcm_esw_subport_port_get(int,bcm_gport_t,bcm_subport_config_t *);
extern int bcm_esw_subport_port_traverse(int,bcm_subport_port_traverse_cb,void *);
extern int bcm_esw_switch_control_get(int,bcm_switch_control_t,int *);
extern int bcm_esw_switch_control_port_get(int,bcm_port_t,bcm_switch_control_t,int *);
extern int bcm_esw_switch_control_port_set(int,bcm_port_t,bcm_switch_control_t,int);
extern int bcm_esw_switch_control_set(int,bcm_switch_control_t,int);
/* bcm_topo_map_get not dispatchable */
/* bcm_topo_map_set not dispatchable */
extern int bcm_esw_topo_port_get(int,int,bcm_port_t *);
/* bcm_trunk_add_info_t_init not dispatchable */
extern int bcm_esw_trunk_bitmap_expand(int,bcm_pbmp_t *);
extern int bcm_esw_trunk_chip_info_get(int,bcm_trunk_chip_info_t *);
/* bcm_trunk_chip_info_t_init not dispatchable */
extern int bcm_esw_trunk_create(int,bcm_trunk_t *);
extern int bcm_esw_trunk_create_id(int,bcm_trunk_t);
extern int bcm_esw_trunk_destroy(int,bcm_trunk_t);
extern int bcm_esw_trunk_detach(int);
extern int bcm_esw_trunk_egress_get(int,bcm_trunk_t,bcm_pbmp_t *);
extern int bcm_esw_trunk_egress_set(int,bcm_trunk_t,bcm_pbmp_t);
extern int bcm_esw_trunk_find(int,bcm_module_t,bcm_port_t,bcm_trunk_t *);
extern int bcm_esw_trunk_get(int,bcm_trunk_t,bcm_trunk_add_info_t *);
extern int bcm_esw_trunk_init(int);
extern int bcm_esw_trunk_mcast_join(int,bcm_trunk_t,bcm_vlan_t,bcm_mac_t);
extern int bcm_esw_trunk_override_ipmc_get(int,bcm_port_t,bcm_trunk_t,int,int *);
extern int bcm_esw_trunk_override_ipmc_set(int,bcm_port_t,bcm_trunk_t,int,int);
extern int bcm_esw_trunk_override_mcast_get(int,bcm_port_t,bcm_trunk_t,int,int *);
extern int bcm_esw_trunk_override_mcast_set(int,bcm_port_t,bcm_trunk_t,int,int);
extern int bcm_esw_trunk_override_ucast_get(int,bcm_port_t,bcm_trunk_t,int,int *);
extern int bcm_esw_trunk_override_ucast_set(int,bcm_port_t,bcm_trunk_t,int,int);
extern int bcm_esw_trunk_override_vlan_get(int,bcm_port_t,bcm_trunk_t,bcm_vlan_t,int *);
extern int bcm_esw_trunk_override_vlan_set(int,bcm_port_t,bcm_trunk_t,bcm_vlan_t,int);
extern int bcm_esw_trunk_pool_get(int,bcm_port_t,bcm_trunk_t,int *,int [BCM_TRUNK_MAX_PORTCNT]);
extern int bcm_esw_trunk_pool_set(int,bcm_port_t,bcm_trunk_t,int,const int [BCM_TRUNK_MAX_PORTCNT]);
extern int bcm_esw_trunk_psc_get(int,bcm_trunk_t,int *);
extern int bcm_esw_trunk_psc_set(int,bcm_trunk_t,int);
extern int bcm_esw_trunk_set(int,bcm_trunk_t,bcm_trunk_add_info_t *);
#ifdef	INCLUDE_L3
extern int bcm_esw_tunnel_config_get(int,bcm_tunnel_config_t *);
extern int bcm_esw_tunnel_config_set(int,bcm_tunnel_config_t *);
/* bcm_tunnel_config_t_init not dispatchable */
extern int bcm_esw_tunnel_dscp_map_create(int,uint32,int *);
extern int bcm_esw_tunnel_dscp_map_destroy(int,int);
extern int bcm_esw_tunnel_dscp_map_get(int,int,bcm_tunnel_dscp_map_t *);
extern int bcm_esw_tunnel_dscp_map_port_get(int,bcm_port_t,bcm_tunnel_dscp_map_t *);
extern int bcm_esw_tunnel_dscp_map_port_set(int,bcm_port_t,bcm_tunnel_dscp_map_t *);
extern int bcm_esw_tunnel_dscp_map_set(int,int,bcm_tunnel_dscp_map_t *);
/* bcm_tunnel_dscp_map_t_init not dispatchable */
extern int bcm_esw_tunnel_initiator_clear(int,bcm_l3_intf_t *);
extern int bcm_esw_tunnel_initiator_get(int,bcm_l3_intf_t *,bcm_tunnel_initiator_t *);
extern int bcm_esw_tunnel_initiator_set(int,bcm_l3_intf_t *,bcm_tunnel_initiator_t *);
/* bcm_tunnel_initiator_t_init not dispatchable */
extern int bcm_esw_tunnel_terminator_add(int,bcm_tunnel_terminator_t *);
extern int bcm_esw_tunnel_terminator_delete(int,bcm_tunnel_terminator_t *);
extern int bcm_esw_tunnel_terminator_get(int,bcm_tunnel_terminator_t *);
/* bcm_tunnel_terminator_t_init not dispatchable */
extern int bcm_esw_tunnel_terminator_update(int,bcm_tunnel_terminator_t *);
#endif	/* INCLUDE_L3 */
extern int bcm_esw_tx(int,bcm_pkt_t *,void *);
extern int bcm_esw_tx_array(int,bcm_pkt_t **,int,bcm_pkt_cb_f,void *);
/* bcm_tx_cpu_tunnel not dispatchable */
/* bcm_tx_cpu_tunnel_get not dispatchable */
/* bcm_tx_cpu_tunnel_set not dispatchable */
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_tx_dv_dump(int,void *);
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_tx_init(int);
extern int bcm_esw_tx_list(int,bcm_pkt_t *,bcm_pkt_cb_f,void *);
extern int bcm_esw_tx_pkt_l2_map(int,bcm_pkt_t *,bcm_mac_t,int);
extern int bcm_esw_tx_pkt_setup(int,bcm_pkt_t *);
#ifdef	BROADCOM_DEBUG
extern int bcm_esw_tx_show(int);
/* bcm_unit_local not dispatchable */
/* bcm_unit_max not dispatchable */
/* bcm_unit_remote not dispatchable */
/* bcm_unit_remote_unit_get not dispatchable */
/* bcm_unit_subtype_get not dispatchable */
/* bcm_unit_valid not dispatchable */
/* bcm_vlan_action_set_t_init not dispatchable */
#endif	/* BROADCOM_DEBUG */
extern int bcm_esw_vlan_control_get(int,bcm_vlan_control_t,int *);
extern int bcm_esw_vlan_control_port_get(int,int,bcm_vlan_control_port_t,int *);
extern int bcm_esw_vlan_control_port_set(int,int,bcm_vlan_control_port_t,int);
extern int bcm_esw_vlan_control_set(int,bcm_vlan_control_t,int);
extern int bcm_esw_vlan_control_vlan_get(int,bcm_vlan_t,bcm_vlan_control_vlan_t *);
extern int bcm_esw_vlan_control_vlan_set(int,bcm_vlan_t,bcm_vlan_control_vlan_t);
/* bcm_vlan_control_vlan_t_init not dispatchable */
extern int bcm_esw_vlan_create(int,bcm_vlan_t);
extern int bcm_esw_vlan_cross_connect_add(int,bcm_vlan_t,bcm_vlan_t,bcm_gport_t,bcm_gport_t);
extern int bcm_esw_vlan_cross_connect_delete(int,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_vlan_cross_connect_delete_all(int);
extern int bcm_esw_vlan_cross_connect_traverse(int,bcm_vlan_cross_connect_traverse_cb,void *);
/* bcm_vlan_data_t_init not dispatchable */
extern int bcm_esw_vlan_default_get(int,bcm_vlan_t *);
extern int bcm_esw_vlan_default_set(int,bcm_vlan_t);
extern int bcm_esw_vlan_destroy(int,bcm_vlan_t);
extern int bcm_esw_vlan_destroy_all(int);
extern int bcm_esw_vlan_dtag_add(int,int,bcm_vlan_t,bcm_vlan_t,int);
extern int bcm_esw_vlan_dtag_delete(int,int,bcm_vlan_t);
extern int bcm_esw_vlan_dtag_delete_all(int);
extern int bcm_esw_vlan_dtag_get(int,int,bcm_vlan_t,bcm_vlan_t *,int *);
extern int bcm_esw_vlan_dtag_range_add(int,int,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t,int);
extern int bcm_esw_vlan_dtag_range_delete(int,int,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_vlan_dtag_range_delete_all(int);
extern int bcm_esw_vlan_dtag_range_get(int,int,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t *,int *);
extern int bcm_esw_vlan_dtag_range_traverse(int,bcm_vlan_dtag_range_traverse_cb,void *);
extern int bcm_esw_vlan_dtag_traverse(int,bcm_vlan_dtag_traverse_cb,void *);
extern int bcm_esw_vlan_init(int);
extern int bcm_esw_vlan_ip4_add(int,bcm_ip_t,bcm_ip_t,bcm_vlan_t,int);
extern int bcm_esw_vlan_ip4_delete(int,bcm_ip_t,bcm_ip_t);
extern int bcm_esw_vlan_ip4_delete_all(int);
extern int bcm_esw_vlan_ip_action_add(int,bcm_vlan_ip_t *,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_ip_add(int,bcm_vlan_ip_t *);
extern int bcm_esw_vlan_ip_delete(int,bcm_vlan_ip_t *);
extern int bcm_esw_vlan_ip_delete_all(int);
/* bcm_vlan_ip_t_init not dispatchable */
extern int bcm_esw_vlan_list(int,bcm_vlan_data_t **,int *);
extern int bcm_esw_vlan_list_by_pbmp(int,bcm_pbmp_t,bcm_vlan_data_t **,int *);
extern int bcm_esw_vlan_list_destroy(int,bcm_vlan_data_t *,int);
extern int bcm_esw_vlan_mac_action_add(int,bcm_mac_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_mac_add(int,bcm_mac_t,bcm_vlan_t,int);
extern int bcm_esw_vlan_mac_delete(int,bcm_mac_t);
extern int bcm_esw_vlan_mac_delete_all(int);
extern int bcm_esw_vlan_mcast_flood_get(int,bcm_vlan_t,bcm_vlan_mcast_flood_t *);
extern int bcm_esw_vlan_mcast_flood_set(int,bcm_vlan_t,bcm_vlan_mcast_flood_t);
/* bcm_vlan_policer_get mapped to bcm_e_unavail */
/* bcm_vlan_policer_set mapped to bcm_e_unavail */
extern int bcm_esw_vlan_port_add(int,bcm_vlan_t,bcm_pbmp_t,bcm_pbmp_t);
/* bcm_vlan_port_create mapped to bcm_e_unavail */
extern int bcm_esw_vlan_port_default_action_get(int,bcm_port_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_port_default_action_set(int,bcm_port_t,bcm_vlan_action_set_t *);
/* bcm_vlan_port_destroy mapped to bcm_e_unavail */
extern int bcm_esw_vlan_port_egress_default_action_get(int,bcm_port_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_port_egress_default_action_set(int,bcm_port_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_port_get(int,bcm_vlan_t,bcm_pbmp_t *,bcm_pbmp_t *);
extern int bcm_esw_vlan_port_protocol_action_add(int,bcm_port_t,bcm_port_frametype_t,bcm_port_ethertype_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_port_remove(int,bcm_vlan_t,bcm_pbmp_t);
/* bcm_vlan_stat_enable_set mapped to bcm_e_unavail */
/* bcm_vlan_stat_get mapped to bcm_e_unavail */
/* bcm_vlan_stat_get32 mapped to bcm_e_unavail */
/* bcm_vlan_stat_set mapped to bcm_e_unavail */
/* bcm_vlan_stat_set32 mapped to bcm_e_unavail */
extern int bcm_esw_vlan_stg_get(int,bcm_vlan_t,bcm_stg_t *);
extern int bcm_esw_vlan_stg_set(int,bcm_vlan_t,bcm_stg_t);
extern int bcm_esw_vlan_stp_get(int,bcm_vlan_t,bcm_port_t,int *);
extern int bcm_esw_vlan_stp_set(int,bcm_vlan_t,bcm_port_t,int);
extern int bcm_esw_vlan_translate_action_add(int,bcm_gport_t,bcm_vlan_translate_key_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_translate_action_delete(int,bcm_gport_t,bcm_vlan_translate_key_t,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_vlan_translate_action_get(int,bcm_gport_t,bcm_vlan_translate_key_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_translate_action_range_add(int,bcm_gport_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_translate_action_range_delete(int,bcm_gport_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_vlan_translate_action_range_delete_all(int);
extern int bcm_esw_vlan_translate_action_range_get(int,bcm_gport_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_translate_action_range_traverse(int,bcm_vlan_translate_action_range_traverse_cb,void *);
extern int bcm_esw_vlan_translate_action_traverse(int,bcm_vlan_translate_action_traverse_cb,void *);
extern int bcm_esw_vlan_translate_add(int,int,bcm_vlan_t,bcm_vlan_t,int);
extern int bcm_esw_vlan_translate_delete(int,int,bcm_vlan_t);
extern int bcm_esw_vlan_translate_delete_all(int);
extern int bcm_esw_vlan_translate_egress_action_add(int,int,bcm_vlan_t,bcm_vlan_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_translate_egress_action_delete(int,int,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_vlan_translate_egress_action_get(int,int,bcm_vlan_t,bcm_vlan_t,bcm_vlan_action_set_t *);
extern int bcm_esw_vlan_translate_egress_action_traverse(int,bcm_vlan_translate_egress_action_traverse_cb,void *);
extern int bcm_esw_vlan_translate_egress_add(int,int,bcm_vlan_t,bcm_vlan_t,int);
extern int bcm_esw_vlan_translate_egress_delete(int,int,bcm_vlan_t);
extern int bcm_esw_vlan_translate_egress_delete_all(int);
extern int bcm_esw_vlan_translate_egress_get(int,int,bcm_vlan_t,bcm_vlan_t *,int *);
extern int bcm_esw_vlan_translate_egress_traverse(int,bcm_vlan_translate_egress_traverse_cb,void *);
extern int bcm_esw_vlan_translate_get(int,int,bcm_vlan_t,bcm_vlan_t *,int *);
extern int bcm_esw_vlan_translate_range_add(int,int,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t,int);
extern int bcm_esw_vlan_translate_range_delete(int,int,bcm_vlan_t,bcm_vlan_t);
extern int bcm_esw_vlan_translate_range_delete_all(int);
extern int bcm_esw_vlan_translate_range_get(int,int,bcm_vlan_t,bcm_vlan_t,bcm_vlan_t *,int *);
extern int bcm_esw_vlan_translate_range_traverse(int,bcm_vlan_translate_range_traverse_cb,void *);
extern int bcm_esw_vlan_translate_traverse(int,bcm_vlan_translate_traverse_cb,void *);
extern int bcm_esw_vpls_bitmap_add(int,uint32,bcm_vlan_t,bcm_pbmp_t);
extern int bcm_esw_vpls_bitmap_delete(int,uint32);
extern int bcm_esw_vpls_bitmap_delete_all(int);
extern int bcm_esw_vpls_bitmap_detach(int);
extern int bcm_esw_vpls_bitmap_get(int,uint32,bcm_vlan_t *,bcm_pbmp_t *);
extern int bcm_esw_vpls_bitmap_init(int);
/* bcm_vswitch_create mapped to bcm_e_unavail */
/* bcm_vswitch_create_with_id mapped to bcm_e_unavail */
/* bcm_vswitch_destroy mapped to bcm_e_unavail */
/* bcm_vswitch_detach mapped to bcm_e_unavail */
/* bcm_vswitch_init mapped to bcm_e_unavail */
/* bcm_vswitch_port_add mapped to bcm_e_unavail */
/* bcm_vswitch_port_delete mapped to bcm_e_unavail */
/* bcm_vswitch_port_delete_all mapped to bcm_e_unavail */
/* bcm_vswitch_port_get mapped to bcm_e_unavail */
extern int bcm_e_unavail(void);
extern int accton_esw_field_entry_copy_id(int,bcm_field_group_t,bcm_field_entry_t);

/* added by charles, accton expantion for phy control call*/
extern int bcm_esw_port_phy_ioctl(int unit,bcm_port_t port,unsigned int cmd,void * io_req);

#endif	/* BCM_ESW_SUPPORT */
#endif	/* !_BCM_INT_ESW_DISPATCH_H */
