#ifndef _TEMP_H
#define _TEMP_H

#define	PING_MGR_MAX_PING_SIZE				SYS_ADPT_MAX_PING_SIZE
#define SNTP_MAX_POLLTIME				 MAX_sntpPollInterval			/* Max polling time */
#define SNTP_MIN_POLLTIME				 MIN_sntpPollInterval				/* Min polling time */ 
#define ACL_ETHER_TYPE_MIN_RANGE      MIN_aclMacAceMinEtherType
#define ACL_ETHER_TYPE_MAX_RANGE      MAX_aclMacAceMinEtherType
#define ACL_VID_MIN_RANGE             MIN_aclMacAceMinVid
#define ACL_VID_MAX_RANGE             MAX_aclMacAceMinVid

#define ACL_PORT_MIN_BITMASK_RANGE     MIN_aclIpAceSourcePortBitmask
#define ACL_PORT_MAX_BITMASK_RANGE     MAX_aclIpAceSourcePortBitmask
#define ACL_PORT_BITMASK_ANY           MIN_aclIpAceSourcePortBitmask
#define ACL_PORT_BITMASK_SINGLE        MAX_aclIpAceSourcePortBitmask 

#define ACL_TCP_CODE_ANY               MIN_aclIpAceControlCode
#define ACL_TCP_CODE_MIN_RANGE         MIN_aclIpAceControlCode
#define ACL_TCP_CODE_MAX_RANGE         MAX_aclIpAceControlCode


#define ACL_TCP_CODE_BITMASK_ANY       MIN_aclIpAceControlCodeBitmask
#define ACL_TCP_CODE_BITMASK_MIN_RANGE MIN_aclIpAceControlCodeBitmask
#define ACL_TCP_CODE_BITMASK_MAX_RANGE MAX_aclIpAceControlCodeBitmask

#define ACL_ETH2_ETHERTYPE_MIN_RANGE   MIN_aclMacAceMinEtherType
#define ACL_ETH2_ETHERTYPE_MAX_RANGE   MAX_aclMacAceMinEtherType
#define	PING_MGR_MIN_PING_SIZE				SYS_ADPT_MIN_PING_SIZE
#define ACL_PROTOCOL_MAX_VALID_RANGE  (MAX_aclIpAceProtocol - 1) 
#define ACL_PROTOCOL_MIN_RANGE        MIN_aclIpAceProtocol
#define ACL_DSCP_MAX_VALID_RANGE        (MAX_aclIpAceDscp - 1 )
#define ACL_DSCP_MIN_RANGE             MIN_aclIpAceDscp
#define ACL_TOS_MAX_VALID_RANGE        (MAX_aclIpAceTos - 1 )
#define ACL_TOS_MIN_RANGE              MIN_aclIpAceTos
#define ACL_PORT_MAX_VALID_RANGE       MAX_aclIpAceMaxSourcePort
#define ACL_PORT_MIN_RANGE             MIN_aclIpAceMinSourcePort
#define ACL_PRECEDENCE_MAX_VALID_RANGE (MAX_aclIpAcePrec-1 )
#define ACL_PRECEDENCE_MIN_RANGE       MIN_aclIpAcePrec
#define PING_MGR_MAX_PING_NBR                   SYS_ADPT_MAX_PING_NUM

typedef enum EH_TYPE_Msg_E
{
    EH_TYPE_MSG_VALUE_OUT_OF_RANGE = 1,
    EH_TYPE_MSG_INVALID_IP,
    EH_TYPE_MSG_INVALID,
    EH_TYPE_MSG_INVALID_VALUE,
    EH_TYPE_MSG_INVALID_PARAMETER,
    EH_TYPE_MSG_IS_INVALID,
    EH_TYPE_MSG_GW_INVALID,
    EH_TYPE_MSG_FAILED_TO,
    EH_TYPE_MSG_FAILED_TO_ADD,
    EH_TYPE_MSG_FAILED_TO_GET,
    EH_TYPE_MSG_FAILED_TO_SET,
    EH_TYPE_MSG_FAILED_TO_DELETE,
    EH_TYPE_MSG_EXISTS,
    EH_TYPE_MSG_NOT_EXIST,
    EH_TYPE_MSG_MCAST_PORT_NOT_EXIST,
    EH_TYPE_MSG_TIMEOUT,
    EH_TYPE_MSG_TBL_FULL,
    EH_TYPE_MSG_GARP_TIMER_SET_DEBIED,
    EH_TYPE_MSG_VLAN_INST_ID_SET_DENIED,
    EH_TYPE_MSG_NOT_MEMBER,
    EH_TYPE_MSG_NOT_SUPPORTED,
    EH_TYPE_MSG_NO_ACCESS_RIGHT,
    EH_TYPE_MSG_NO_TIME_SRV,
    EH_TYPE_MSG_MAXIMUM_EXCEEDED,
    EH_TYPE_MSG_LOG_LEVEL_RAM_LOWER,
    EH_TYPE_MSG_LOG_LEVEL_FLASH_HIGER,
    EH_TYPE_MSG_SRV_IP_NOT_ZERO,
    EH_TYPE_MSG_FILE_PROTECTED,
    EH_TYPE_MSG_FILE_SYSTEM_BUSY,
    EH_TYPE_MSG_FILENAME_TOO_LONG,
    EH_TYPE_MSG_FILENAME_NOT_NULL,
    EH_TYPE_MSG_FILE_XFER_BUSY,
    EH_TYPE_MSG_CMD_INCOMPLETE,
    EH_TYPE_MSG_CMD_AMBIGUOUS,
    EH_TYPE_MSG_CMD_UNRECOGNIIZED,
    EH_TYPE_MSG_CMD_INV_PARAM,
    EH_TYPE_MSG_CMD_CONSOLE_ONLY,
    EH_TYPE_MSG_CMD_NOT_FOR_MULT_PORTS,
    EH_TYPE_MSG_CMD_INPUT_INVALID,
    EH_TYPE_MSG_CLI_EXEC_TIMEOUT_TELNET,
    EH_TYPE_MSG_SWITCH_GW_SUBNET,
    EH_TYPE_MSG_SECRET_KEY_SET,
    EH_TYPE_MSG_CERTIFICATE_BUF_IN_USE,
    EH_TYPE_MSG_SSL_HANDSHAKE_FAILED,
    EH_TYPE_MSG_IGMPSNP_DISABLED,
    EH_TYPE_MSG_DEF_GW_ADD_DENIED,
    EH_TYPE_MSG_SUBNET_NOT_FOUND,
    EH_TYPE_MSG_SUBNET_BOUND_TO_INTERF,
    EH_TYPE_MSG_RCV_PKT_UNEXPECTED,
    EH_TYPE_MSG_PTY_REQUESTED,
    EH_TYPE_MSG_CRC_ATTACK_DETECTED,
    EH_TYPE_MSG_INVAL_CAPABILITY,
    EH_TYPE_MSG_INVAL_F_SPD_DUP,
    EH_TYPE_MSG_1000F_FORCE_DENIED,
    EH_TYPE_MSG_MGMT_PORT_CNFG,
    EH_TYPE_MSG_SRV_BLADE_PORT_CNFG,
    EH_TYPE_MSG_PVLAN_SAME_UL_DL,
    EH_TYPE_MSG_PVLAN_DISABLED,
    EH_TYPE_MSG_WRR_DISABLED,
    EH_TYPE_MSG_SPD_DUPLEX_UNSET,
    EH_TYPE_MSG_STATIC_ADDR_SET_PORT,
    EH_TYPE_MSG_INTERF_NOT_A_TRUNK,
    EH_TYPE_MSG_TRUNK_CNFG_ERR,
    EH_TYPE_MSG_TRUNK_CNFG_ERR_BC_STORM,
    EH_TYPE_MSG_TRUNK_NOT_PRESENT,
    EH_TYPE_MSG_TRUNK_NO_MEMBER,
    EH_TYPE_MSG_TRUNK_MEMBERS_SAME,
    EH_TYPE_MSG_TRUNK_DL_PORTS_ADJACENT,
    EH_TYPE_MSG_MIRROR_MON_CONFLICT,
    EH_TYPE_MSG_MIRROR_NOT_SAME_CHIP,
    EH_TYPE_MSG_MIRROR_DEST_SAME,
    EH_TYPE_MSG_MSTP_SUPPORTED_ONLY,
    EH_TYPE_MSG_XSTP_INFO_GET_FAILED,
    EH_TYPE_MSG_STA_MODE_SET_FAILED,
    EH_TYPE_MSG_PROT_MIG_UNSUPPORTED,
    EH_TYPE_MSG_VLAN_INST_ID_SET_FAIL,
    EH_TYPE_MSG_PVLAN_UPDOWN_LNK_SET,
    EH_TYPE_MSG_TRUNK_MEMBER_JOIN,
    EH_TYPE_MSG_TRUNK_MEMBER_CNFG_ERR,
    EH_TYPE_MSG_MUTUAL_EXCLUSIVE,
    EH_TYPE_MSG_HELP,
    EH_TYPE_MSG_100FIBER_ERR_AUTO_NEGO,
    EH_TYPE_MSG_QUEUE_WRR_WEIGHT,
    EH_TYPE_MSG_MIRROR_NOT_SUPPORT,
    EH_TYPE_MSG_NOT_TRUNK_MEMBER,
    EH_TYPE_MSG_MAX_ALLOW_RATE_LIMIT,
    EH_TYPE_MSG_IPFLT_IP_RANGE,
    EH_TYPE_MSG_TASK_CREATE,
    EH_TYPE_MSG_SEMPH_CREATE,
    EH_TYPE_MSG_ALLOCATE,
    EH_TYPE_MSG_MEM_ALLOCATE,
    EH_TYPE_MSG_MEM_FREE,
    EH_TYPE_MSG_L_MEM_ALLOCATE,
    EH_TYPE_MSG_L_MEM_FREE,
    EH_TYPE_MSG_L_PT_ALLOCATE,
    EH_TYPE_MSG_L_PT_FREE,
    EH_TYPE_MSG_NULL_POINTER,
    EH_TYPE_MSG_NOT_IN_MASTER_MODE,
    EH_TYPE_MSG_SOCKET_OP_FAILED,
    EH_TYPE_MSG_LACP_TRUNK_REMOVE,
    EH_TYPE_MSG_DEB_MSG,
    EH_TYPE_MSG_NO_SPD_DUP_IN_AUTO_NEGO,
    EH_TYPE_MSG_COUNTER_GET,
    EH_TYPE_MSG_COUNTER_CLEAR,
    EH_TYPE_MSG_SWITCH_CHIP_SET,
    EH_TYPE_MSG_SWITCH_CHIP_GET,
    EH_TYPE_MSG_LOC_EN,
    EH_TYPE_MSG_LOC_DIS,
    EH_TYPE_MSG_LOC_GET,
    EH_TYPE_MSG_LOC_SET,
    EH_TYPE_MSG_LOC_ADD,
    EH_TYPE_MSG_LOC_DEL,
    EH_TYPE_MSG_LOC_RESET,
    EH_TYPE_MSG_LOC_CREATE,
    EH_TYPE_MSG_LOC_DESTROY,
    EH_TYPE_MSG_LOC_PORT_SEC_ACTION,
    EH_TYPE_MSG_REM_UNIT_EN,
    EH_TYPE_MSG_REM_UNIT_DIS,
    EH_TYPE_MSG_REM_UNIT_SET,
    EH_TYPE_MSG_REM_UNIT_ADD,
    EH_TYPE_MSG_REM_UNIT_DEL,
    EH_TYPE_MSG_REM_UNIT_RESET,
    EH_TYPE_MSG_REM_UNIT_CREATE,
    EH_TYPE_MSG_REM_UNIT_DESTROY,
    EH_TYPE_MSG_REM_PORT_EN,
    EH_TYPE_MSG_REM_PORT_DIS,
    EH_TYPE_MSG_REM_PORT_SET,
    EH_TYPE_MSG_REM_PORT_ADD,
    EH_TYPE_MSG_REM_PORT_DEL,
    EH_TYPE_MSG_REM_PORT_CREATE,
    EH_TYPE_MSG_REM_PORT_DESTROY,
    EH_TYPE_MSG_REM_PORT_SEC_ACTION,
    EH_TYPE_MSG_SLAVE_UNIT_NOTIFY,
    EH_TYPE_MSG_FFP_STATIS_INCORRECT,
    EH_TYPE_MSG_NO_VLAN_IN_INSTANCE
}EH_TYPE_Msg_T;

#endif /* _TEMP_H */
